%define rname wallet_engine
# upstream sets no soname for the cdylib, this one is ALT-specific:
# bump it on every incompatible change of the exported UniFFI API
# (the generated C++ binding checks the API checksums at runtime)
%define sover 0
# the revision used by Telegram Desktop 7.3.0
# (Telegram/build/docker/centos_env/Dockerfile)
%define commit e59e0d89d7ee90c388bf36e3334c5b276f396697

Name: libwallet_engine
Version: 0.0.7
Release: alt1

Summary: TON wallet engine library with a C++ binding

License: MIT OR Apache-2.0
Group: System/Libraries
Url: https://github.com/i582/wallet-engine

# Source-url: https://github.com/i582/wallet-engine/archive/%commit/wallet-engine-%version.tar.gz
Source: %name-%version.tar
Source1: %name-development-%version.tar
Source2: config.toml
# Telegram Desktop applies it on top of the engine and uses its API
# (ton_connect_tlb module, decode_sign_data_cell):
# https://github.com/desktop-app/patches/blob/master/wallet-engine.patch
Patch: wallet-engine.patch

BuildRequires(pre): rpm-macros-rust
BuildRequires: rpm-build-rust /proc
BuildRequires: gcc-c++

%description
Wallet Engine is a Rust library for TON wallet applications: it creates and
imports wallets, parses and formats TON addresses, signs and submits
transfers, and connects dApps over TON Connect. It is used by Telegram
Desktop 7.3 and newer.

%package -n %name%sover
Summary: TON wallet engine library
Group: System/Libraries

%description -n %name%sover
Wallet Engine is a Rust library for TON wallet applications: it creates and
imports wallets, parses and formats TON addresses, signs and submits
transfers, and connects dApps over TON Connect. It is used by Telegram
Desktop 7.3 and newer.

%package devel
Summary: Development files for %name
Group: Development/C++
Requires: %name%sover = %EVR

%description devel
Wallet Engine is a Rust library for TON wallet applications: it creates and
imports wallets, parses and formats TON addresses, signs and submits
transfers, and connects dApps over TON Connect. It is used by Telegram
Desktop 7.3 and newer.

This package contains the link library and the C++ binding generated by
UniFFI (wallet_engine.hpp and wallet_engine.cpp, which the application
compiles itself).

%prep
%setup -a1
%patch -p1
# use the system Rust toolchain
rm -v rust-toolchain.toml
install -vD %SOURCE2 .cargo/config.toml

%build
export CARGO_HOME="$PWD/.cargo"
# the same profile overrides as in the Telegram Desktop build;
# rustc does not set a soname for a cdylib, so pass it explicitly
cargo rustc --offline --locked --lib --release --crate-type cdylib \
    --config "profile.release.opt-level=3" \
    --config "profile.release.panic='unwind'" \
    -- -C link-arg=-Wl,-soname,lib%rname.so.%sover

# generate the C++ binding from the metadata embedded in the library
cargo run --offline --locked --manifest-path bindgen/cpp/bindgen/Cargo.toml -- \
    --library --out-dir out/%rname target/release/lib%rname.so

%check
export CARGO_HOME="$PWD/.cargo"
# test the optimized code: the deep cell tests run on a 512 KiB thread stack,
# which unoptimized frames overflow on aarch64
cargo test --offline --locked --lib --release \
    --config "profile.release.opt-level=3" \
    --config "profile.release.panic='unwind'"
# the generated binding must compile and link against the library
cd out/%rname
echo '#include "wallet_engine.hpp"
int main() { return 0; }' > check.cpp
g++ -std=c++20 -Wno-pessimizing-move check.cpp wallet_engine.cpp \
    -L../../target/release -l%rname -Wl,--no-undefined -o check
rm -v check check.cpp

%install
install -pD -m755 target/release/lib%rname.so %buildroot%_libdir/lib%rname.so.%version
ln -s lib%rname.so.%version %buildroot%_libdir/lib%rname.so.%sover
ln -s lib%rname.so.%sover %buildroot%_libdir/lib%rname.so

mkdir -p %buildroot%_includedir/%rname/
install -pm644 out/%rname/* %buildroot%_includedir/%rname/

%files -n %name%sover
%doc README.md CHANGELOG.md LICENSE-MIT LICENSE-APACHE
%_libdir/lib%rname.so.%sover
%_libdir/lib%rname.so.%version

%files devel
%_libdir/lib%rname.so
%_includedir/%rname/

%changelog
* Fri Oct 09 2026 Vitaly Lipatov <lav@altlinux.ru> 0.0.7-alt1
- initial build for Sisyphus
