#
#   - Text-MicroTemplate -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   (ALT Linux revision)
#   The following arguments were used:
#       Text::MicroTemplate
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Text-MicroTemplate
%define m_distro Text-MicroTemplate
%define m_name Text-MicroTemplate
%define m_author_id unknown
%define _enable_test 1

Name: perl-Text-MicroTemplate
Version: 0.18
Release: alt1

Summary: Micro template engine with Perl5 language

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Eugene Prokopiev <enp@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/K/KA/KAZUHO/%m_distro-%version.tar.gz

# Automatically added by buildreq on Mon Feb 20 2012
BuildRequires: perl-IO-stringy perl-devel

%description
None.

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/*

%changelog
* Mon Feb 20 2012 Eugene Prokopiev <enp@altlinux.ru> 0.18-alt1
- initial build for ALT Linux Sisyphus

