#
#   - Data-OptList -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Data::OptList
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Data-OptList
%define m_distro Data-OptList
%define m_name Data-OptList
%define m_author_id unknown
%define _enable_test 1

Name: perl-Data-OptList
Version: 0.107
Release: alt1

Summary: Data-OptList - Perl module

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Mikhail Pokidko <pma@altlinux.org>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/R/RJ/RJBS/Data-OptList-0.107.tar.gz

# Automatically added by buildreq on Wed Apr 21 2010
BuildRequires: perl-Module-Install perl-Params-Util perl-Sub-Install

%description
None.

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc Changes README
%perl_vendor_privlib/Data*

%changelog
* Mon Sep 19 2011 Igor Vlasenko <viy@altlinux.ru> 0.107-alt1
- automated CPAN update

* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.106-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Wed Apr 21 2010 Alexey Tourbin <at@altlinux.ru> 0.106-alt1
- 0.103 -> 0.106

* Thu Sep 04 2008 Mikhail Pokidko <pma@altlinux.org> 0.103-alt2
- sisyphus_check fixes

* Wed May 14 2008 Mikhail Pokidko <pma@altlinux.org> 0.103-alt1
- first build for ALT Linux Sisyphus

