Name:    sscg
Version: 4.0.3
Release: alt1

Summary: Simple SSL certificate generator
License: GPL-3.0-only
Group:   Security/Networking
Url:     https://github.com/sgallagher/sscg

Source: %name-%version.tar

BuildRequires(pre): meson
BuildRequires: cmake
BuildRequires: openssl
BuildRequires: openssl-devel
BuildRequires: libpath_utils-devel
BuildRequires: libtalloc-devel
BuildRequires: libpopt-devel
BuildRequires: help2man

%description
A utility to aid in the creation of more secure "self-signed"
certificates. The certificates created by this tool are generated in a
way so as to create a CA certificate that can be safely imported into a
client machine to trust the service certificate without needing to set
up a full PKI environment and without exposing the machine to a risk of
false signatures from the service certificate.

%prep
%setup

%build
%meson
%meson_build

%install
%meson_install

%check
%__meson_test -t 10

%files
%doc README.md
%_bindir/%name
%_man8dir/%name.*

%changelog
* Tue Feb 17 2026 Andrey Limachko <liannnix@altlinux.org> 4.0.3-alt1
- Update to upstream version 4.0.3.
- Breaking changes:
  * Minimum OpenSSL version raised to 3.x (dropped 1.1/2.x support).
  * DH parameters no longer generated by default (use --dhparams-file).
  * Custom DH parameter generation deprecated (will be removed in 5.0).
  * Removed --package argument (was deprecated in 3.0).
  * Minimum RSA key strength for private CA raised to 4096 bits.
- New features:
  * Added ML-DSA (Module-Lattice Digital Signature Algorithm) support for post-quantum cryptography.
  * Added ECDSA (Elliptic Curve Digital Signature Algorithm) key generation.
  * Enhanced command-line interface with logically grouped help output.
- Improvements:
  * Extended maximum DNS name length to 255 characters.
  * Improved compatibility with OpenSSL 3.4+.
  * Enhanced security: basicConstraint marked as critical for CA certificates.
  * Added internationalization (i18n) support and updated README.
  * Refactored key creation logic for better modularity.
  * Reworked file opening to avoid TOCTOU issues.
- Bug fixes:
  * Fixed IP address handling in CA certificate SAN constraints.
  * Fixed regression when attempting to use same file for both CA and certificate.
  * Fixed various issues discovered by Coverity analysis.
  * Fixed detection of invalid hashes.
  * Better handling of files in general.

* Tue Feb 07 2023 Andrey Limachko <liannnix@altlinux.org> 3.0.3-alt1
- Initial build
