#
#   - parent -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       parent
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module parent
%define m_distro parent
%define m_name parent
%define m_author_id CORION
%define _enable_test 1

Name: perl-parent
Version: 0.225
Release: alt1

Summary: Establish an ISA relationship with base classes at compile time

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/parent/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/C/CO/CORION/parent-0.225.tar.gz

# Automatically added by buildreq on Fri Sep 05 2008 (-bi)
BuildRequires: perl-devel

%description
"parent" allows you to both load one or more modules, while setting up inheritance from
those modules at the same time
		
		package Baz;
		use parent qw(Foo Bar);

mostly is similar in effect to

    package Baz;
    BEGIN {
        require Foo;
        require Bar;
        push @ISA, qw(Foo Bar);
    }


%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/parent*
%doc Changes

%changelog
* Mon Sep 19 2011 Igor Vlasenko <viy@altlinux.ru> 0.225-alt1
- automated CPAN update

* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.223-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Fri Jul 16 2010 Igor Vlasenko <viy@altlinux.ru> 0.223-alt1
- automated CPAN update

* Fri Sep 05 2008 Michael Bochkaryov <misha@altlinux.ru> 0.221-alt2
- fix directory ownership violation

* Wed Jun 25 2008 Michael Bochkaryov <misha@altlinux.ru> 0.221-alt1
- first build for ALT Linux Sisyphus

