#
#   - Data::Random -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Data-Random-0.05.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Data-Random
%define m_distro Data-Random
%define m_name Data::Random
%define m_author_id unknown
%define _enable_test 1

Name: perl-Data-Random
Version: 0.05
Release: alt2.1

Summary: Perl module to generate random data

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vladimir A. Svyatoshenko <svyt@altlinux.ru>

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Mon Jun 11 2007
BuildRequires: perl-Date-Calc perl-devel perl-GD2

%description
A module used to generate random data.  Useful mostly for test programs.

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Data*

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.05-alt2.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Oct 07 2008 Vladimir A. Svyatoshenko <svyt@altlinux.ru> 0.05-alt2
- fixed build

* Mon Jun 11 2007 Vladimir A. Svyatoshenko <svyt@altlinux.ru> 0.05-alt1
- first build for ALT Linux Sisyphus

