#
#   - prefork -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --spec-only prefork
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module prefork
%define m_distro prefork
%define m_name prefork
%define m_author_id ADAMK
%define _enable_test 1

Name: perl-prefork
Version: 1.05
Release: alt1.1

Summary: Pragma to ensure modules are fully loaded before forking

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/~adamk/prefork-%version/

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source0: http://www.cpan.org/authors/id/E/ET/ETHER/%{module}-%{version}.tar.gz
#Source: http://www.cpan.org/modules/by-module/%m_distro/%m_distro-%version.tar.bz2

# Automatically added by buildreq on Sun Jul 22 2007
BuildRequires: perl-Test-Pod

%description
Optimized module loading for forking or non-forking processes.

%prep
%setup -q -n %{module}-%{version}

%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%doc Changes README CONTRIBUTING
%perl_vendor_privlib/prefork.pm

%changelog
* Wed Apr 22 2020 Igor Vlasenko <viy@altlinux.ru> 1.05-alt1.1
- dropped deprecated BR: perl-Module-Install

* Sun Oct 28 2018 Igor Vlasenko <viy@altlinux.ru> 1.05-alt1
- automated CPAN update

* Fri Jul 16 2010 Igor Vlasenko <viy@altlinux.ru> 1.04-alt1
- automated CPAN update

* Sat Sep 06 2008 Vitaly Lipatov <lav@altlinux.ru> 1.02-alt2
- fix directory ownership violation
- disable man packaging

* Sat Jun 14 2008 Vitaly Lipatov <lav@altlinux.ru> 1.02-alt1
- new version 1.02 (with rpmrb script)

* Sun Jul 22 2007 Vitaly Lipatov <lav@altlinux.ru> 1.01-alt1
- new version 1.01 (with rpmrb script)
- update buildreq

* Tue Jul 12 2005 Vitaly Lipatov <lav@altlinux.ru> 0.04-alt1
- first build for ALT Linux Sisyphus
