%define goipath github.com/linuxdeepin/dde-api

Name: deepin-api
Version: 6.0.44
Release: alt1

Summary: Golang bingding for dde-daemon

License: GPL-3.0+
Group: Graphical desktop/Other
Url: https://github.com/linuxdeepin/dde-api
Vcs: https://github.com/linuxdeepin/dde-api

# Source-url: https://github.com/linuxdeepin/dde-api/archive/%version/dde-api-%version.tar.gz
Source0: dde-api-%version.tar
# go mod vendor -o ../vendor
Source1: vendor.tar
Patch: %name-%version-%release.patch

#Requires: deepin-desktop-base rfkill
#Requires(pre): shadow-utils dbus-tools

BuildRequires(pre): rpm-build-golang rpm-build-python3
BuildRequires: gcc-c++ libgtk+3-devel glib2-devel libgio-devel libgdk-pixbuf-xlib-devel libXcursor-devel libpoppler-glib-devel librsvg-devel libXfixes-devel libalsa-devel libpulseaudio-devel libgudev-devel libXi-devel deepin-gettext-tools
BuildRequires: /proc

%description
%summary.

%package -n golang-%name-devel
Summary: %summary
Group: Graphical desktop/Other
AutoReq: no
# BuildArch: noarch

%description -n golang-%name-devel
%summary.

This package contains library source intended for
building other packages which use import path with
%goipath prefix.

%package devel
Summary: %summary
Group: Development/C++
BuildArch: noarch
Provides: dde-api-devel = %EVR

%description devel
This package provides headers for %name.

%prep
%setup -n dde-api-%version -a1
%autopatch -p1
sed -i 's|/usr/sbin/locale-gen|locale-gen|' \
  locale-helper/main.go
sed -i 's|/usr/bin/true|/bin/true|' \
  misc/systemd/system/deepin-shutdown-sound.service
sed -i 's|/usr/lib/libdeepin-event-log.so|%_libdir/libdeepin-event-log.so|' \
  cpp-include/eventlogger.hpp

%build
export GOFLAGS="-mod=vendor"
%make

%install
export GOPATH="%go_path"
%makeinstall_std SYSTEMD_SERVICE_DIR="%_unitdir" -i

%files
%doc README.md LICENSE debian/changelog
%_bindir/*
%dir %_libexecdir/deepin-api/
%_libexecdir/deepin-api/*
%_iconsdir/hicolor/??x??/actions/*
%_iconsdir/hicolor/???x???/actions/*
%_iconsdir/hicolor/scalable/actions/*
%_datadir/dbus-1/*
%_datadir/polkit-1/*
%_unitdir/*.service
%_sharedstatedir/polkit-1/*
%dir %_datadir/dde-api/
%dir %_datadir/dde-api/data/
%_datadir/dde-api/data/*

%files -n golang-%name-devel
%go_path/src/%goipath

%files devel
%dir %_includedir/dde-api/
%_includedir/dde-api/eventlogger.hpp
%dir %_datadir/cmake/DDEAPI/
%_datadir/cmake/DDEAPI/DDEAPIConfig.cmake

%changelog
* Tue Jun 16 2026 Leontiy Volodin <lvol@altlinux.org> 6.0.44-alt1
- New version 6.0.44.

* Thu Jun 04 2026 Leontiy Volodin <lvol@altlinux.org> 6.0.43-alt1
- New version 6.0.43.
- Added devel subpackage.

* Fri Apr 17 2026 Leontiy Volodin <lvol@altlinux.org> 6.0.38-alt1
- New version 6.0.38.

* Thu Mar 26 2026 Leontiy Volodin <lvol@altlinux.org> 6.0.37-alt1
- New version 6.0.37.

* Thu Mar 05 2026 Leontiy Volodin <lvol@altlinux.org> 6.0.35-alt1
- New version 6.0.35.

* Wed Jan 14 2026 Leontiy Volodin <lvol@altlinux.org> 6.0.33-alt1
- New version 6.0.33.

* Fri Nov 28 2025 Leontiy Volodin <lvol@altlinux.org> 6.0.30-alt1
- New version 6.0.30.

* Thu Oct 23 2025 Leontiy Volodin <lvol@altlinux.org> 6.0.29-alt1
- New version 6.0.29.

* Thu Sep 25 2025 Leontiy Volodin <lvol@altlinux.org> 6.0.26-alt1
- New version 6.0.26.

* Thu Aug 21 2025 Leontiy Volodin <lvol@altlinux.org> 6.0.24-alt1
- New version 6.0.24.

* Tue Aug 05 2025 Leontiy Volodin <lvol@altlinux.org> 6.0.22-alt1
- New version 6.0.22.

* Mon Jul 21 2025 Leontiy Volodin <lvol@altlinux.org> 6.0.21-alt1
- New version 6.0.21.

* Tue Jul 15 2025 Leontiy Volodin <lvol@altlinux.org> 6.0.19-alt1
- New version 6.0.19.

* Thu Feb 06 2025 Leontiy Volodin <lvol@altlinux.org> 6.0.16-alt1
- New version 6.0.16.
- Added vcs tag.
- Fixed sound for session startup.

* Fri Sep 06 2024 Leontiy Volodin <lvol@altlinux.org> 6.0.12-alt1
- New version 6.0.12.

* Wed Jul 17 2024 Leontiy Volodin <lvol@altlinux.org> 6.0.11-alt1
- New version 6.0.11.

* Thu Feb 01 2024 Leontiy Volodin <lvol@altlinux.org> 6.0.9-alt1
- New version 6.0.9.

* Mon Nov 27 2023 Leontiy Volodin <lvol@altlinux.org> 6.0.8-alt1
- New version 6.0.8.
- Updated to API v23.
- Cleanup spec.
- Packed golang modules for deepin-api only.

* Tue Oct 31 2023 Ivan A. Melnikov <iv@altlinux.org> 5.5.32-alt3.2
- NMU: Update vendored golang.org/x/sys to build on loongarch64.

* Wed Feb 15 2023 Ivan A. Melnikov <iv@altlinux.org> 5.5.32-alt3.1
- NMU: avoid spourious dependencies generated by shell.req
  from vendored CI scripts.

* Fri Dec 23 2022 Leontiy Volodin <lvol@altlinux.org> 5.5.32-alt3
- Packed github.com/jouyouyun/hardware for startdde.
- Fixed some permission problems for sound effects.

* Tue Dec 13 2022 Leontiy Volodin <lvol@altlinux.org> 5.5.32-alt2
- Updated golang modules.

* Thu Nov 03 2022 Leontiy Volodin <lvol@altlinux.org> 5.5.32-alt1
- New version (5.5.32).
- Upstream:
  + fix: Repair the dde-open analysis part of url cannot get
  the scheme problem.

* Tue Sep 13 2022 Leontiy Volodin <lvol@altlinux.org> 5.5.31-alt1
- New version (5.5.31).
- Packaged new golang modules for deepin-daemon.
- Updated internal golang modules.

* Thu Sep 01 2022 Leontiy Volodin <lvol@altlinux.org> 5.5.30-alt3
- Packaged golang modules for deepin-daemon.

* Tue Aug 30 2022 Leontiy Volodin <lvol@altlinux.org> 5.5.30-alt2
- Updated internal golang modules.

* Wed Aug 24 2022 Leontiy Volodin <lvol@altlinux.org> 5.5.30-alt1
- New version (5.5.30).

* Mon Apr 11 2022 Leontiy Volodin <lvol@altlinux.org> 5.5.12-alt1
- New version (5.5.12).

* Wed Feb 16 2022 Leontiy Volodin <lvol@altlinux.org> 5.5.5-alt1
- New version (5.5.5).

* Wed Feb 02 2022 Leontiy Volodin <lvol@altlinux.org> 5.4.32-alt1
- New version (5.4.32).
- Built with internal golang submodules.

* Tue May 18 2021 Leontiy Volodin <lvol@altlinux.org> 5.4.6-alt1
- New version (5.4.6) with rpmgs script.

* Tue Apr 27 2021 Leontiy Volodin <lvol@altlinux.org> 5.4.5-alt1
- New version (5.4.5) with rpmgs script.

* Thu Mar 04 2021 Leontiy Volodin <lvol@altlinux.org> 5.4.2-alt1
- New version (5.4.2) with rpmgs script.
- Fixed build with golang 1.16.

* Mon Jan 25 2021 Leontiy Volodin <lvol@altlinux.org> 5.3.2-alt1
- New version (5.3.2) with rpmgs script.

* Thu Dec 10 2020 Leontiy Volodin <lvol@altlinux.org> 5.3.0.14-alt1
- New version (5.3.0.14) with rpmgs script.

* Mon Nov 30 2020 Leontiy Volodin <lvol@altlinux.org> 5.3.0.13-alt1
- New version (5.3.0.13) with rpmgs script.

* Thu Nov 19 2020 Leontiy Volodin <lvol@altlinux.org> 5.3.0.12-alt2
- Fixed BuildRequires.

* Mon Oct 12 2020 Leontiy Volodin <lvol@altlinux.org> 5.3.0.12-alt1
- New version (5.3.0.12) with rpmgs script.

* Fri Sep 11 2020 Leontiy Volodin <lvol@altlinux.org> 5.3.0.11-alt1
- Initial build for ALT Sisyphus (thanks fedora for this spec).
