Name: mp3info
Version: 0.8.5a
Release: alt1

Summary: Utility for MP3 information and tag modification
License: GPL
Group: Sound

Url: ftp://ibiblio.org/pub/linux/apps/sound/mp3-utils/mp3info
Source0: %url/mp3info-%version.tar
Source1: mp3info.menu
Source2: mp3info-16.xpm
Source3: mp3info-32.xpm
Source4: mp3info-48.xpm
Source5: mp3info.desktop
Patch1: mp3info-0.8.5a-deb-fixes.patch
Patch2: mp3info-0.8.5a-alt-fixes.patch
Patch3: mp3info-0.8.4-kharpost-fixes.patch
Patch4: mp3info-0.8.5a-alt-gcc44.patch
Packager: Michael Shigorin <mike@altlinux.org>

# Automatically added by buildreq on Fri May 15 2009
BuildRequires: libgtk+2-devel libncurses-devel

Summary(ru_RU.KOI8-R): Утилита для просмотра информации о MP3-файлах и изменения тегов

%package -n g%name
Summary: Utility for MP3 information and tag modification
Group: Sound
Requires: %name = %version-%release

%description
An MP3 technical info viewer and ID3 1.x tag editor
MP3Info has an interactive mode (using curses) and a command line mode.
MP3Info can display ID3 tag information as well as various technical aspects
of an MP3 file including playing time, bit-rate, sampling frequency and other
attributes in a pre-defined or user-specifiable output format.

This package installs ncurses version of mp3info.
If you prefer GTK interface you should use g%name package.

%description -n g%name
An MP3 technical info viewer and ID3 1.x tag editor
MP3Info has an interactive mode (using curses) and a command line mode.
MP3Info can display ID3 tag information as well as various technical aspects
of an MP3 file including playing time, bit-rate, sampling frequency and other
attributes in a pre-defined or user-specifiable output format.

This package installs GTK version of mp3info.
If you prefer command line or curses interface you should use %name package.

%prep
%setup
sed -i 's/$//' *.c
%patch1 -p1
%patch2 -p1
#patch3 -p1
%patch4 -p1

%build
#def_enable Werror
%make_build CFLAGS="%optflags" mp3info gmp3info

%install
make install INSTALL="install -pD" DESTDIR="%buildroot"
install -pDm644 %_sourcedir/mp3info.desktop %buildroot%_desktopdir/%name.desktop
install -pDm644 %_sourcedir/mp3info-16.xpm %buildroot%_miconsdir/%name.xpm
install -pDm644 %_sourcedir/mp3info-32.xpm %buildroot%_niconsdir/%name.xpm
install -pDm644 %_sourcedir/mp3info-48.xpm %buildroot%_liconsdir/%name.xpm
ln -s mp3info.1 "%buildroot%_man1dir/gmp3info"

%files
%_bindir/mp3info
%_man1dir/mp3info.*
%doc README ChangeLog *.lsm

%files -n gmp3info
%_bindir/gmp3info
%_man1dir/gmp3info.*
%_desktopdir/%name.desktop
%_liconsdir/*.xpm
%_niconsdir/*.xpm
%_miconsdir/*.xpm
%doc README ChangeLog *.lsm

%changelog
* Fri May 15 2009 Michael Shigorin <mike@altlinux.org> 0.8.5a-alt1
- 0.8.5a
  + potential buffer overflow fix
  + patch1, patch2 updated
  + patch3 unneeded (fixed upstream)
- fixed build with gcc-4.4
- dropped obsolete macros
- replaced debian menufile with freedesktop one
- me as a Packager:
  + disabled -Werror (due to one type-related warning)

* Sun Dec 14 2008 Dmitry V. Levin <ldv@altlinux.org> 0.8.4-alt10
- Removed obsolete %%update_menus/%%clean_menus calls.

* Fri Apr 11 2008 Dmitry V. Levin <ldv@altlinux.org> 0.8.4-alt9
- Moved %%update_menus/%%clean_menus to proper subpackage (reported by repocop).

* Mon Sep 10 2007 Michael Shigorin <mike@altlinux.org> 0.8.4-alt8
- Fixed broken handling of service frames (#12252);
  thanks Dmitry A. Kharitonov <kharpost rambler ru>
  for both bugreport and patch

* Sun Nov 12 2006 Dmitry V. Levin <ldv@altlinux.org> 0.8.4-alt7
- Fixed build with -D_FORTIFY_SOURCE=2 -Werror.

* Thu May 25 2006 Dmitry V. Levin <ldv@altlinux.org> 0.8.4-alt6
- Deal with compilation warnings generated by new gcc compiler.

* Tue Mar 07 2006 Dmitry V. Levin <ldv@altlinux.org> 0.8.4-alt5
- Fixed build on 64bit architectures.

* Tue Feb 10 2004 Dmitry V. Levin <ldv@altlinux.org> 0.8.4-alt4
- Fixed several potential buffer overflows.

* Thu Dec 11 2003 Dmitry V. Levin <ldv@altlinux.org> 0.8.4-alt3
- Applied fixes from Debian.
- Fixed build dependencies.
- Moved gtk interface version (g%name) to separate subpackage.

* Sat Oct 05 2002 Rider <rider@altlinux.ru> 0.8.4-alt2
- rebuild

* Sat Jan 05 2002 Rider <rider@altlinux.ru> 0.8.4-alt1
- 0.8.4
- added to menu

* Sat Mar 17 2001 Dmitry V. Levin <ldv@altlinux.ru> 0.2.16-ipl6mdk
- Fixed build with glibc-2.2.2.

* Sun Jan 14 2001 AEN <aen@logic.ru>
- RE adaptation

* Wed Nov 08 2000 Thierry Vignaud <tvignaud@mandrakesoft.com> 0.2.16-4mdk
- capitalize summary

* Tue Aug 01 2000 Thierry Vignaud <tvignaud@mandrakesoft.com> 0.2.16-3mdk
- BM

* Tue May 02 2000 Lenny Cartier <lenny@mandrakesoft.com> 0.2.16-2mdk
- fix group
- fix files section

* Tue Nov 30 1999 Lenny Cartier <lenny@mandrakesoft.com>
- new in contribs
- bz archive, man pages

* Fri Mar 19 1999 Thorvald Natvig <thorvald@natvig.com>
- Initial release as RPM
