Summary: X Render Extension Test Tool
Name: rendercheck
Version: 1.4
Release: alt1
License: BSD
Group: System/X11
Source: %name-%version.tar.bz2
Url: http://cgit.freedesktop.org/xorg/app/rendercheck

BuildRequires: xorg-util-macros

# Automatically added by buildreq on Wed Apr 28 2010
BuildRequires: libXrender-devel

%description
rendercheck is a program to test a Render extension implementation
against separate calculations of expected output.

Tests currently include:
 - Destination coordinates correctness
 - Source coordinates correctness
 - Transformed (FilterNearest) source coordinates correctness.
 - Composite with and without mask (with/without component alpha), with 1x1
   repeating Pictures and 10x10 Pictures.

Unfortunately, there are currently no command-line arguments to
control its execution.  Options, such as verbosity or number of
iterations to encourage pixmap migration, are controlled only in
source.

%prep
%setup -q

%build
./autogen.sh
%configure
%make

%install
%make install DESTDIR=%buildroot

%files
%doc README INSTALL COPYING doc/* AUTHORS NEWS
%_bindir/%name
%_man1dir/*

%changelog
* Fri Jan 14 2011 Fr. Br. George <george@altlinux.ru> 1.4-alt1
- Autobuild version bump to 1.4

* Wed Apr 28 2010 Fr. Br. George <george@altlinux.ru> 1.3-alt1
- Version up

* Sun Oct 01 2006 Fr. Br. George <george@altlinux.ru> 1.0.3-alt1
- Initial build from CAOS

* Tue Dec 07 2004 Mezzanine <mezzanine@kainx.org>
- Specfile auto-generated by Mezzanine

