%define hsc_name ghc
%define hsc_version %ghc_version
%define hsc_namever %hsc_name
%define h_pkg_name mtl
%define f_pkg_name mtl
%define pkg_libdir %_libdir/%hsc_name-%hsc_version/lib/%h_pkg_name-%version

Name: %hsc_namever-%f_pkg_name
Version: 2.0.1.0
Release: alt2.1
License: BSD
Group: Development/Haskell
Source: %f_pkg_name-%version.tar
Summary: Monad transformer library
BuildRequires: ghc ghc-transformers
BuildRequires(pre): rpm-build-haskell


%description
A monad transformer library, inspired by the paper /Functional
Programming with Overloading and Higher-Order Polymorphism/,
by Mark P Jones (<http://web.cecs.pdx.edu/~mpj/pubs/springschool.html>),
Advanced School of Functional Programming, 1995.


%prep
%setup -n %h_pkg_name-%version


%build
%hs_configure2
%hs_build

%install
%hs_install
%hs_gen_filelist

cd %buildroot%_datadir/doc/%hsc_namever-%f_pkg_name-%version
rm -rf doc LICENSE

%files -f %name-files.nonprof
%hs_pkgconfdir/%f_pkg_name-%version.conf
%doc dist/doc/html
%doc LICENSE

%changelog
* Sat Aug 13 2011 Denis Smirnov <mithraen@altlinux.ru> 2.0.1.0-alt2.1
- rebuild with shared objects support

* Tue Aug 09 2011 Denis Smirnov <mithraen@altlinux.ru> 2.0.1.0-alt2
- rebuild

* Wed Dec 08 2010 Denis Smirnov <mithraen@altlinux.ru> 2.0.1.0-alt1
- 2.0.1.0

* Mon Sep 13 2010 Denis Smirnov <mithraen@altlinux.ru> 1.1.0.2-alt6
- auto rebuild

* Mon Sep 13 2010 Denis Smirnov <mithraen@altlinux.ru> 1.1.0.2-alt5
- auto rebuild

* Thu Sep 09 2010 Denis Smirnov <mithraen@altlinux.ru> 1.1.0.2-alt2
- ghc 6.12.3

* Thu Sep 09 2010 Denis Smirnov <mithraen@altlinux.ru> 1.1.0.2-alt1.1.1
- rebuild with new haskell

* Wed Mar 17 2010 Denis Smirnov <mithraen@altlinux.ru> 1.1.0.2-alt1.1
- rebuild with new haskell

* Tue Nov 13 2008 Alexander Myltsev <avm@altlinux.ru> 1.1.0.2-alt1
- New version.

* Mon Jan 14 2008 Alex V. Myltsev <avm@altlinux.ru> 1.1.0.0-alt2
- Use package.conf.d.

* Wed Jan 09 2008 Alex V. Myltsev <avm@altlinux.ru> 1.1.0.0-alt1
- spec file autogenerated by cabal-rpm
