# Original package name Copas
%define oname copas
%define oversion 2.0.2-1
%define rockspec %oname-%oversion.rockspec
Name: lua-module-%oname
Version: 2.0.2
Release: alt1
Summary: Coroutine Oriented Portable Asynchronous Services
License: MIT/X11
Group: Development/Other
Url: http://www.keplerproject.org/copas/
Provides: luarocks(%oname) = %version

BuildArch: noarch

Source: %oname.tar.gz

BuildPreReq: rpm-macros-lua >= 1.2
# Automatically added by buildreq on ...
BuildRequires: liblua5-devel luarocks
BuildRequires: luarocks(luasocket) >= 2.1, luarocks(coxpcall) >= 1.14
Requires: luarocks(luasocket) >= 2.1, luarocks(coxpcall) >= 1.14

%description
      Copas is a dispatcher based on coroutines that can be used by
      TCP/IP servers. It uses LuaSocket as the interface with the
      TCP/IP stack. A server registered with Copas should provide a
      handler for requests and use Copas socket functions to send
      the response. Copas loops through requests and invokes the
      corresponding handlers. For a full implementation of a Copas
      HTTP server you can refer to Xavante as an example.

%prep
%setup -n %oname

%install
%luarocks_make rockspec/%rockspec
%luarocks_move_docs doc

%check
#TODO
exit 0
%lua_path_add_buildroot
for t in %buildroot%luarocks_dbdir/%oname/%oversion/tests/* ; do
  lua $t
done

%files
%lua_modulesdir_noarch/*
%luarocks_dbdir/%oname
%doc README* docs_from_rockstree/*
%exclude %luarocks_dbdir/manifest

%changelog
* Thu Jul 13 2017 Aleksei Nikiforov <darktemplar@altlinux.org> 2.0.2-alt1
- Upgraded to upstream version 2.0.2-1
- Rebuild with new luarocks and lua-5.3

* Wed Oct 15 2014 Ildar Mulyukov <ildar@altlinux.ru> 1.2.1-alt1_lr1
- autogenerated by lrimport

* Sun Jan 09 2011 Ildar Mulyukov <ildar@altlinux.ru> 1.1.6-alt1_lr1
- autogenerated by lrimport
