# vim: set ft=spec: -*- rpm-spec -*-
#   - MP3::Tag -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       MP3::Tag
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module MP3-Tag
%define m_distro MP3-Tag
%define m_name MP3::Tag
%define m_author_id unknown
%def_enable test

Name: perl-MP3-Tag
Version: 0.9710
Release: alt1.1

Summary: Module for reading tags of MP3 audio files

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Sir Raorn <raorn@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/I/IL/ILYAZ/modules/%m_distro-%version.tar
Patch: %m_distro-%version-%release.patch

# Automatically added by buildreq on Thu Jan 04 2007
BuildRequires: perl-devel

%description
Tag is a wrapper module to read different tags of mp3 files.  It
provides an easy way to access the functions of seperate modules
which do the handling of reading/writing the tags itself.

At the moment MP3::Tag::ID3v1 and MP3::Tag::ID3v2 are supported for
read and write; MP3::Tag::Inf, MP3::Tag::CDDB_File, MP3::Tag::File,
MP3::Tag::LastResort are supported for read access (the information
obtained by parsing CDDB files, .inf file and the filename).

%prep
%setup -q -n %m_distro-%version
%patch -p1

%build
%perl_vendor_build -n

%install
%perl_vendor_install

%files
%perl_vendor_privlib/MP3*

%changelog
* Mon Nov 29 2010 Igor Vlasenko <viy@altlinux.ru> 0.9710-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Sun Apr 27 2008 Sir Raorn <raorn@altlinux.ru> 0.9710-alt1
- [0.9710]
- Dropped useless utils with unmets

* Thu Jan 04 2007 Sir Raorn <raorn@altlinux.ru> 0.9709-alt1
- first build for ALT Linux Sisyphus

