%define _unpackaged_files_terminate_build 1
%define sover 3
%define libsuffix %sover-openssl

Name: libcoap%sover
Version: 4.3.5
Release: alt1

Summary: Shared library of libcoap (CoAP, RFC 7252)
Summary(ru_RU.UTF-8): Разделяемая библиотека libcoap (CoAP, RFC 7252)
License: BSD-2-Clause and BSD-3-Clause and BSD-1-Clause
Group: System/Libraries
Url: https://libcoap.net
VCS: https://github.com/obgm/libcoap

Source: %name-%version.tar

BuildRequires: pkgconfig(openssl)
BuildRequires: CUnit-devel
BuildRequires: doxygen
BuildRequires: graphviz
BuildRequires: asciidoc-a2x

%description
libcoap is a C implementation of the Constrained Application
Protocol (CoAP), as defined in RFC 7252, together with a number
of follow-up RFCs (Observe, Block-wise transfer, OSCORE, etc).

Shared library implementing the Constrained Application Protocol
(CoAP, RFC 7252) with OpenSSL as the (D)TLS backend.

%description -l ru_RU.UTF-8
libcoap — реализация на языке C протокола CoAP (RFC 7252) для
устройств с ограниченными ресурсами, с поддержкой Observe,
блочных передач и OSCORE.

Разделяемая библиотека с реализацией протокола CoAP (RFC 7252),
в качестве (D)TLS-бэкенда используется OpenSSL.

%package devel
Summary: Development files for libcoap
Summary(ru_RU.UTF-8): Файлы разработки для libcoap
Group: Development/C
Requires: %name = %EVR

%description devel
Development headers and pkg-config file for libcoap.

%description devel -l ru_RU.UTF-8
Заголовочные файлы и pkg-config файл для libcoap.

%package doc
Summary: Documentation for libcoap
Summary(ru_RU.UTF-8): Документация для libcoap
Group: Documentation
BuildArch: noarch

%description doc
API documentation generated by doxygen, manual pages, together
with the README and license files of libcoap.

%description doc -l ru_RU.UTF-8
Документация по API, собранная doxygen, страницы руководства,
а также файлы README и лицензии libcoap.

%package utils
Summary: Command line CoAP client, server and resource directory
Summary(ru_RU.UTF-8): Консольные CoAP-клиент, сервер и resource directory
Group: Networking/Other

%description utils
Command line CoAP client, CoAP server and CoAP resource directory
built on top of libcoap.

%description utils -l ru_RU.UTF-8
Консольные CoAP-клиент, CoAP-сервер и CoAP resource directory,
построенные на основе libcoap.

%prep
%setup

%build
./autogen.sh
%configure \
    --with-openssl \
    --enable-shared \
    --disable-static \
    --enable-tests \
    --enable-examples \
    --enable-documentation \
    --disable-add-default-names
%make_build

%install
%makeinstall_std
rm -f %buildroot%_libdir/*.a %buildroot%_libdir/*.la

%check
tests/testdriver

%files
%_libdir/libcoap-%libsuffix.so.%sover
%_libdir/libcoap-%libsuffix.so.%sover.*

%files devel
%dir %_includedir/coap%sover
%_includedir/coap%sover/*
%_libdir/libcoap-%libsuffix.so
%_pkgconfigdir/libcoap-%libsuffix.pc

%files doc
%_docdir/*
%_man3dir/*
%_man5dir/*
%_man7dir/*

%files utils
%_bindir/coap-*
%dir %_datadir/libcoap
%_datadir/libcoap/*

%changelog
* Wed Sep 16 2026 Dina Tagantseva <dinchik@altlinux.org> 4.3.5-alt1
- Initial build for Sisyphus.

