#
#   - AutoXS::Header -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       -debug AutoXS::Header
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module AutoXS-Header
%define m_distro AutoXS-Header
%define m_name AutoXS::Header
%define m_author_id unknown
%define _enable_test 1

Name: perl-AutoXS-Header
Version: 1.02
Release: alt1

Summary: Container for the AutoXS header files

License: Artistic
Group: Development/Perl
Url: %CPAN %m_distro

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/S/SM/SMUELLER/%m_distro-%version.tar.gz

# Automatically added by buildreq on Mon Oct 19 2009 (-bi)
BuildRequires: perl-devel

%description
This module is a simple container for the newest version of the
AutoXS header file "AutoXS.h".

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%perl_vendor_privlib/AutoXS/*

%changelog
* Mon Oct 19 2009 Michael Bochkaryov <misha@altlinux.ru> 1.02-alt1
- initial build for ALT Linux Sisyphus

