#
#   - Net::Nessus -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --version=0.09 Net-Nessus-0.09.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Net-Nessus
%define m_distro Net-Nessus
%define m_name Net::Nessus
%define m_author_id unknown
%define _enable_test 1

Name: perl-Net-Nessus
Version: 0.09
Release: alt2.1

Summary: Net-Nessus - Perl module

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Slava Dubrovskiy <dubrsl@altlinux.org>

BuildArch: noarch
Source: %m_distro-%version.tar.gz
Source1: %m_distro-%version-status

# Automatically added by buildreq on Sun Apr 29 2007
BuildRequires: perl-devel perl-Net-Telnet perl-Term-ReadKey

# automatically added during perl 5.8 -> 5.12 upgrade.
# perl-podlators is required for pod2man conversion.
BuildRequires: perl-podlators

%description
None.

%prep
%setup -q -n %m_distro-%version
%__cp -aRf %SOURCE1 .status

%build
%perl_vendor_build INSTALLMAN1DIR=%_man1dir

%install
%perl_vendor_install

%files
%_bindir/*
%perl_vendor_privlib/Bundle
%perl_vendor_privlib/Net
%_man1dir/*

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.09-alt2.1
- repair after perl 5.12 upgrade using girar-nmu

* Thu Sep 11 2008 Slava Dubrovskiy <dubrsl@altlinux.org> 0.09-alt2
- Fix build

* Sun Apr 29 2007 Slava Dubrovskiy <dubrsl@altlinux.org> 0.09-alt1
- first build for ALT Linux Sisyphus

