#
#   - Algorithm-Annotate -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Algorithm::Annotate
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Algorithm-Annotate
%define m_distro Algorithm-Annotate
%define m_name Algorithm-Annotate
%define m_author_id CLKAO
%define _enable_test 1

Name: perl-Algorithm-Annotate
Version: 0.10
Release: alt2.1

Summary: Represent a series of changes in annotation list

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org/CPAN/authors/id/C/CL/%m_author_id/%m_distro-%version.tar.bz2
#Source: http://www.cpan.org/modules/by-module/Algorithm/%m_distro-%version.tar.bz2

# Automatically added by buildreq on Tue Feb 21 2006
BuildRequires: perl-Algorithm-Diff perl-devel

%description
Algorithm::Annotate generates a list that is useful for generating
output simliar to "cvs annotate".

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Algorithm/

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.10-alt2.1
- repair after perl 5.12 upgrade using girar-nmu

* Thu Sep 04 2008 Vitaly Lipatov <lav@altlinux.ru> 0.10-alt2
- fix directory ownership violation

* Tue Feb 21 2006 Vitaly Lipatov <lav@altlinux.ru> 0.10-alt1
- initial build for ALT Linux Sisyphus

