%define target_lua_version 5.4

# Original package name lusc_luv
%define oname lusc_luv
%define oversion 4.0.1-1
%define rockspec lusc_luv-4.0.1-1.rockspec
Name: lua%target_lua_version-module-%oname
Version: 4.0.1
Release: alt1_lr1
Summary: Structured Async/Concurrency for Lua using Luv
License: MIT
Group: Development/Other
Url: https://github.com/svermeulen/lusc_luv

Source: https://github.com/svermeulen/lusc_luv/archive/refs/heads/main.tar.gz#/%oname-main.tar.gz
Source1: https://luarocks.org/manifests/svermeulen/lusc_luv-4.0.1-1.rockspec

BuildArch: noarch
BuildPreReq: rpm-macros-lua >= 1.5.2 rpm-build-lua
BuildRequires: lua%target_lua_version-luarocks
# lua5.3-luarocks lua5.1-luarocks
BuildRequires: luarocks%target_lua_version(luv)

%description
Structured Async/Concurrency for Lua using Luv

%if 0
%package -n lua5.3-module-%oname
Summary: Structured Async/Concurrency for Lua using Luv
Group: Development/Other
%description -n lua5.3-module-%oname
Structured Async/Concurrency for Lua using Luv
%package -n lua5.1-module-%oname
Summary: Structured Async/Concurrency for Lua using Luv
Group: Development/Other
%description -n lua5.1-module-%oname
Structured Async/Concurrency for Lua using Luv
%endif

%prep
%setup -n %oname-main

%install
%luarocks_make %SOURCE1
%luarocks_move_docs doc

%add_findreq_skiplist %luarocks_dbdir_prefix-*/%oname/*/{doc,docs,etc,examples,samples,spec,test}/*

%files
%lua54_modulesdir_noarch/*
%luarocks_dbdir_prefix-%target_lua_version/%oname
%doc dist example docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-%target_lua_version/manifest

%if 0
%files -n lua5.3-module-%oname
%lua53_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.3/%oname
%doc dist example docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.3/manifest

%files -n lua5.1-module-%oname
%lua51_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.1/%oname
%doc dist example docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.1/manifest
%endif

%changelog
* Tue Apr 29 2025 Ildar Mulyukov <ildar@altlinux.ru> 4.0.1-alt1_lr1
- autogenerated by lrimport