#
#   - XML::Compile::Tester -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       XML::Compile::Tester
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module XML-Compile-Tester
%define m_distro XML-Compile-Tester
%define m_name XML::Compile::Tester
%define m_author_id MARKOV
%define _enable_test 1

Name: perl-XML-Compile-Tester
Version: 0.06
Release: alt1

Summary: support XML::Compile related regression testing

License: Artistic
Group: Development/Perl
Url: %CPAN %m_distro

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/M/MA/MARKOV/XML-Compile-Tester-0.06.tar.gz

# Automatically added by buildreq on Sat Jan 10 2009
BuildRequires: perl-Log-Report perl-Test-Deep perl-Test-Pod

%description
The XML::Compile module suite has extensive regression testing. Probably,
you want to do regression testing as well. This module provide functions
which simplify writing tests for XML::Compile related distributions.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%perl_vendor_privlib/XML/*

%changelog
* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 0.06-alt1
- automated CPAN update

* Sat Jan 10 2009 Vitaly Lipatov <lav@altlinux.ru> 0.04-alt1
- initial build for ALT Linux Sisyphus

