Name: autoconf-archive
Version: 2012.04.07
Release: alt1
Summary: The Autoconf Macro Archive

Group: Development/Other
License: GPLv3+ with exceptions
URL: http://www.gnu.org/software/autoconf-archive/
Source: ftp://ftp.gnu.org/gnu/autoconf-archive/%name-%version.tar.xz
BuildArch: noarch

%description
The GNU Autoconf Archive is a collection of more than 450 macros for
GNU Autoconf that have been contributed as free software by friendly
supporters of the cause from all over the Internet.

%prep
%setup -q

%build
%configure
%make_build

%install
%makeinstall

# remove dir file which will be generated by /sbin/install-info
rm -f %buildroot%_infodir/dir
# document files are installed another location
rm -rf %buildroot%_datadir/%name

%files
%doc AUTHORS COPYING* ChangeLog NEWS README TODO
%_datadir/aclocal/*.m4
%_infodir/autoconf-archive.info*

%changelog
* Mon Sep 03 2012 Alexey Shabalin <shaba@altlinux.ru> 2012.04.07-alt1
- initial build
