%define target_lua_version 5.4

# Original package name luarocks-build-treesitter-parser
%define oname luarocks-build-treesitter-parser
%define oversion 6.0.2-1
%define rockspec luarocks-build-treesitter-parser-6.0.2-1.rockspec
Name: lua%target_lua_version-module-%oname
Version: 6.0.2
Release: alt1_lr1
Summary: A luarocks build backend for tree-sitter parsers.
License: MIT
Group: Development/Other
Url: https://github.com/lumen-oss/luarocks-build-treesitter-parser

Source: https://github.com/lumen-oss/luarocks-build-treesitter-parser/archive/refs/tags/v6.0.2.zip#/%oname-%version.zip
Source1: https://luarocks.org/manifests/neorocks/luarocks-build-treesitter-parser-6.0.2-1.rockspec

BuildArch: noarch
BuildPreReq: rpm-macros-lua >= 1.5.2 rpm-build-lua
BuildRequires: lua%target_lua_version-luarocks lua5.3-luarocks lua5.1-luarocks
BuildRequires: luarocks%target_lua_version(luafilesystem) luarocks5.1(luafilesystem) luarocks5.3(luafilesystem)

Requires: /usr/bin/tree-sitter luarocks%target_lua_version(luafilesystem)
%description
Warning: This is early WIP!
A luarocks build backend for tree-sitter parsers.
Used by the Neovim User Rock Repository (NURR).
The resulting parser libraries are installed to
<luarocks-install-tree>/lib/lua/<lua-version>/parser.

%package -n lua5.3-module-%oname
Summary: A luarocks build backend for tree-sitter parsers.
Group: Development/Other
Requires: /usr/bin/tree-sitter luarocks5.3(luafilesystem)
%description -n lua5.3-module-%oname
Warning: This is early WIP!
A luarocks build backend for tree-sitter parsers.
Used by the Neovim User Rock Repository (NURR).
The resulting parser libraries are installed to
<luarocks-install-tree>/lib/lua/<lua-version>/parser.

%package -n lua5.1-module-%oname
Summary: A luarocks build backend for tree-sitter parsers.
Group: Development/Other
Requires: /usr/bin/tree-sitter luarocks5.1(luafilesystem)
%description -n lua5.1-module-%oname
Warning: This is early WIP!
A luarocks build backend for tree-sitter parsers.
Used by the Neovim User Rock Repository (NURR).
The resulting parser libraries are installed to
<luarocks-install-tree>/lib/lua/<lua-version>/parser.

%prep
%setup -n %oname-%version

%install
%luarocks_make %SOURCE1
%luarocks_move_docs doc

%add_findreq_skiplist %luarocks_dbdir_prefix-*/%oname/*/{doc,docs,etc,examples,samples,spec,test}/*

%files
%lua54_modulesdir_noarch/*
%luarocks_dbdir_prefix-%target_lua_version/%oname
%doc docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-%target_lua_version/manifest

%files -n lua5.3-module-%oname
%lua53_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.3/%oname
%doc docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.3/manifest

%files -n lua5.1-module-%oname
%lua51_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.1/%oname
%doc docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.1/manifest

%changelog
* Wed May 27 2026 Ildar Mulyukov <ildar@altlinux.ru> 6.0.2-alt1_lr1
- new version

* Sun Apr 27 2025 Ildar Mulyukov <ildar@altlinux.ru> 6.0.0-alt1_lr1
- autogenerated by lrimport
