%define oname mysql-replication

Name: python3-module-%oname
Version: 0.31
Release: alt1

Summary: Pure Python Implementation of MySQL replication protocol build on top of PyMYSQL

License: MIT
Group: Development/Python3
Url: https://pypi.org/project/mysql-replication/
Packager: Python Development Team <python@packages.altlinux.org>

# Source-url: %__pypi_url %oname
Source: %name-%version.tar

BuildArch: noarch

BuildRequires(pre): rpm-build-intro
BuildRequires(pre): rpm-build-python3

# generated by epm restore --dry-run from mysql-replication/setup.py install_requires
%py3_use pymysql >= 0.6

%description
Pure Python Implementation of MySQL replication protocol build on top of PyMYSQL.
This allow you to receive event like insert, update, delete with their datas and raw SQL queries.

%prep
%setup

%build
%python3_build

%install
%python3_install
%python3_prune

%check
#python3 setup.py test

%files
%doc README.md
%python3_sitelibdir/*

%changelog
* Mon Mar 13 2023 Grigory Ustinov <grenka@altlinux.org> 0.31-alt1
- Automatically updated to 0.31.

* Thu May 26 2022 Grigory Ustinov <grenka@altlinux.org> 0.30-alt1
- Build new version.

* Sun Jan 24 2021 Vitaly Lipatov <lav@altlinux.ru> 0.22-alt1
- initial build for ALT Sisyphus
