%define _unpackaged_files_terminate_build 1
%def_with check
%define target_lua_version 5.3

# Original package name LuaSocket
%define oname luasocket
%define oversion 3.1.0-1
%define rockspec luasocket/rockspecs/luasocket-3.1.0-1.rockspec
Name: lua%target_lua_version-module-%oname
Version: 3.1.0
Release: alt3_lr1
Epoch: 1
Summary: Network support for the Lua language
License: MIT
Group: Development/Other
Url: https://github.com/lunarmodules/luasocket

%if "%target_lua_version" == "5.1"
Obsoletes: lua-module-%oname < %EVR
Provides: lua-module-%oname = %EVR
%endif
%if "%target_lua_version" == "5.4"
Obsoletes: liblua%target_lua_version-module-%oname < %EVR
%endif
# self-dependencies
%filter_from_requires /lua%target_lua_version.dispatch/d
%filter_from_requires /lua%target_lua_version.socket\./d
%filter_from_requires /lua%target_lua_version.ssl\./d

Source: https://github.com/lunarmodules/luasocket/archive/refs/tags/v3.1.0.tar.gz#/%oname-%version.tar.gz

BuildPreReq: rpm-macros-lua >= 1.5.2 rpm-build-lua
BuildRequires: liblua%target_lua_version-devel lua%target_lua_version-luarocks

%description
      LuaSocket is a Lua extension library composed of two parts: a set of C
      modules that provide support for the TCP and UDP transport layers, and a
      set of Lua modules that provide functions commonly needed by applications
      that deal with the Internet.

%prep
%setup -n %oname-%version

%install
%luarocks_make rockspecs/%oname-%oversion.rockspec
%luarocks_move_docs docs

%check
subst 's|bin/lua$|bin/lua%current_lua_version|' test/udp-zero-length-send*
%lua_path_add_buildroot
( %lua test/testsrvr.lua ||: )&
sleep 1
%lua test/testclnt.lua
%lua test/hello.lua

%add_findreq_skiplist %luarocks_dbdir_prefix-*/%oname/*/{doc,docs,etc,examples,samples,spec,test}/*

%files
%lua_modulesdir/*
%lua_modulesdir_noarch/*
%luarocks_dbdir_prefix-%target_lua_version/%oname
%doc CHANGELOG.* FIX* LICENSE* README.* TODO* WISH* docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-%target_lua_version/manifest

%changelog
* Sat Dec 27 2025 Ildar Mulyukov <ildar@altlinux.ru> 1:3.1.0-alt3_lr1
- autogenerated by lrimport
- remove the patch that already in upstream
- remove "shared libraries" part (irrelevant for Lua modules)

* Tue Apr 01 2025 Sergey Zhidkih <rx1513@altlinux.org> 1:3.1.0-alt2_lr1
- Change build system from make to luarocks.
- Repackage according to shared library policy.
- Refactor spec.

* Tue Aug 22 2023 Ildar Mulyukov <ildar@altlinux.ru> 3.0rc1-alt5_lr2
- fix build with newer autodep system

* Sat Oct 08 2022 Vladimir D. Seleznev <vseleznv@altlinux.org> 1:3.1.0-alt1
- Updated to 3.1.0.

* Sun Jul 03 2022 Vladimir D. Seleznev <vseleznv@altlinux.org> 1:3.0.0-alt1
- Updated to 3.0.0.
- Added devel subpackage.

* Tue Nov 12 2019 Ildar Mulyukov <ildar@altlinux.ru> 3.0rc1-alt4_lr2
- fix excessive dep on /usr/bin/lua

* Fri Jun 07 2019 Ildar Mulyukov <ildar@altlinux.ru> 3.0rc1-alt3_lr2
- autogenerated by lrimport
- restuctured according to https://www.altlinux.org/Lua_Policy

* Thu Jul 13 2017 Aleksei Nikiforov <darktemplar@altlinux.org> 3.0rc1-alt2
- Rebuild with new luarocks and lua-5.3

* Tue Oct 07 2014 Ildar Mulyukov <ildar@altlinux.ru> 3.0rc1-alt1_lr1
- autogenerated by lrimport

* Thu Jan 06 2011 Ildar Mulyukov <ildar@altlinux.ru> 2.0.2-alt1_lr3
- autogenerated by lrimport
