#
#   - Scope::Guard -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Scope::Guard
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Scope-Guard
%define m_distro Scope-Guard
%define m_name Scope::Guard
%define m_author_id CHOCOLATE
%define _enable_test 1

Name: perl-Scope-Guard
Version: 0.20
Release: alt1.1

Summary: lexically scoped resource management

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/Scope-Guard/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/C/CH/CHOCOLATE/Scope-Guard-0.20.tar.gz

# Automatically added by buildreq on Tue Sep 23 2008 (-bi)
BuildRequires: perl-Test-Pod perl-Test-Pod-Coverage

%description
This module provides a convenient way to perform cleanup or other forms of resource
management at the end of a scope. It is particularly useful when dealing with exceptions:
the Scope::Guard constructor takes a reference to a subroutine that is guaranteed to
be called even if the thread of execution is aborted prematurely. This effectively allows
lexically-scoped "promises" to be made that are automatically honoured by perl's garbage
collector.

For more information, see: <http://www.cuj.com/documents/s=8000/cujcexp1812alexandr/>

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Scope*
%doc Changes README

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.20-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 0.20-alt1
- automated CPAN update

* Tue Sep 23 2008 Michael Bochkaryov <misha@altlinux.ru> 0.03-alt2
- fix directory ownership violation

* Mon May 26 2008 Michael Bochkaryov <misha@altlinux.ru> 0.03-alt1
- first build for ALT Linux Sisyphus

