%define _unpackaged_files_terminate_build 1
#
#   - Data::Compare -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Data::Compare
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Data-Compare
%define m_distro Data-Compare
%define m_name Data::Compare
%define m_author_id DCANTRELL
%define _enable_test 1

Name: perl-Data-Compare
Version: 1.28
Release: alt1

Summary: compare perl data structures

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/Data-Compare/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source0: http://www.cpan.org/authors/id/D/DC/DCANTRELL/%{module}-%{version}.tar.gz

# Automatically added by buildreq on Mon Jan 05 2009
BuildRequires: perl-Clone perl-File-Find-Rule perl-JSON perl-Test-Pod

%description
Compare two perl data structures recursively. Returns 0 if the
structures differ, else returns 1.

A few data types are treated as special cases:


%prep
%setup -q -n %{module}-%{version}
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc GPL2.txt ARTISTIC.txt README CHANGELOG
%perl_vendor_privlib/*
%exclude %perl_vendor_archlib
%doc README CHANGELOG NOTES

%changelog
* Thu Mar 16 2023 Igor Vlasenko <viy@altlinux.org> 1.28-alt1
- automated CPAN update

* Thu Nov 07 2019 Igor Vlasenko <viy@altlinux.ru> 1.27-alt1
- automated CPAN update

* Tue Sep 24 2019 Igor Vlasenko <viy@altlinux.ru> 1.26-alt1
- automated CPAN update

* Tue Dec 16 2014 Igor Vlasenko <viy@altlinux.ru> 1.25-alt1
- automated CPAN update

* Wed Apr 09 2014 Igor Vlasenko <viy@altlinux.ru> 1.24-alt1
- automated CPAN update

* Sat Sep 28 2013 Igor Vlasenko <viy@altlinux.ru> 1.23-alt1
- automated CPAN update

* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 1.22-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 1.22-alt1
- automated CPAN update

* Mon Jan 05 2009 Michael Bochkaryov <misha@altlinux.ru> 1.21-alt1
- 1.21 version build
- documentation added to package

* Mon Oct 06 2008 Igor Vlasenko <viy@altlinux.ru> 1.19-alt1.1
- NMU for unknown reason:
  the person above was too neglectant to add --changelog "- NMU: <reason>" option.

* Wed Jun 18 2008 Michael Bochkaryov <misha@altlinux.ru> 1.19-alt1
- first build for ALT Linux Sisyphus

