Name: arp-scan
Version: 1.8.1
Release: alt1

Summary: Scanning and fingerprinting tool
License: GPLv3+
Group: Monitoring

Url: http://www.nta-monitor.com/tools/arp-scan
Source: %url/download/%name-%version.tar.gz
# Files generated by get-iab and get-oui as replacements of older files
# shipped with arp-scan:
Source1: ieee-iab.txt
Source2: ieee-oui.txt

# Automatically added by buildreq on Wed Dec 28 2011 (-bi)
BuildRequires: libpcap-devel perl-libwww

%description
arp-scan is a command-line tool that uses the ARP protocol to discover
and fingerprint IP hosts on the local network.

%prep
%setup

%build
cp -a %_sourcedir/{ieee-iab.txt,ieee-oui.txt} .
%configure
%make_build

%install
%makeinstall_std

%files
%_bindir/*
%_datadir/arp-scan
%_man1dir/*
%_man5dir/*

%changelog
* Wed Dec 28 2011 Victor Forsiuk <force@altlinux.org> 1.8.1-alt1
- Initial build.
