#
#   - MouseX-App-Cmd -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   (ALT Linux revision)
#   The following arguments were used:
#       '--packager=Igor Vlasenko <viy@altlinux.ru>' --url http://search.cpan.org/CPAN/authors/id/M/MJ/MJGARDNER/MouseX-App-Cmd-0.11.tar.gz --no-depchk MouseX-App-Cmd-0.11.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module MouseX-App-Cmd
%define m_distro MouseX-App-Cmd
%define m_name MouseX-App-Cmd
%define m_author_id unknown
%define _disable_test 1

Name: perl-MouseX-App-Cmd
Version: 0.11
Release: alt1

Summary: Mashes up L<MouseX::Getopt|MouseX::Getopt> and L<App::Cmd|App::Cmd>

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/CPAN/authors/id/M/MJ/MJGARDNER/MouseX-App-Cmd-0.11.tar.gz

Packager: Igor Vlasenko <viy@altlinux.ru>

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Thu Oct 18 2012
BuildRequires: perl-YAML perl-devel perl(Mouse.pm) perl(Getopt/Long/Descriptive.pm)

%description
None.

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/MouseX/*

%changelog
* Thu Oct 18 2012 Igor Vlasenko <viy@altlinux.ru> 0.11-alt1
- initial build for ALT Linux Sisyphus

