Name: mojo-signatures
Version: 1.1
Summary: Mojo API signatures project
License: MIT
Url: http://mojo.codehaus.org/
Packager: Igor Vlasenko <viy@altlinux.ru>
Requires: /bin/sh
Requires: /bin/sh
Requires: jpackage-utils
Requires: jpackage-utils
Requires: jpackage-utils
Requires: maven
Requires: mojo-parent

BuildArch: noarch
Group: Development/Java
Release: alt0.1jpp
Source: mojo-signatures-1.1-0.6.svn11457.fc17.cpio

%description
The API Signatures project contains a number of projects which
generate signatures of various APIs, such as the Java Runtime. These
signatures are generated by and consumed by the Animal Sniffer
project.

# sometimes commpress gets crazy (see maven-scm-javadoc for details)
%set_compress_method none
%prep
cpio -idmu --quiet --no-absolute-filenames < %{SOURCE0}

%build
cpio --list < %{SOURCE0} | sed -e 's,^\.,,' > %name-list

%install
mkdir -p $RPM_BUILD_ROOT
for i in usr var etc; do
[ -d $i ] && mv $i $RPM_BUILD_ROOT/
done

%post

echo -e "<dependencies>\n" > /etc/maven/maven2-depmap.xml
if [ -d /usr/share/maven-fragments ] && [ -n "`find /usr/share/maven-fragments -type f`" ]; then
cat /usr/share/maven-fragments/* >> /etc/maven/maven2-depmap.xml
fi
echo -e "</dependencies>\n" >> /etc/maven/maven2-depmap.xml

%postun

echo -e "<dependencies>\n" > /etc/maven/maven2-depmap.xml
if [ -d /usr/share/maven-fragments ] && [ -n "`find /usr/share/maven-fragments -type f`" ]; then
cat /usr/share/maven-fragments/* >> /etc/maven/maven2-depmap.xml
fi
echo -e "</dependencies>\n" >> /etc/maven/maven2-depmap.xml


%files -f %name-list

%changelog
* Sun Mar 11 2012 Igor Vlasenko <viy@altlinux.ru> 1.1-alt0.1jpp
- bootstrap pack of jars created with jppbootstrap script
- temporary package to satisfy circular dependencies

