%define ghc_version 8.6.4
%define hsc_name ghc
%define hsc_version %ghc_version
%define hsc_namever %hsc_name%hsc_version
%define h_pkg_name tagsoup
%define f_pkg_name tagsoup
%define pkg_libdir %_libdir/%hsc_name-%hsc_version/%h_pkg_name-%version

Name: %hsc_namever-%f_pkg_name
Version: 0.14.8
Release: alt2
License: BSD3
Packager: Denis Smirnov <mithraen@altlinux.ru>
Group: Development/Haskell
Url: https://github.com/ndmitchell/tagsoup
Source: %name-%version.tar
Patch: %name-%version-%release.patch
Summary: Parsing and extracting information from (possibly malformed) HTML/XML documents

BuildPreReq: haskell(abi) = %ghc_version

BuildRequires: ghc8.6.4-common ghc8.6.4-doc

%description
TagSoup is a library for parsing HTML/XML. It supports the HTML 5
specification, and can be used to parse either well-formed XML, or
unstructured and malformed HTML from the web. The library also provides
useful functions to extract information from an HTML document, making it
ideal for screen-scraping.

Users should start from the "Text.HTML.TagSoup" module.

%prep
%setup
%patch -p1

%build
%hs_configure2
%hs_build

%install
%hs_install
%hs_gen_filelist

%files -f %name-files.all

%changelog
* Thu Aug 06 2020 Evgeny Sinelnikov <sin@altlinux.org> 0.14.8-alt2
- Clean from unneeded BuildRequires generated by buildreq

* Sun Jun 21 2020 Denis Smirnov <mithraen@altlinux.ru> 0.14.8-alt1
- Spec created by cabal2rpm 0.20_10
