%def_without profiling
%define hsc_name ghc
%define hsc_version %ghc_version
%define hsc_namever %hsc_name
%define h_pkg_name flow2dot
%define f_pkg_name flow2dot
%define pkg_libdir %_libdir/%hsc_name-%hsc_version/lib/%h_pkg_name-%version

Name: %f_pkg_name
Version: 0.9.0.1
Release: alt2

Summary: Generates sequence diagrams from textual descriptions
License: BSD3
Group: Development/Haskell

Url: http://adept.linux.kiev.ua/repos/flow2dot
Source: %name-%version.tar
Source1: flow2dot-fix-dot-lost-edges

Packager: Michael Shigorin <mike@altlinux.org>

# Automatically added by buildreq on Sun Jul 01 2012 (-bb)
# optimized out: elfutils ghc7.4.2 ghc7.4.2-common ghc7.4.2-mtl ghc7.4.2-random ghc7.4.2-text ghc7.4.2-transformers libgmp-devel pkg-config python-base rpm-build-haskell
BuildRequires: ghc7.4.2-doc ghc7.4.2-parsec ghc7.4.2-quickcheck ghc7.4.2-utf8-string graphviz

%description
Generates sequence diagrams from textual descriptions with help
of Graphviz graph drawing tool.

Check out <http://adept.linux.kiev.ua/repos/flow2dot/sample.flow> (source)
and <http://adept.linux.kiev.ua/repos/flow2dot/sample.png> (output).

%if_with profiling
%package -n %hsc_namever-%f_pkg_name-prof
Summary: Profiling libraries for %hsc_namever-%f_pkg_name
Group: Development/Libraries
Requires: %hsc_namever-%f_pkg_name = %version

%description -n %hsc_namever-%f_pkg_name-prof
Generates sequence diagrams from textual descriptions with help
of Graphviz graph drawing tool.

This package contains profiling libraries for %hsc_name %hsc_version.
%endif

%prep
%setup -n %h_pkg_name-%version

%build
%hs_configure2
%hs_build

%install
%hs_install
%hs_gen_filelist
install -pDm755 %SOURCE1 %buildroot%_bindir/flow2dot-fix-dot-lost-edges

%files -f %name-files.nonprof
%_bindir/*
%doc LICENSE README sample.*

%changelog
* Sun Jul 01 2012 Denis Smirnov <mithraen@altlinux.ru> 0.9.0.1-alt2
- rebuild with ghc 7.4.2

* Fri Mar 23 2012 Denis Smirnov <mithraen@altlinux.ru> 0.9.0.1-alt1
- 0.9.0.1

* Wed Apr 13 2011 Denis Smirnov <mithraen@altlinux.ru> 0.8-alt1
- 0.8

* Thu Apr 07 2011 Denis Smirnov <mithraen@altlinux.ru> 0.7-alt2
- fix build with ghc 7.0

* Sun Nov 01 2009 Michael Shigorin <mike@altlinux.org> 0.7-alt1
- 0.7

* Sat Oct 31 2009 Michael Shigorin <mike@altlinux.org> 0.6.1-alt2
- disabled profiling by default (thanks avm@ for a hint, silly me)

* Fri Oct 30 2009 Michael Shigorin <mike@altlinux.org> 0.6.1-alt1
- 0.6.1

* Tue Nov 25 2008 Michael Shigorin <mike@altlinux.org> 0.3-alt2
- rebuild against recent ghc

* Sat Feb 16 2008 Michael Shigorin <mike@altlinux.org> 0.3-alt1
- 0.3:
  + quote entity names for graphviz
- spec cleanup
- updated buildrequires

* Wed Feb 13 2008 Michael Shigorin <mike@altlinux.org> 0.2.1-alt0.20080213
- built for ALT Linux
- thanks Alexey V. Myltsev (avm@), see also #14412

* Wed Feb 13 2008 cabal-rpm <cabal-devel@haskell.org> 0.2.1-alt0.20080213
- spec file autogenerated by cabal-rpm
