Name: libytnef
Version: 1.5
Release: alt1

Summary: TNEF Stream Parser Library
Group: System/Libraries
License: GPL2
Url: http://ytnef.sf.net

Source: http://dl.sf.net/ytnef/%name-%version.tar.bz

# fc: fixes potential bufferoverflow
Patch: libytnef-fc-bufferoverflow.patch

%description
TNEF Stream Parser Library, used by "ytnef" to decode TNEF (winmail.dat)
streams generated by Microsoft Outlook.

%package devel
Summary: Development files for %name
Group: Development/C
Requires: %name = %version-%release

%description devel
The %name-devel package contains libraries and header files for
developing applications that use %name.

%prep
%setup
%patch -p1 -b .bufferoverflow

%build
%configure --disable-static
%make_build

%install
%makeinstall_std includedir=%_includedir/%name

%files
%_libdir/%name.so.*
%doc ChangeLog

%files devel
%_includedir/%name/
%_libdir/%name.so

%changelog
* Mon Jan 12 2015 Yuri N. Sedunov <aris@altlinux.org> 1.5-alt1
- first build for Sisyphus

