%define pypi_name pybtex_docutils

Name: python3-module-%pypi_name
Version: 1.0.3
Release: alt1

Summary: A docutils backend for pybtex
License: MIT
Group: Development/Python3
Url: https://github.com/mcmtroffaes/pybtex-docutils
Vcs: https://github.com/mcmtroffaes/pybtex-docutils.git

Source: %name-%version.tar

BuildRequires(Pre): rpm-build-python3
BuildRequires: python3-module-setuptools
BuildRequires: python3-module-docutils
BuildRequires: python3-module-pybtex

BuildArch: noarch

%description
The pybtex docutils backend allows BibTeX citations to be inserted into
documentation generated by docutils.

%prep
%setup

%build
%pyproject_build

%install
%pyproject_install

%files
%doc README.rst
%python3_sitelibdir_noarch/%pypi_name
%python3_sitelibdir_noarch/%{pyproject_distinfo %pypi_name}

%changelog
* Thu Apr 02 2026 Ulysses Apokin <ulysses@altlinux.org> 1.0.3-alt1
- Initial build for Sisyphus.
