Name:           python-module-happybase
Version:        0.8
Release:        alt2
Summary:        A developer-friendly Python library to interact with Apache HBase
License:        MIT
Group:          Development/Python
Url:            https://github.com/wbolster/happybase
Source:         %{name}-%{version}.tar
BuildRequires:  python-module-sphinx
BuildRequires:  python-devel
BuildRequires:  python-module-setuptools
BuildRequires:  python-module-thrift
Requires:       python-module-thrift

BuildArch:      noarch

%description
HappyBase is a developer-friendly Python library to interact with Apache HBase.

%prep
%setup

%build
python setup.py build
python setup.py build_sphinx
# Remove hidden file generated by Sphinx
rm doc/build/html/.buildinfo

%install
%python_install

# %check
# python setup.py test

%files
%doc LICENSE.rst NEWS.rst README.rst TODO.rst doc/build/html
%{python_sitelibdir}/*

%changelog
* Sat Dec 22 2018 Igor Vlasenko <viy@altlinux.ru> 0.8-alt2
- NMU: deleted and restored in Sisyphus due to new thrift

* Mon Aug 11 2014 Lenar Shakirov <snejok@altlinux.ru> 0.8-alt1
- First build for ALT (based on OpenSuSe 0.8-1.1.src)

