Name: ruby-compat
Epoch: 1
Version: 1.9.3
Release: alt1
Summary: Empty packages for bootstrap Ruby
License: Public domain
Group: Development/Ruby
BuildArch: noarch

%description
Empty packages for bootstrap Ruby.


%package -n ruby-tool-rdoc
Summary: Documentation tool for Ruby source code
Group: Development/Ruby
Requires: rdoc >= 1.9.3

%description -n ruby-tool-rdoc
RDoc is a documentation tool for Ruby source code.


%package -n rubygems
Summary: A package management framework for the Ruby programming language
Group: Development/Ruby
Requires: ruby-tools >= 1.9.3

%description -n rubygems
RubyGems is a package management framework for the Ruby programming language.


%package -n ruby-rake
Summary: Ruby based make-like utility
Group: Development/Ruby
Requires: ruby-tools >= 1.9.3

%description -n ruby-rake
ake is a Make-like program implemented in Ruby. Tasks and dependencies are
specified in standard Ruby syntax.


%package -n ruby-test-unit
Summary: Ruby unit testing framework
Group: Development/Ruby
Requires: ruby-tools >= 1.9.3
Provides: ruby-test-unit = 2.2.0

%description -n ruby-test-unit
Ruby unit testing framework.


%package -n ruby-minitest
Summary: Small and fast replacement for ruby's huge and slow test/unit
Group: Development/Ruby
Requires: ruby-stdlibs >= 1.9.3
Provides: ruby-minitest = 2.5.1

%description -n ruby-minitest
Small and fast replacement for ruby's huge and slow test/unit.


%package -n ruby-json
Summary: JSON parser and generator
Group: Development/Ruby
Requires: ruby-stdlibs >= 1.9.3
Provides: ruby-json = 1.5.4

%description -n ruby-json
JSON parser and generator.


%package -n ruby-racc-runtime
Summary: Runtime library for parser which is generated by Racc
Group: Development/Ruby
Requires: ruby-stdlibs >= 1.9.3

%description -n ruby-racc-runtime
Runtime library for parser which is generated by Racc.


%files -n ruby-tool-rdoc


%files -n rubygems


%files -n ruby-rake


#files -n ruby-test-unit


%files -n ruby-minitest


%files -n ruby-json


#files -n ruby-racc-runtime


%changelog
* Fri Dec 07 2012 Led <led@altlinux.ru> 1:1.9.3-alt1
- Temporary build
