#
#   - HTTP::Request::AsCGI -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#

%define module HTTP-Request-AsCGI
%define m_distro HTTP-Request-AsCGI
%define m_name HTTP::Request::AsCGI
%define m_author_id unknown
%def_enable test

Name: perl-HTTP-Request-AsCGI
Version: 1.2
Release: alt1.1

Summary: %m_name - Setup a CGI enviroment from a HTTP::Request

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/HTTP-Request-AsCGI/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/C/CH/CHANSEN/%m_distro-%version.tar.gz

# Automatically added by buildreq on Tue Apr 20 2010 (-bi)
BuildRequires: perl-Class-Accessor perl-devel perl-libwww

%description
Provides a convinient way of setting up an CGI enviroment from a
HTTP::Request.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/HTTP*
%doc Changes README examples

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 1.2-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Apr 20 2010 Alexey Tourbin <at@altlinux.ru> 1.2-alt1
- 0.5 -> 1.2

* Sat Sep 13 2008 Michael Bochkaryov <misha@altlinux.ru> 0.5-alt2
- fix directory ownership violation
- spec file cleanup
- docs and examples added to package

* Wed Mar 14 2007 Sir Raorn <raorn@altlinux.ru> 0.5-alt1
- first build for ALT Linux Sisyphus

