#
#   - Error -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --spec-only Error
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Error
%define m_distro Error
%define m_name Error
%define m_author_id unknown
%define _enable_test 1

Name: perl-Error
Version: 0.17016
Release: alt1.1

Summary: Error - Error/exception handling in an OO-ish way

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/S/SH/SHLOMIF/Error-0.17016.tar.gz

# Automatically added by buildreq on Thu Sep 01 2005
BuildRequires: perl-devel perl-Module-Build

%description
The "Error" package provides two interfaces. Firstly "Error" provides
a procedural interface to exception handling. Secondly "Error" is a
base class for errors/exceptions that can either be thrown, for
subsequent catch, or can simply be recorded.

Errors in the class "Error" should not be thrown directly, but the
user should throw errors from a sub-class of "Error".

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc ChangeLog README examples
%perl_vendor_privlib/Error.pm

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.17016-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Fri Jul 16 2010 Igor Vlasenko <viy@altlinux.ru> 0.17016-alt1
- automated CPAN update

* Sat Sep 06 2008 Vitaly Lipatov <lav@altlinux.ru> 0.15-alt2
- fix directory ownership violation

* Thu Sep 01 2005 Vitaly Lipatov <lav@altlinux.ru> 0.15-alt1
- first build for ALT Linux Sisyphus
