%define target_lua_version 5.4

# Original package name basexx
%define oname basexx
%define oversion 0.4.1-1
%define rockspec basexx-0.4.1-1.rockspec
Name: lua%target_lua_version-module-%oname
Version: 0.4.1
Release: alt2_lr1
Summary: A base2, base16, base32, base64 and base85 library for Lua
License: MIT
Group: Development/Other
Url: https://github.com/aiq/basexx

# These Obsoletes/Provides only necessary when previous (out-of-poicy) versions exist in repo
%if "%target_lua_version" == "5.4"
Obsoletes: lua-module-%oname < %EVR
Provides: lua-module-%oname = %version
%else
Obsoletes: lua5-%oname < %EVR
Provides: lua5-%oname = %version
%endif

Source: https://github.com/aiq/basexx/archive/v0.4.1.tar.gz#/basexx-0.4.1.tar.gz
Source1: https://luarocks.org/manifests/luarocks/basexx-0.4.1-1.rockspec

BuildPreReq: rpm-macros-lua >= 1.5.2 rpm-build-lua
# Automatically added by buildreq on ...
BuildRequires: lua%target_lua_version-luarocks

BuildArch: noarch
BuildRequires: lua5.3-luarocks lua5.1-luarocks

%description
A Lua library which provides base2(bitfield), base16(hex), base32(crockford/rfc), base64(rfc/url), base85(z85) decoding and encoding.

%package -n lua5.3-module-%oname
Summary: A base2, base16, base32, base64 and base85 library for Lua
Group: Development/Other
%description -n lua5.3-module-%oname
A Lua library which provides base2(bitfield), base16(hex), base32(crockford/rfc), base64(rfc/url), base85(z85) decoding and encoding.
%package -n lua5.1-module-%oname
Summary: A base2, base16, base32, base64 and base85 library for Lua
Group: Development/Other
%description -n lua5.1-module-%oname
A Lua library which provides base2(bitfield), base16(hex), base32(crockford/rfc), base64(rfc/url), base85(z85) decoding and encoding.

%prep
%setup -n %oname-%version

%install
%luarocks_make %SOURCE1
%luarocks_move_docs test

%check
%lua_path_add_buildroot
[ -x /usr/bin/busted ] || exit 0
busted

%add_findreq_skiplist %luarocks_dbdir_prefix-*/%oname/*/{doc,docs,etc,examples,samples,spec,test}/*

%files
%lua54_modulesdir_noarch/*
%luarocks_dbdir_prefix-%target_lua_version/%oname
%doc CHANGELOG* LICENSE* README* docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-%target_lua_version/manifest

%files -n lua5.3-module-%oname
%lua53_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.3/%oname
%doc CHANGELOG* LICENSE* README* docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.3/manifest

%files -n lua5.1-module-%oname
%lua51_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.1/%oname
%doc CHANGELOG* LICENSE* README* docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.1/manifest

%changelog
* Sun Feb 11 2024 Ildar Mulyukov <ildar@altlinux.ru> 0.4.1-alt2_lr1
- autogenerated by lrimport

* Sat Mar 28 2020 Alexey Shabalin <shaba@altlinux.org> 0.4.1-alt2
- fix path to rockspec

* Sat Mar 28 2020 Alexey Shabalin <shaba@altlinux.org> 0.4.1-alt1
- Initial build
