#
#   - Device::Gsm -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Device::Gsm
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Device-Gsm
%define m_distro Device-Gsm
%define m_name Device::Gsm
%define m_author_id unknown
%define _enable_test 1

Name: perl-Device-Gsm
Version: 1.58
Release: alt1

Summary: Perl extension to interface GSM phones / modems

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Denis Smirnov <mithraen@altlinux.ru>

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Wed May 25 2011 (-bb)
# optimized out: perl-Device-SerialPort
BuildRequires: perl-Device-Modem perl-Encode perl-devel

%description
`Device::Gsm' class implements basic GSM functions, network registration and SMS sending.

This class supports also `PDU' mode to send `SMS' messages, and should be
fairly usable. In the past, I have developed and tested it under Linux RedHat 7.1
with a 16550 serial port and Siemens C35i/C45 GSM phones attached with
a Siemens-compatible serial cable. Currently, I'm developing and testing this stuff
with Linux Slackware 10.2 and a Cambridge Silicon Radio (CSR) USB
bluetooth dongle, connecting to a Nokia 6600 phone.

Please be kind to the universe and contact me if you have troubles or you are
interested in this.

Please be monstruosly kind to the universe and (if you don't mind spending an SMS)
use the `examples/send_to_cosimo.pl' script to make me know that Device::Gsm works
with your device (thanks!).

Recent versions of `Device::Gsm' have also an utility called `autoscan' in
the `bin/' folder, that creates a little profile of the devices it runs
against, that contains information about supported commands and exact output
of commands to help recognize similar devices.

Be sure to send me your profile by email (if you want to),
so I can add better support for your device in the future!

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Device/*

%changelog
* Wed May 25 2011 Denis Smirnov <mithraen@altlinux.ru> 1.58-alt1
- initial build for ALT Linux Sisyphus

