Name: synaptic-usermode
Version: 1.3
Release: alt3

Summary: Usermode bindings for synaptic
Group: System/Configuration/Packaging
License: GPL
BuildArch: noarch
Packager: Dmitry V. Levin <ldv@altlinux.org>

Source: %name-%version.tar

Requires: synaptic >= 0.15-alt7, consolehelper

BuildPreReq: libpam-devel

%define conshelpdir %_libexecdir/consolehelper

%description
Synaptic is a graphical front-end for APT (Advanced Package Tool).
It attempts to be a lot easier to use than other existing APT front-ends.

This package contains usermode bindings for synaptic.

%prep
%setup

%install
mkdir -p %buildroot%_bindir
ln -s $(relative %conshelpdir/helper %_bindir/) %buildroot%_bindir/synaptic
install -pD -m640 synaptic.pamd %buildroot%_sysconfdir/pam.d/synaptic
install -pD -m640 synaptic.security %buildroot%_sysconfdir/security/console.apps/synaptic
install -pD -m644 synaptic-16.png %buildroot%_miconsdir/synaptic.png
install -pD -m644 synaptic-32.png %buildroot%_niconsdir/synaptic.png
install -pD -m644 synaptic-48.png %buildroot%_liconsdir/synaptic.png
install -pD -m644 synaptic.desktop %buildroot%_datadir/applications/synaptic.desktop

%files
%config(noreplace) %_sysconfdir/pam.d/synaptic
%config(noreplace) %_sysconfdir/security/console.apps/synaptic
%_bindir/synaptic
%_datadir/applications/synaptic.desktop
%_miconsdir/synaptic.png
%_niconsdir/synaptic.png
%_liconsdir/synaptic.png

%changelog
* Fri May 27 2011 Lenar Shakirov <snejok@altlinux.ru> 1.3-alt3
- System category replaced by Settings in desktop file

* Thu Oct 28 2010 Lenar Shakirov <snejok@altlinux.ru> 1.3-alt2
- Settings removed from Category in desktop file (closes: #18642)

* Sun Dec 28 2008 Dmitry V. Levin <ldv@altlinux.org> 1.3-alt1
- Removed obsolete %%post/%%postun scripts.
- Moved icons to proper location.
- Updated desktop file.
- Made absolute symlink relative.

* Sat Feb 25 2006 Sviatoslav Sviridov <svd@altlinux.ru> 1.2-alt2
- Removed Debian-style menu
- Using macros for icon dirs in files section

* Thu Jan 12 2006 ALT QA Team Robot <qa-robot@altlinux.org> 1.2-alt1.1
- Rebuilt for new style PAM dependencies generated by rpm-build-4.0.4-alt55.

* Wed Aug 31 2005 Sviatoslav Sviridov <svd@altlinux.ru> 1.2-alt1
- Added freedesktop menu entry
- Updatet menu file: using same title and longtitle as in .desktop file
- Updated icon from synaptic package

* Tue Jun 21 2005 Dmitry V. Levin <ldv@altlinux.org> 1.1-alt3
- Updated %_bindir/synaptic symlink.

* Thu Sep 25 2003 Dmitry V. Levin <ldv@altlinux.org> 1.1-alt2
- Updated package dependencies.

* Fri Dec 06 2002 Dmitry V. Levin <ldv@altlinux.org> 1.1-alt1
- Replaced .xpm icons with .png ones.
- Added "icon=" option to menu file (#0001670).

* Thu Nov 08 2001 Dmitry V. Levin <ldv@alt-linux.org> 1.0-alt1
- Moved usermode stuff to separate package.
