
%define _unpackaged_files_terminate_build 1

%define common_summary A Rust port of the reverb module from Vital/Vitalium synthesizer

%define common_description A Rust port of the reverb module from the Vital/Vitalium\
synthesizer, allowing it to be used as an effect plugin.\
There are also a few minor improvements and optimizations added.

Name: vitalium-verb
Version: 1.3.0
Release: alt1

Summary: %common_summary
License: GPL-3.0-or-later
Group: Sound
Url: https://github.com/BillyDM/vitalium-verb
Vcs: https://github.com/BillyDM/vitalium-verb.git

# Exclude i586 just because I can
ExcludeArch: %ix86

Source: %name-%version.tar

# cargo-vendor-alt > .gear/config.toml
Source1: vendor.tar
Source2: config.toml

Patch: %name-%version-%release.patch

BuildRequires(pre): rpm-build-rust
BuildRequires: /proc

BuildRequires: pkgconfig(alsa)
BuildRequires: pkgconfig(jack)
BuildRequires: pkgconfig(gl)
BuildRequires: pkgconfig(glu)
BuildRequires: pkgconfig(x11)
BuildRequires: pkgconfig(xcb)
BuildRequires: pkgconfig(xcb-icccm)
BuildRequires: pkgconfig(xcb-util)

BuildRequires: sccache

%description
%common_description


%package -n vst3-%name-plugin
Summary: %common_summary -- VST3
Group: Sound

%description -n vst3-%name-plugin
%common_description

This package contains %name build as VST3 plugin.


%prep
%setup -a1

# Add our config.toml was generated by cargo vendor to upstream
# one to preserve the aliases there.
cat %SOURCE2 >> .cargo/config.toml

cat >> .cargo/config.toml <<EOF
[build]
rustflags = ["-Copt-level=3", "-Cdebuginfo=2"]

[profile.release]
strip = false
EOF

%autopatch -p1

%build
# allow nightly features, e.g. portable_simd
export RUSTC_BOOTSTRAP=1
# use sccache
export RUSTC_WRAPPER="$(which sccache)"

cargo xtask bundle vitalium_verb --release

%install
mkdir -p %buildroot%_libdir/vst3
cp  -a -t %buildroot%_libdir/vst3/ ./target/bundled/*.vst3

%files -n vst3-%name-plugin
%_libdir/vst3/*


%changelog
* Sun Jan 04 2026 Ivan A. Melnikov <iv@altlinux.org> 1.3.0-alt1
- build for Sisyphus
