#
#   - File::Which -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       File::Which
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module File-Which
%define m_distro File-Which
%define m_name File::Which
%define m_author_id PEREINAR
%define _enable_test 1

Name: perl-File-Which
Version: 1.09
Release: alt1.1

Summary: Portable implementation of the `which' utility

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/File-Which/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/P/PE/PEREINAR/%m_distro-%version.tar.gz

# Automatically added by buildreq on Sat Sep 13 2008 (-bi)
BuildRequires: perl-devel perl-Test-Script

# automatically added during perl 5.8 -> 5.12 upgrade.
# perl-podlators is required for pod2man conversion.
BuildRequires: perl-podlators

%description
"File::Which" was created to be able to get the paths to executable programs
on systems under which the `which' program wasn't implemented in the shell.

"File::Which" searches the directories of the user's "PATH" (as returned by
"File::Spec->path()"), looking for executable files having the name specified
as a parameter to "which()". Under Win32 systems, which do not have a notion of
directly executable files, but uses special extensions such as ".exe" and
".bat" to identify them, "File::Which" takes extra steps to assure that you
will find the correct file (so for example, you might be searching for "perl",
it'll try "perl.exe", "perl.bat", etc.)

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build INSTALLMAN1DIR=%_man1dir

%install
%perl_vendor_install

%files
%_bindir/pwhich
%_man1dir/pwhich*
%perl_vendor_privlib/File*
%doc Changes README

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 1.09-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Fri Jan 29 2010 Vladimir Lettiev <crux@altlinux.ru> 1.09-alt1
- NMU: New version 1.09
- Added pwhich - perl-only replacement for which

* Sat Sep 13 2008 Michael Bochkaryov <misha@altlinux.ru> 0.05-alt2
- fix directory ownership violation

* Wed Apr 09 2008 Michael Bochkaryov <misha@altlinux.ru> 0.05-alt1
- first build for ALT Linux Sisyphus

