#
#   - Module-Starter-Plugin-SimpleStore -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       -debug Module::Starter::Plugin::SimpleStore
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Module-Starter-Plugin-SimpleStore
%define m_distro Module-Starter-Plugin-SimpleStore
%define m_name Module-Starter-Plugin-SimpleStore
%define m_author_id unknown
%define _enable_test 1

Name: perl-Module-Starter-Plugin-SimpleStore
Version: 0.143
Release: alt1

Summary: template storage methods for Module::Starter

License: Artistic and GPL
Group: Development/Perl
Url: %CPAN %m_distro

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/R/RJ/RJBS/%m_distro-%version.tar.gz

# Automatically added by buildreq on Tue Oct 27 2009 (-bi)
BuildRequires: perl-Module-Starter perl-Test-Pod perl-Test-Pod-Coverage

%description
This Module::Starter plugin is intended to be loaded after
Module::Starter::Plugin::Template.  It implements the "templates" method,
required by the Template plugin.  The "DirStore" plugin stores all the
required templates as files in a directory.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/
mkdir -p %buildroot%_bindir
install -m755 bin/ms-pack %buildroot%_bindir/module-starter-pack

%files
%perl_vendor_privlib/Module/Starter/Plugin/*
%_bindir/*
%doc LICENSE Changes README

%changelog
* Tue Oct 27 2009 Michael Bochkaryov <misha@altlinux.ru> 0.143-alt1
- initial build for ALT Linux Sisyphus

