%define _unpackaged_files_terminate_build 1
#
#   - User::Identity -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       User::Identity
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module User-Identity
%define m_distro User-Identity
%define m_name User::Identity
%define m_author_id unknown
%define _enable_test 1

Name: perl-User-Identity
Version: 0.98
Release: alt1

Summary: Define a user

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source0: http://www.cpan.org/authors/id/M/MA/MARKOV/%{module}-%{version}.tar.gz

# Automatically added by buildreq on Sat Feb 04 2006
BuildRequires: perl-TimeDate perl-devel

%description
The User::Identity object is created to maintain a set of informational
objects which are related to one user. The User::Identity module tries to
be smart providing defaults, conversions and often required combinations.

The identities are not implementing any kind of storage, and can therefore
be created by any simple or complex Perl program. This way, it is more
flexible than an XML file to store the data. For instance, you can
decide to store the data with Data::Dumper, Storable, DBI, AddressBook
or whatever. Extension to simplify this task are still to be developed.

%prep
%setup -q -n %{module}-%{version}

%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%doc Changes README
%perl_vendor_privlib/User/*
%perl_vendor_privlib/Mail/*

%changelog
* Thu Nov 23 2017 Igor Vlasenko <viy@altlinux.ru> 0.98-alt1
- automated CPAN update

* Tue Feb 14 2017 Igor Vlasenko <viy@altlinux.ru> 0.97-alt1
- automated CPAN update

* Sun Sep 25 2016 Igor Vlasenko <viy@altlinux.ru> 0.96-alt1
- automated CPAN update

* Tue Jan 28 2014 Igor Vlasenko <viy@altlinux.ru> 0.94-alt1
- automated CPAN update

* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 0.93-alt1
- automated CPAN update

* Fri Oct 10 2008 Vitaly Lipatov <lav@altlinux.ru> 0.92-alt1
- new version 0.92 (with rpmrb script)
- pack missed Mail::Identity

* Sat Sep 06 2008 Vitaly Lipatov <lav@altlinux.ru> 0.90-alt2
- fix directory ownership violation
- disable man packaging

* Sat Feb 04 2006 Vitaly Lipatov <lav@altlinux.ru> 0.90-alt1
- initial build for ALT Linux Sisyphus

