#
#   - Net::Radius -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   (ALT Linux revision)
#   The following arguments were used:
#       Net::Radius
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Net-Radius
%define m_distro Net-Radius
%define m_name Net::Radius
%define m_author_id unknown
%define _enable_test 1

Name: perl-Net-Radius
Version: 2.103
Release: alt1

Summary: Net-Radius - Perl module

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Eugene Prokopiev <enp@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/L/LU/LUISMUNOZ/Net-Radius-%{version}.tar.gz

# Automatically added by buildreq on Mon Dec 17 2012
# optimized out: perl-Sub-Uplevel perl-Tree-DAG_Node perl-devel
BuildRequires: perl-Test-Warn subversion

%description
None.

%prep
%setup -n %m_distro-2.103
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Net/*

%changelog
* Wed Jul 24 2013 Igor Vlasenko <viy@altlinux.ru> 2.103-alt1
- automated CPAN update

* Mon Dec 17 2012 Eugene Prokopiev <enp@altlinux.ru> 2.000-alt1
- initial build for ALT Linux Sisyphus

