Name:		filigram
Version:	7422
Release:	alt1
Group:		Sciences/Mathematics
License:	MIT/X11
Summary:	Pretty pictures generation by mathematical means
# wget -r -l1 --cut-dirs=2 -k -nH -np -P filigram http://www.chiark.greenend.org.uk/~sgtatham/filigram
Source:		%name-%version.tar
Patch:		%name.help.patch
URL:		http://www.chiark.greenend.org.uk/~sgtatham/filigram

%description
Filigrams are a type of pretty pictures generated by mathematical means.
They're not technically a type of fractal, although they contain elements which
people who know fractals might find hauntingly familiar. They're something
I invented by accident once and decided to polish up because it looked pretty. 

%prep
%setup
%patch

%build
gcc %name.c -o%name

%install
install -D %name %buildroot%_bindir/%name

%files
%doc *[^m]
%_bindir/*

%changelog
* Mon Aug 23 2010 Fr. Br. George <george@altlinux.ru> 7422-alt1
- Initial build for ALT

