#
#   - HTML::BBReverse -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       HTML-BBReverse --version 0.07
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module HTML-BBReverse
%define m_distro HTML-BBReverse
%define m_name HTML::BBReverse
%define m_author_id unknown
%define _enable_test 1

Name: perl-HTML-BBReverse
Version: 0.07
Release: alt1.1.1

Summary: HTML-BBReverse - Perl module

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Igor Zubkov <icesik@altlinux.ru>

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Sat May 03 2008
BuildRequires: perl-Module-Build

%description
HTML-BBReverse - Perl module.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/*
%exclude %perl_vendor_archlib

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.07-alt1.1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Oct 07 2008 Igor Vlasenko <viy@altlinux.ru> 0.07-alt1.1
- NMU: fix for perlarchdir ownership

* Sat May 03 2008 Igor Zubkov <icesik@altlinux.org> 0.07-alt1
- build for Sisyphus

