# Original package name LuaFileSystem
%define oname luafilesystem
%define oversion 1.6.2-2
%define rockspec %oname-%oversion.rockspec
Name: lua-module-%oname
Version: 1.6.2
Release: alt2
Summary: File System Library for the Lua Programming Language
License: MIT/X11
Group: Development/Other
Url: http://www.keplerproject.org/luafilesystem/
Packager: Ildar Mulyukov <ildar@altlinux.ru>
Obsoletes: lua5-luafilesystem
Provides: lua5-luafilesystem = %version
Provides: luarocks(%oname) = %version

Source: https://github.com/downloads/keplerproject/luafilesystem/luafilesystem-1.6.2.tar.gz
Source1: https://rocks.moonscript.org/manifests/luarocks/luafilesystem-1.6.2-2.rockspec

BuildPreReq: rpm-macros-lua >= 1.2
# Automatically added by buildreq on ...
BuildRequires: liblua5-devel luarocks

%description
      LuaFileSystem is a Lua library developed to complement the set of
      functions related to file systems offered by the standard Lua
      distribution. LuaFileSystem offers a portable way to access the
      underlying directory structure and file attributes.

%prep
%setup -n %oname-%version

%install
%luarocks_make %SOURCE1
%luarocks_move_docs doc

%check
%lua_path_add_buildroot
for t in %buildroot%luarocks_dbdir/%oname/%oversion/tests/* ; do
  lua $t
done

%files
%lua_modulesdir/*
%luarocks_dbdir/%oname
%doc README* docs_from_rockstree/*
%exclude %luarocks_dbdir/manifest

%changelog
* Thu Jul 13 2017 Aleksei Nikiforov <darktemplar@altlinux.org> 1.6.2-alt2
- Rebuild with new luarocks and lua-5.3

* Mon Oct 06 2014 Ildar Mulyukov <ildar@altlinux.ru> 1.6.2-alt1_lr2
- autogenerated by lrimport

* Thu Jan 06 2011 Ildar Mulyukov <ildar@altlinux.ru> 1.5.0-alt1_lr1
- autogenerated by lrimport
