Name: fossil
Version: 1.30
Release: alt1

Summary: A distributed SCM with bug tracking and wiki
License: %bsdstyle
Group: Development/Other
Url: http://www.fossil-scm.org/
Source: %name-%version.tar
Patch: %name-%version-%release.patch

BuildRequires(pre): rpm-build-licenses
BuildRequires: zlib-devel libsqlite3-devel libssl-devel libreadline-devel tcl

%description
Fossil is a simple, high-reliability, distributed software configuration
management with distributed bug tracking, distributed wiki and built-in
web interface.

%package doc
Summary: Fossil documentation
Group: Development/Documentation

%description doc
Documentation in HTML format for Fossil.

%prep
%setup
%patch -p1

%build
# configure script is not generated by autoconf but by autosetup,
# so don't use %%configure macro
./configure \
	--prefix=%_usr \
	--disable-internal-sqlite \
	--with-openssl=auto

%make_build

%install
%makeinstall_std

%files
%doc COPYRIGHT-BSD2.txt
%_bindir/fossil

# Don't package documentation,
# seems like something wrong with it.
#files doc
#doc www

%changelog
* Wed Feb 11 2015 Mikhail Efremov <sem@altlinux.org> 1.30-alt1
- Updated to 1.30.

* Tue Aug 05 2014 Mikhail Efremov <sem@altlinux.org> 1.29-alt1
- Updated to 1.29.

* Tue Feb 11 2014 Mikhail Efremov <sem@altlinux.org> 1.28-alt1
- Updated to 1.28.

* Fri Jan 10 2014 Mikhail Efremov <sem@altlinux.org> 1.27-alt1
- Initial build.

