#
#   - Catalyst::Plugin::Session -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#

%define module Catalyst-Plugin-Session
%define m_distro Catalyst-Plugin-Session
%define m_name Catalyst::Plugin::Session
%define m_author_id NUFFIN
%def_enable test

Name: perl-Catalyst-Plugin-Session
Version: 0.32
Release: alt1

Summary: %m_name - Generic Session plugin - ties together server side

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/Catalyst-Plugin-Session/

Packager: Michael Bochklaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/B/BO/BOBTFISH/Catalyst-Plugin-Session-0.32.tar.gz

# Automatically added by buildreq on Tue Apr 20 2010 (-bi)
BuildRequires: perl-Catalyst-Runtime perl-Module-Install perl-Object-Signature perl-Test-Deep perl-Test-Exception perl-Test-Pod perl-Test-Pod-Coverage

%description
The Session plugin is the base of two related parts of
functionality required for session management in web
applications.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Catalyst*
%doc Changes README

%changelog
* Mon Sep 19 2011 Igor Vlasenko <viy@altlinux.ru> 0.32-alt1
- automated CPAN update

* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.30-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 0.30-alt1
- automated CPAN update

* Tue Apr 20 2010 Alexey Tourbin <at@altlinux.ru> 0.29-alt1
- 0.19 -> 0.29

* Mon Sep 08 2008 Michael Bochkaryov <misha@altlinux.ru> 0.19-alt2
- fix directory ownership violation

* Tue Jul 01 2008 Michael Bochkaryov <misha@altlinux.ru> 0.19-alt1
- 0.19 version build

* Tue Mar 27 2007 Sir Raorn <raorn@altlinux.ru> 0.14-alt1
- first build for ALT Linux Sisyphus

