%set_automake_version 1.11

Name: knetload
Version: 2.9.92
Release: alt1
Serial: 1

Group: Monitoring
Summary: Network traffic monitor for KDE3/TDE Kicker
URL: http://www.flameeyes.eu/oldstuff
License: %gpl2only

Source: %name-%version.tar.bz2
Source1: %name-Makefile.am

Patch1: %name-2.9.92-automake.patch

Patch10: %name-2.9.92-kcfg.diff
Patch11: %name-2.9.92-if-name.diff

# Automatically added by buildreq on Mon Dec 22 2014 (-bi)
# optimized out: elfutils fontconfig gnu-config imake kdebase-common kdelibs kdelibs-devel kdepim-libs libICE-devel libSM-devel libX11-devel libXext-devel libXt-devel libpng-devel libqt3-devel libqt3-settings libstdc++-devel libtqt-devel pkg-config python-base xml-utils xorg-cf-files xorg-xproto-devel zlib-devel
BuildRequires: doxygen gcc-c++ graphviz kde-i18n-ru kdepim-devel libjpeg-devel xdg-user-dirs

BuildRequires: rpm-build-licenses rpm-macros-kde-common-devel rpm-macros-qt3

%description
This is a network throughput meter for Kicker (the KDE3/TDE Panel).
It will show the traffic on a network device with two diagrams, one
for outgoing and one for incoming data.

Since version 3, KNetLoad is now a true full-integrated Kicker applet,
no more the old standalone application which resides on the system
tray. This change allow you to have bigger, more readable graphs, and
also allow you to add more than one interface monitored at a time.

%prep
%setup -q
%patch1 -p1

%patch10 -p1
%patch11 -p1

make -f admin/Makefile.common cvs ||:

%build

%add_optflags -I%_includedir/tqtinterface -lkdeui -lkdecore -L%_qt3dir/lib -lqt-mt -fPIC -DPIC

%K3configure \
    --enable-final \
    --enable-shared \
    --disable-static \
    --disable-rpath \
    --program-transform-name=""

%make_build

pushd knetload/.libs
g++ -shared -L%_qt3dir/lib -o libknetloadapplet.so *.o -lkdeui -lkdecore -lqt-mt -lpthread
popd

%install
%K3install PACKAGE=%name

pushd %buildroot/%_K3doc
for DIR in `ls -d *`; do
    pushd $DIR
    NAME=`ls -d *`
    if [ "$NAME" = "doc" ]; then
        mv $NAME %name
    fi
    popd
done
popd

mkdir %_bKlibdir
mv %buildroot/%_libdir/libknetloadapplet.so %_bKlibdir

%K3find_lang %name
echo '%lang(sr) /usr/share/kde/locale/sr@Latn/LC_MESSAGES/knetload.mo' >> %name.lang

%files -f %name.lang
%_Klibdir/libknetloadapplet.so

%_datadir/icons/crystalsvg/*/apps/%name.*

%_K3cfg/knetload.kcfg
%_kde3_iconsdir/hicolor/*/apps/*.png

%_K3apps/kicker/applets/%{name}applet.desktop

%dir %_K3apps/knetloadapplet
%dir %_K3apps/knetloadapplet/pics
%_K3apps/knetloadapplet/pics/*.png

%dir %_K3doc/*/%name
%_K3doc/*/%name/*
%doc COPYING README AUTHORS

%changelog
* Thu Dec 18 2014 Sergey Y. Afonin <asy@altlinux.ru> 1:2.9.92-alt1
- new wersion (formally 3.0 alpha2)

* Thu Dec 18 2014 Sergey Y. Afonin <asy@altlinux.ru> 1:2.3-alt3
- returned to Sisyphus

* Thu Jan 27 2005 Sergey V Turchin <zerg at altlinux dot org> 1:2.3-alt2
- rebuild with gcc3.4

* Wed Aug 11 2004 Sergey V Turchin <zerg at altlinux dot org> 1:2.3-alt1
- new version

* Wed May 12 2004 Sergey V Turchin <zerg at altlinux dot org> 1:2.2.2-alt1
- new version

* Wed May 05 2004 Sergey V Turchin <zerg at altlinux dot org> 1:2.1.1-alt1
- new version
- update Russian translation
- fix package description
- fix i18n in popup window, in dock widget

* Mon Apr 05 2004 Sergey V Turchin <zerg at altlinux dot org> 1:2.00-alt0.3.beta2
- fix package description
- fix Russian translation
- update BuildRequires

* Wed Oct 01 2003 Sergey V Turchin <zerg at altlinux dot org> 1:2.00-alt0.2.beta2
- add Russian translation

* Tue Sep 30 2003 Sergey V Turchin <zerg at altlinux dot org> 1:2.00-alt0.1.beta2
- new version

* Tue Sep 30 2003 Sergey V Turchin <zerg at altlinux dot org> 1:1.99-alt1
- new version
- remove binary from tarball
- fix build requires

* Thu Sep 12 2002 Sergey V Turchin <zerg@altlinux.ru> 1:1.9.4-alt2
- rebuild with gcc3.2

* Sat Apr 27 2002 Sergey V Turchin <zerg@altlinux.ru> 1:1.9.4-alt1
- new version
- build with KDE3

* Fri Oct 12 2001 Sergey V Turchin <zerg@altlinux.ru> 1.91-ipl2mdk
- rebuild with new libpng

* Fri Mar 2 2001 AEN <aen@logic.ru> 1.91-ipl1mdk
- new version with KDE-2.1
* Mon Jan 15 2001 AEN <aen@logic.ru>
- RE adaptation
- BuildReq added

* Fri Nov 17 2000 David BAUDENS <baudens@mandrakesoft.com> 1.90-3mdk
- Rebuild with gcc-2.96 & glibc-2.2

* Tue Oct 10 2000 David BAUDENS <baudens@mandrakesoft.com> 1.90-2mdk
- Don't think i586 is alone in CPU constellation
- Macros

* Mon Oct  9 2000 Vincent Saugey <vince@mandrakesoft.com> 1.90-1mdk
- Up to KDE2 Version

* Thu May  4 2000 Vincent Saugey <vince@mandrakesoft.com> 1.3-7mdk
- Reducte entry menu to kde destop
- Remove rpath

* Tue Mar 28 2000 Francis Galiegue <fg@mandrakesoft.com> 1.3-6mdk
- Don't use prefix
- Don't use autogenerated file list
- Menu entry
- Changed group

* Fri Jan 21 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com>
- Libtoolize --force.

* Tue Dec 22 1999 - David BAUDENS <baudens@mandrakesoft.com>
- Add fr.po

* Tue Nov 23 1999 John Corey <jcorey@mandrakesoft.com>
- Rebuild with FHS-2.0 compliance

* Tue Oct 12 1999 Francis Galiegue <francis@mandrakesoft.com>
- fixed stupid bug of mine in spec file

* Tue Oct 12 1999 Francis Galiegue <francis@mandrakesoft.com>
- version 1.3
- spec file cleanups

* Sat Aug 28 1999 Daniel M. Duley <mosfet@linuxmandrake.com>
- Inital RPM.

