%define _unpackaged_files_terminate_build 1
%define mod_name alterator_backend_source

Name: alterator-backend-source
Version: 0.1.2
Release: alt1

Summary: System software sources manager for Alterator
License: GPLv2+
Group: System/Configuration/Other
URL: https://altlinux.space/sheriffkorov/alterator-backend-source

BuildArch: noarch

Source0: %name-%version.tar

Requires: python3-module-%{mod_name}
Requires: python3-module-gnupg
Requires: python3-module-urllib3
Requires: alterator-backend-systeminfo-utils
Requires: alterator-interface-source = %EVR
Requires: alterator-module-executor >= 0.1.29
Requires: alterator-entry

BuildRequires(pre): rpm-build-pyproject rpm-macros-alterator
BuildRequires: python3-devel
BuildRequires: python3-module-setuptools
%{?!_without_check:%{?!_disable_check:
BuildRequires: python3-module-pytest
BuildRequires: python3-module-tomlkit
BuildRequires: apt-source >= 0.1.1
BuildRequires: alterator-entry
BuildRequires: python3-module-gnupg
}}

%description
%summary.

%package -n alterator-interface-source
Summary: Interface of source for Alterator
Group: System/Configuration/Other

%description -n alterator-interface-source
%summary.

%package -n python3-module-%{mod_name}
Summary: System software sources manager for Alterator
Group: Development/Python3

Requires: apt-source >= 0.1.1
Requires: python3-module-gnupg
Requires: python3-module-tomlkit

%description -n python3-module-%{mod_name}
%summary.

%prep
%setup

%build
%pyproject_build

%install
mkdir -p %buildroot%_datadir/polkit-1/actions
install -v -p -m 664 -D interface/*.policy %buildroot%_datadir/polkit-1/actions
mkdir -p %buildroot%_datadir/dbus-1/interfaces
install -v -p -m 664 -D interface/*.xml %buildroot%_datadir/dbus-1/interfaces
mkdir -p %buildroot%_alterator_libdir/backends/source.d
install -v -p -m 755 -D scripts/* %buildroot%_alterator_libdir/backends/source.d
install -v -p -m 755 -D .gear/%{name}.filetrigger %buildroot%_rpmlibdir/10-%{name}.filetrigger
mkdir -p %buildroot%_alterator_datadir/backends
install -v -p -m 644 -D backend/*.backend %buildroot%_alterator_datadir/backends
%pyproject_install

%check
%pyproject_run_pytest

%files
%_alterator_libdir/backends
%_alterator_datadir/backends
%_rpmlibdir/10-%{name}.filetrigger

%files -n alterator-interface-source
%_datadir/polkit-1/actions
%_datadir/dbus-1/interfaces

%files -n python3-module-%{mod_name}
%python3_sitelibdir/%mod_name/
%python3_sitelibdir/%{pyproject_distinfo %mod_name}

%post
%_alterator_libdir/backends/source.d/generate-sources-backends

%preun
if [ $1 = 0 ]; then
    find %_sysconfdir/alterator/backends -name "autogenerated-source-*.backend" -type f -delete
fi


%changelog
* Tue Jun 09 2026 Maria Alexeeva <alxvmr@altlinux.org> 0.1.2-alt1
- Fix signature verification when apt-config returns an empty string.

* Mon Jun 08 2026 Maria Alexeeva <alxvmr@altlinux.org> 0.1.1-alt1
- Generated source lists are consolidated into a single file per source.
- Legacy mirror files are commented out (not deleted) during migration.
- Added Polkit authentication for write operations.
- Switched to APT methods to support all protocols.
- Removed parallel downloads due to mirror compatibility issues.
- Changed sign semantics: sign changes now apply only to enabled entries.
- Improved handling of malformed TOML files and missing sources.
- Thx Oleg Chagaev and Andrey Alekseev.

* Mon Mar 30 2026 Maria Alexeeva <alxvmr@altlinux.org> 0.1.0-alt1
- First build for Sisyphus.

