%define target_lua_version 5.4

# Original package name lpeg_patterns
%define oname lpeg_patterns
%define oversion 0.5-0
%define rockspec lpeg_patterns-0.5-0.rockspec
Name: lua%target_lua_version-module-%oname
Version: 0.5
Release: alt1_lr0
Summary: a collection of LPEG patterns
License: MIT
Group: Development/Other
Url: https://github.com/daurnimator/lpeg_patterns

# These Obsoletes/Provides only necessary when previous (out-of-poicy) versions exist in repo
%if "%target_lua_version" == "5.4"
Obsoletes: lua-module-%oname < %EVR
Provides: lua-module-%oname = %version
%else
Obsoletes: lua5-%oname < %EVR
Provides: lua5-%oname = %version
%endif

Source: https://github.com/daurnimator/lpeg_patterns/archive/v0.5.zip#/lpeg_patterns-0.5.zip
Source1: https://luarocks.org/manifests/luarocks/lpeg_patterns-0.5-0.rockspec

BuildPreReq: rpm-macros-lua >= 1.5.2 rpm-build-lua
BuildRequires: luarocks%target_lua_version(lpeg)
# Automatically added by buildreq on ...
BuildRequires: lua%target_lua_version-luarocks

BuildArch: noarch
BuildRequires: lua5.3-luarocks luarocks5.3(lpeg) lua5.1-luarocks luarocks5.1(lpeg)

%description
%summary

%package -n lua5.3-module-%oname
Summary: a collection of LPEG patterns
Group: Development/Other
%description -n lua5.3-module-%oname
%summary
%package -n lua5.1-module-%oname
Summary: a collection of LPEG patterns
Group: Development/Other
%description -n lua5.1-module-%oname
%summary

%prep
%setup -n %oname-%version

%install
%luarocks_make %SOURCE1
%luarocks_move_docs doc

%check
%lua_path_add_buildroot
[ -x /usr/bin/busted ] || exit 0
busted

%add_findreq_skiplist %luarocks_dbdir_prefix-*/%oname/*/{doc,docs,etc,examples,samples,spec,test}/*

%files
%lua54_modulesdir_noarch/*
%luarocks_dbdir_prefix-%target_lua_version/%oname
%doc NEWS* docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-%target_lua_version/manifest

%files -n lua5.3-module-%oname
%lua53_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.3/%oname
%doc NEWS* docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.3/manifest

%files -n lua5.1-module-%oname
%lua51_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.1/%oname
%doc NEWS* docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.1/manifest

%changelog
* Sun Feb 11 2024 Ildar Mulyukov <ildar@altlinux.ru> 0.5-alt1_lr0
- autogenerated by lrimport

* Sun Mar 29 2020 Alexey Shabalin <shaba@altlinux.org> 0.5-alt1
- Initial build.
