%define oname happybase

Name:       python3-module-%oname
Version:    0.8
Release:    alt3

Summary:    A developer-friendly Python library to interact with Apache HBase.
License:    MIT
Group:      Development/Python3
Url:        https://github.com/wbolster/happybase

BuildArch:  noarch

Source:     %{name}-%{version}.tar
Patch0:     port-on-python3.patch

BuildRequires(pre): rpm-build-python3
BuildRequires: python-tools-2to3
BuildRequires: python3-module-sphinx
BuildRequires: python3-module-thrift
BuildRequires: python3-module-nose

Requires: python3-module-thrift


%description
HappyBase is a developer-friendly Python library to interact with Apache HBase.

%package docs
Summary: Documentation for %oname
Group: Development/Documentation

%description docs
HappyBase is a developer-friendly Python library to interact with Apache HBase.

This package contains documentation for %oname.

%prep
%setup
%patch0 -p1

find -type f -name '*.py' -exec 2to3 -w -n '{}' +

%build
%__python3 setup.py build
%__python3 setup.py build_sphinx

# Remove hidden file generated by Sphinx
rm doc/build/html/.buildinfo

%install
%python3_install

%check
%__python3 setup.py test

%files
%doc LICENSE.rst README.rst
%python3_sitelibdir/*

%files docs
%doc doc/build/html


%changelog
* Fri Jan 24 2020 Andrey Bychkov <mrdrew@altlinux.org> 0.8-alt3
- Porting on Python3.

* Sat Dec 22 2018 Igor Vlasenko <viy@altlinux.ru> 0.8-alt2
- NMU: deleted and restored in Sisyphus due to new thrift

* Mon Aug 11 2014 Lenar Shakirov <snejok@altlinux.ru> 0.8-alt1
- First build for ALT (based on OpenSuSe 0.8-1.1.src)

