#
#   - Algorithm::CheckDigits -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Algorithm-CheckDigits-0.50.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Algorithm-CheckDigits
%define m_distro Algorithm-CheckDigits
%define m_name Algorithm::CheckDigits
%define m_author_id unknown
%define _enable_test 1

Name: perl-Algorithm-CheckDigits
Version: 0.50
Release: alt2.1

Summary: Perl extension to generate and test check digits

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vladimir A. Svyatoshenko <svyt@altlinux.ru>

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Thu Jul 03 2008
BuildRequires: perl-Test-Pod perl-Test-Pod-Coverage

%description
perl -MAlgorithm::CheckDigits -e Algorithm::CheckDigits::print_methods

or

  use Algorithm::CheckDigits;

  @ml = Algorithm::CheckDigits->method_list();

  $isbn = CheckDigits('ISBN');

  if ($isbn->is_valid('3-930673-48-7')) {
	# do something
  }

  $cn = $isbn->complete('3-930673-48');     # $cn = '3-930673-48-7'

  $cd = $isbn->checkdigit('3-930673-48-7'); # $cd = '7'

  $bn = $isbn->basenumber('3-930673-48-7'); # $bn = '3-930673-48'

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Algorithm*

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.50-alt2.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Oct 07 2008 Vladimir A. Svyatoshenko <svyt@altlinux.ru> 0.50-alt2
- fixed build

* Thu Jul 03 2008 Vladimir A. Svyatoshenko <svyt@altlinux.ru> 0.50-alt1
- first build for ALT Linux Sisyphus

