%define target_lua_version 5.3

# Original package name LuaExpat
%define oname luaexpat
%define oversion 1.3.3-1
%define rockspec luaexpat-1.3.3-1.rockspec
Name: lua%target_lua_version-module-%oname
Version: 1.3.3
Release: alt1_lr1
Summary: XML Expat parsing
License: MIT/X11
Group: Development/Other
Url: http://www.keplerproject.org/luaexpat/
Provides: luarocks%target_lua_version(%oname) = %EVR

%if "%target_lua_version" == "5.3"
Obsoletes: lua-module-%oname < %EVR
Provides: lua-module-%oname = %version
%else
Obsoletes: lua5-%oname < %EVR
Provides: lua5-%oname = %version
Obsoletes: lua-expat < %EVR
Provides: lua-expat = %version
%endif

Source: https://github.com/tomasguisasola/luaexpat/archive/v1.3.3.tar.gz
Source1: https://luarocks.org/manifests/luarocks/luaexpat-1.3.3-1.rockspec

BuildPreReq: rpm-macros-lua >= 1.4
# Automatically added by buildreq on ...
BuildRequires: liblua%target_lua_version-devel lua%target_lua_version-luarocks
BuildRequires: libexpat-devel

%description
      LuaExpat is a SAX (Simple API for XML) XML parser based on the
      Expat library.

%prep
%setup -n %oname-%version

%install
%luarocks_make %SOURCE1
%luarocks_move_docs doc

%check
%lua_path_add_buildroot
for t in %buildroot%luarocks_dbdir/%oname/%oversion/tests/* ; do
  lua%target_lua_version $t
done

%files
%lua_modulesdir/*
%lua_modulesdir_noarch/*
%luarocks_dbdir/%oname
%doc README* docs_from_rockstree/*
%exclude %luarocks_dbdir/manifest

%changelog
* Fri Jun 07 2019 Ildar Mulyukov <ildar@altlinux.ru> 1.3.3-alt1_lr1
- autogenerated by lrimport
- restuctured according to https://www.altlinux.org/Lua_Policy

* Thu Jul 13 2017 Aleksei Nikiforov <darktemplar@altlinux.org> 1.3.0-alt2
- Rebuild with new luarocks and lua-5.3

* Mon Oct 06 2014 Ildar Mulyukov <ildar@altlinux.ru> 1.3.0-alt1_lr1
- autogenerated by lrimport

