Name: appliance-hosting-pear
Summary: Requires all PHP PEAR packages
BuildArch: noarch
Version: 4.0.1
Release: alt1
License: GPL
Group: System/Base

Requires: pear-Archive_Zip
Requires: pear-Auth_HTTP
Requires: pear-Auth_PrefManager
Requires: pear-Auth_PrefManager2
Requires: pear-Auth_SASL
Requires: pear-CodeGen_PECL
Requires: pear-Console_Color
Requires: pear-Console_Getargs
Requires: pear-Console_Table
Requires: pear-Contact_Vcard_Build
Requires: pear-Contact_Vcard_Parse
Requires: pear-Crypt_Blowfish
Requires: pear-Crypt_CBC
Requires: pear-Crypt_HMAC
Requires: pear-Crypt_RC4
Requires: pear-Crypt_RSA
Requires: pear-Crypt_Xtea
Requires: pear-DBA
Requires: pear-DB_DataObject_FormBuilder
Requires: pear-DB_NestedSet
Requires: pear-DB_QueryTool
Requires: pear-DB_Table
Requires: pear-DB_ldap
Requires: pear-FSM
Requires: pear-File
Requires: pear-File_Archive
Requires: pear-File_Bittorrent
Requires: pear-File_Find
Requires: pear-File_Fortune
Requires: pear-File_HtAccess
Requires: pear-File_Passwd
Requires: pear-File_SMBPasswd
Requires: pear-File_SearchReplace
Requires: pear-Games_Chess
Requires: pear-Gtk2_EntryDialog
Requires: pear-Gtk2_IndexedComboBox
Requires: pear-Gtk_ScrollingLabel
Requires: pear-Gtk_Styled
Requires: pear-Gtk_VarDump
Requires: pear-HTML_BBCodeParser
Requires: pear-HTML_Crypt
Requires: pear-HTML_Form
Requires: pear-HTML_Javascript
Requires: pear-HTML_Menu
Requires: pear-HTML_Progress
Requires: pear-HTML_Progress2
Requires: pear-HTML_QuickForm2
Requires: pear-HTML_QuickForm_Controller
Requires: pear-HTML_QuickForm_advmultiselect
Requires: pear-HTML_QuickForm_altselect
Requires: pear-HTML_Select_Common
Requires: pear-HTML_Table_Matrix
Requires: pear-HTML_Template_Flexy
Requires: pear-HTML_Template_IT
Requires: pear-HTML_Template_PHPLIB
Requires: pear-HTML_Template_Sigma
Requires: pear-HTML_Template_Xipe
Requires: pear-HTML_TreeMenu
Requires: pear-HTTP_Client
Requires: pear-HTTP_Download
Requires: pear-HTTP_Upload
Requires: pear-I18N_UnicodeNormalizer
Requires: pear-I18Nv2
Requires: pear-Image_Barcode
Requires: pear-Image_Canvas
Requires: pear-Image_GIS
Requires: pear-Image_Graph
Requires: pear-Image_GraphViz
Requires: pear-Image_IPTC
Requires: pear-Image_Remote
Requires: pear-MDB
Requires: pear-MDB2_Driver_ibase
Requires: pear-MDB2_Driver_mssql
Requires: pear-MDB2_Driver_mysql
Requires: pear-MDB2_Driver_mysqli
Requires: pear-MDB2_Driver_oci8
Requires: pear-MDB2_Driver_pgsql
Requires: pear-MDB2_Driver_sqlite
Requires: pear-MDB_QueryTool
Requires: pear-Mail_Queue
Requires: pear-Mail_mimeDecode
Requires: pear-Math_Basex
Requires: pear-Math_Combinatorics
Requires: pear-Math_Fibonacci
Requires: pear-Math_Finance
Requires: pear-Math_Matrix
Requires: pear-Math_RPN
Requires: pear-Math_Stats
Requires: pear-Math_TrigOp
Requires: pear-Net_Curl
Requires: pear-Net_DNSBL
Requires: pear-Net_Dict
Requires: pear-Net_Dig
Requires: pear-Net_FTP
Requires: pear-Net_Finger
Requires: pear-Net_Geo
Requires: pear-Net_IMAP
Requires: pear-Net_IPv4
Requires: pear-Net_IPv6
Requires: pear-Net_Ident
Requires: pear-Net_LDAP
Requires: pear-Net_LMTP
Requires: pear-Net_MPD
Requires: pear-Net_NNTP
Requires: pear-Net_POP3
Requires: pear-Net_Ping
Requires: pear-Net_Portscan
Requires: pear-Net_SMTP
Requires: pear-Net_Server
Requires: pear-Net_Sieve
Requires: pear-Net_SmartIRC
Requires: pear-Net_Traceroute
Requires: pear-Net_UserAgent_Detect
Requires: pear-Net_Whois
Requires: pear-Net_Wifi
Requires: pear-Numbers_Roman
Requires: pear-Numbers_Words
Requires: pear-PEAR_Command_Packaging
Requires: pear-PEAR_Info
Requires: pear-PEAR_PackageFileManager
Requires: pear-PHP_CodeSniffer
Requires: pear-PHP_Debug
Requires: pear-PHP_DocBlockGenerator
Requires: pear-PHP_FunctionCallTracer
Requires: pear-PhpDocumentor
Requires: pear-QA_Peardoc_Coverage
Requires: pear-SOAP
Requires: pear-Science_Chemistry
Requires: pear-Services_Weather
Requires: pear-Stream_SHM
Requires: pear-Stream_Var
Requires: pear-System_Folders
Requires: pear-System_Mount
Requires: pear-Text_CAPTCHA_Numeral
Requires: pear-Text_Figlet
Requires: pear-Text_Password
Requires: pear-Text_Statistics
Requires: pear-Text_Wiki_Creole
Requires: pear-Translation
Requires: pear-Validate
Requires: pear-Var_Dump
Requires: pear-XML_Beautifier
Requires: pear-XML_FastCreate
Requires: pear-XML_Feed_Parser
Requires: pear-XML_HTMLSax
Requires: pear-XML_HTMLSax3
Requires: pear-XML_NITF
Requires: pear-XML_Query2XML
Requires: pear-XML_RPC
Requires: pear-XML_RPC2
Requires: pear-XML_RSS
Requires: pear-XML_Wddx
Requires: pear-XML_XPath
Requires: pear-XML_fo2pdf
Requires: pear-XML_image2svg

%description
%summary

%files

%changelog
* Sun May 06 2012 Denis Smirnov <mithraen@altlinux.ru> 4.0.1-alt1
- initial build for ALT Linux Sisyphus

