%define target_lua_version 5.4

# Original package name binaryheap
%define oname binaryheap
%define oversion 0.4-1
%define rockspec binaryheap-0.4-1.rockspec
Name: lua%target_lua_version-module-%oname
Version: 0.4
Release: alt1_lr1
Summary: Binary heap implementation in pure Lua
License: MIT
Group: Development/Other
Url: https://github.com/Tieske/binaryheap.lua

# These Obsoletes/Provides only necessary when previous (out-of-poicy) versions exist in repo
%if "%target_lua_version" == "5.4"
Obsoletes: lua-module-%oname < %EVR
Provides: lua-module-%oname = %version
%else
Obsoletes: lua5-%oname < %EVR
Provides: lua5-%oname = %version
%endif

Source: https://github.com/Tieske/binaryheap.lua/archive/version_0v4.tar.gz#/binaryheap.lua-version_0v4.tar.gz
Source1: https://luarocks.org/manifests/luarocks/binaryheap-0.4-1.rockspec

BuildPreReq: rpm-macros-lua >= 1.5.2 rpm-build-lua
# Automatically added by buildreq on ...
BuildRequires: lua%target_lua_version-luarocks

BuildArch: noarch
BuildRequires: lua5.3-luarocks lua5.1-luarocks

%description
      Binary heaps are an efficient sorting algorithm. This module
      implements a plain binary heap (without reverse lookup) and a
      'unique' binary heap (with unique payloads and reverse lookup).

%package -n lua5.3-module-%oname
Summary: Binary heap implementation in pure Lua
Group: Development/Other
%description -n lua5.3-module-%oname
      Binary heaps are an efficient sorting algorithm. This module
      implements a plain binary heap (without reverse lookup) and a
      'unique' binary heap (with unique payloads and reverse lookup).
%package -n lua5.1-module-%oname
Summary: Binary heap implementation in pure Lua
Group: Development/Other
%description -n lua5.1-module-%oname
      Binary heaps are an efficient sorting algorithm. This module
      implements a plain binary heap (without reverse lookup) and a
      'unique' binary heap (with unique payloads and reverse lookup).

%prep
%setup -n %oname.lua-version_0v4

%install
%luarocks_make %SOURCE1
%luarocks_move_docs doc

%check
%lua_path_add_buildroot
[ -x /usr/bin/busted ] || exit 0
busted

%add_findreq_skiplist %luarocks_dbdir_prefix-*/%oname/*/{doc,docs,etc,examples,samples,spec,test}/*

%files
%lua54_modulesdir_noarch/*
%luarocks_dbdir_prefix-%target_lua_version/%oname
%doc docs examples spec docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-%target_lua_version/manifest

%files -n lua5.3-module-%oname
%lua53_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.3/%oname
%doc docs examples spec docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.3/manifest

%files -n lua5.1-module-%oname
%lua51_modulesdir_noarch/*
%luarocks_dbdir_prefix-5.1/%oname
%doc docs examples spec docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-5.1/manifest

%changelog
* Sun Feb 11 2024 Ildar Mulyukov <ildar@altlinux.ru> 0.4-alt1_lr1
- autogenerated by lrimport

* Sun Mar 29 2020 Alexey Shabalin <shaba@altlinux.org> 0.4-alt1
- Initial build.
