# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-log-activity
Version: 23
Release: alt1.1
Summary: Log activity for Sugar
License: GPL
Group: Graphical desktop/Sugar
Url: http://sugarlabs.org/
Packager: Sugar Development Team <sugar@packages.altlinux.org>
BuildArch: noarch

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Log/Log-23.tar.bz2

Requires: gnome-vfs  
Requires: python-module-pygnome-gnome-vfs  
Requires: sugar-toolkit >= 0.88.0

BuildPreReq: gettext  
BuildPreReq: sugar-toolkit >= 0.88.0

%description
Log is an activity for developers to examine the log files that are generated
by system software and other activities. Logs can also be uploaded to servers
to allow support staff to assist with troubleshooting.

%prep
%setup -v -n Log-23


%build

rm -f MANIFEST
python setup.py build

%install
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.Log

%files -f org.laptop.Log.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc COPYING NEWS

%changelog
* Fri Oct 28 2011 Vitaly Kuznetsov <vitty@altlinux.ru> 23-alt1.1
- Rebuild with Python-2.7

* Wed Apr 07 2010 Aleksey Lim <alsroot@altlinux.org> 23-alt1
- Sucrose 0.88.0 release

* Thu Dec 03 2009 Eugeny A. Rostovtsev (REAL) <real at altlinux.org> 18-alt1.1
- Rebuilt with python 2.6

* Tue Apr 28 2009 Aleksey Lim <alsroot@altlinux.org> 18-alt1
- new Sucrose 0.84.2 release

* Tue Mar 17 2009 Aleksey Lim <alsroot@altlinux.org> 17-alt1
- new Sucrose 0.84.0 release

* Tue Dec 23 2008 Aleksey Lim <alsroot@altlinux.org> 16-alt2
- add direct gnome-vfs dependency

* Sat Dec 13 2008 Aleksey Lim <alsroot@altlinux.org> 16-alt1
- Sugar 0.84 release cycle

* Sun Nov 23 2008 Aleksey Lim <alsroot@altlinux.org> 14-alt2
- change group tag to "Graphical desktop/Sugar"

* Tue Nov 18 2008 Aleksey Lim <alsroot@altlinux.org> 14-alt1
- first build for ALT Linux Sisyphus
