%def_disable snapshot

%define _name Graphs
%define pypi_name graphs
%define ver_major 2.0
%define api_ver 1
%define rdn_name se.sjoerd.%_name

%def_enable check

Name: graphs
Version: %ver_major.5
Release: alt1

Summary: Plot and manipulate data with Graphs
License: GPL-3.0-or-later
Group: Graphical desktop/GNOME
Url: https://github.com/Sjoerd1993/Graphs

Vcs: https://github.com/Sjoerd1993/Graphs.git

%if_disabled snapshot
Source: %url/archive/v%version/%name-%version.tar.gz
%else
Source: %name-%version.tar
%endif

%define adwaita_ver 1.8

Requires: lib%name = %EVR
Requires: python3-module-pygobject3
Requires: dconf yelp

BuildRequires(pre): rpm-macros-meson rpm-build-python3 rpm-build-gir rpm-build-vala
BuildRequires: meson vala-tools blueprint-compiler /usr/bin/g-ir-compiler
BuildRequires: yelp-tools
BuildRequires: pkgconfig(libadwaita-1) >= %adwaita_ver gir(Adw) = 1
BuildRequires: pkgconfig(gee-0.8)
BuildRequires: pkgconfig(sqlite3)
BuildRequires: python3(numpy) python3(scipy)
BuildRequires: python3(PIL) python3(matplotlib)
BuildRequires: python3(sympy) python3(gio_pyio)
BuildRequires: python3(numexpr)
BuildRequires: gir(Gee) = 0.8
%{?_enable_check:BuildRequires: /usr/bin/appstreamcli desktop-file-utils}
# TODO: python tests
#BuildRequires: python3(pytest) typelib(Adw) = 1}

%description
Graphs is a simple, yet powerful tool that allows you to plot and
manipulate your data with ease. New data can be imported from a wide
variety of filetypes, or generated by equation. All data can be
manipulated using a variety of operations.

%package -n lib%name
Summary: %_name shared library
Group: System/Libraries

%description -n lib%name
This package contains shared library needed %_name to work.

%prep
%setup -n %{?_disable_snapshot:%_name}%{?_enable_snapshot:%name}-%version
sed -i "s/'pytest'/'py.test3'/" tests/meson.build
%python3_fix_shebang data/generate_gresource.py

%build
%meson -Dbuildtype=release
%meson_build

%install
%meson_install
%find_lang --with-gnome --output=%name.lang %name
# this and lines below is a quick hack to fix 'install_subdir' with newer meson
rm -rf %buildroot%_topdir

%check
install -pD tests/* -t %__builddir/run_tests/
export LD_LIBRARY_PATH=%buildroot/%_libdir
export GI_TYPELIB_PATH=%buildroot/%_typelibdir
export PYTHONPATH=%buildroot%python3_sitelibdir_noarch
%__meson_test

%files -f %name.lang
%_bindir/%name
%python3_sitelibdir_noarch/%pypi_name
%_desktopdir/%rdn_name.desktop
%_datadir/dbus-1/services/%rdn_name.service
%_datadir/glib-2.0/schemas/%rdn_name.gschema.xml
%_iconsdir/hicolor/*/apps/%{rdn_name}*.svg
%_datadir/metainfo/%rdn_name.metainfo.xml
%_datadir/mime/packages/%rdn_name.mime.xml
%_man1dir/%name.1*
%doc README*

%files -n lib%name
%_libdir/lib%name.so
%_typelibdir/%_name-%api_ver.typelib

%changelog
* Sat Jun 27 2026 Yuri N. Sedunov <aris@altlinux.org> 2.0.5-alt1
- 2.0.5

* Thu Jun 25 2026 Yuri N. Sedunov <aris@altlinux.org> 2.0.4-alt1
- 2.0.4

* Tue Jun 16 2026 Yuri N. Sedunov <aris@altlinux.org> 2.0.3-alt1
- 2.0.3

* Fri May 22 2026 Yuri N. Sedunov <aris@altlinux.org> 2.0.2-alt1
- 2.0.2

* Tue May 19 2026 Yuri N. Sedunov <aris@altlinux.org> 2.0.1-alt1
- 2.0.1

* Sat May 16 2026 Yuri N. Sedunov <aris@altlinux.org> 2.0.0-alt1
- 2.0.0

* Mon Mar 30 2026 Yuri N. Sedunov <aris@altlinux.org> 1.8.8-alt1
- 1.8.8

* Tue Jan 06 2026 Yuri N. Sedunov <aris@altlinux.org> 1.8.7-alt1
- 1.8.7

* Wed Dec 03 2025 Yuri N. Sedunov <aris@altlinux.org> 1.8.6-alt1
- 1.8.6

* Wed Jul 30 2025 Yuri N. Sedunov <aris@altlinux.org> 1.8.5-alt1
- 1.8.5

* Wed Jan 29 2025 Yuri N. Sedunov <aris@altlinux.org> 1.8.4-alt1
- 1.8.4

* Mon Nov 11 2024 Yuri N. Sedunov <aris@altlinux.org> 1.8.3-alt1
- 1.8.3

* Thu Aug 15 2024 Yuri N. Sedunov <aris@altlinux.org> 1.8.2-alt1
- 1.8.2

* Wed Jun 19 2024 Yuri N. Sedunov <aris@altlinux.org> 1.8.1-alt1
- 1.8.1

* Tue Apr 23 2024 Yuri N. Sedunov <aris@altlinux.org> 1.8.0-alt1
- 1.8.0

* Tue Feb 06 2024 Yuri N. Sedunov <aris@altlinux.org> 1.7.2-alt1
- updated to v1.7.2-2-g975ae74

* Mon Jan 15 2024 Yuri N. Sedunov <aris@altlinux.org> 1.7.1-alt1
- first build for Sisyphus (v1.7.1-8-g11b2692)


