#
#   - Data::Diver -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   (ALT Linux revision)
#   The following arguments were used:
#       .
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Data-Diver
%define m_distro Data-Diver
%define m_name Data::Diver
%define m_author_id unknown
%define _enable_test 1

Name: perl-Data-Diver
Version: 1.0101
Release: alt1

Summary: Simple, ad-hoc access to elements of deeply nested structures

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Kirill Maslinsky <kirill@altlinux.org>

BuildArch: noarch
Source: %m_distro-%version.tar
BuildRequires: perl-Module-Build

%description
Note that Data::Diver does `use strict;' and so will not use symbolic
references.  That is, a simple string can never be used as a reference.

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Data/*

%changelog
* Thu Jan 24 2013 Kirill Maslinsky <kirill@altlinux.org> 1.0101-alt1
- initial build for ALT Linux Sisyphus

