#
#   - DBIx::DBSchema -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       DBIx::DBSchema
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module DBIx-DBSchema
%define m_distro DBIx-DBSchema
%define m_name DBIx::DBSchema
%define m_author_id unknown
%define _enable_test 1

Name: perl-DBIx-DBSchema
Version: 0.39
Release: alt1.1

Summary: Database-independent schema objects

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/I/IV/IVAN/DBIx-DBSchema-0.39.tar.gz

# Automatically added by buildreq on Sat Sep 24 2005
BuildRequires: perl-DBD-Pg perl-DBI perl-FreezeThaw perl-Log-Agent perl-Storable perl-devel

%description
DBIx::DBSchema objects are collections of DBIx::DBSchema::Table objects and
represent a database schema.

This module implements an OO-interface to database schemas.  Using this module,
you can create a database schema with an OO Perl interface.  You can read the
schema from an existing database.  You can save the schema to disk and restore
it a different process.  Most importantly, DBIx::DBSchema can write SQL
CREATE statements statements for different databases from a single source.

Currently supported databases are MySQL and PostgreSQL.  Sybase support is
partially implemented.  DBIx::DBSchema will attempt to use generic SQL syntax
for other databases.  Assistance adding support for other databases is
welcomed.  See DBIx::DBSchema::DBD, "Driver Writer's Guide and Base Class".

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc Changes README 
%perl_vendor_privlib/DBIx/

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.39-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Fri Jul 16 2010 Igor Vlasenko <viy@altlinux.ru> 0.39-alt1
- automated CPAN update

* Sat Sep 06 2008 Vitaly Lipatov <lav@altlinux.ru> 0.27-alt2
- fix directory ownership violation

* Sat Sep 24 2005 Vitaly Lipatov <lav@altlinux.ru> 0.27-alt1
- first build for ALT Linux Sisyphus

