#
#   - Math::Base85 -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Math::Base85
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Math-Base85
%define m_distro Math-Base85
%define m_name Math::Base85
%define m_author_id unknown
%define _enable_test 1

Name: perl-Math-Base85
Version: 0.2
Release: alt1

Summary: Perl extension for base 85 numbers, as referenced by RFC 1924

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Denis Smirnov <mithraen@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/T/TM/TMONROE/%m_distro-%version.tar.gz

# Automatically added by buildreq on Sat Nov 07 2009
BuildRequires: perl-Math-BigInt perl-devel

%description
RFC 1924 describes a compact, fixed-size representation of IPv6
addresses which uses a base 85 number system.  This module handles
some of the uglier details of it.

The base 85 numbers (from 0 to 84) are as follows:

    0..9 A..Z a..z ! # $ %% & ( ) * + - ; < = > ? @ ^ _ ` { | } ~

At the moment, there's not much in this module.  But it should be
sufficient for the purposes of RFC 1924.

This module has a variable called $Math::Base85::base85_digits,
which is a string containing the digits of the base 85 alphabet
from lowest (0) to highest (~), in that order.

Additionally, the following two functions are defined for general
use.  (They will be exported upon request.)

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%perl_vendor_privlib/Math/*

%changelog
* Sat Nov 07 2009 Denis Smirnov <mithraen@altlinux.ru> 0.2-alt1
- initial build for ALT Linux Sisyphus

