%define  modulename sphinxcontrib-log-cabinet

Name:    python3-module-%modulename
Version: 1.0.1
Release: alt1

Summary: Organize changelog directives in Sphinx docs.
License: BSD-3-Clause
Group:   Development/Python3
URL:     https://github.com/davidism/sphinxcontrib-log-cabinet

Packager: Andrey Cherepanov <cas@altlinux.org>

BuildRequires(pre): rpm-build-python3
BuildRequires: python3-dev python3-module-setuptools

BuildArch: noarch

Source:  %modulename-%version.tar

%description
Organize changelogs generated by versionadded, versionchanged,
deprecated directives. The log will be sorted by newest to oldest
version. For HTML docs, older versions will be collapsed by default.

%prep
%setup -n %modulename-%version

%build
%python3_build

%install
%python3_install

%files
%doc README.rst
%python3_sitelibdir/sphinxcontrib/*
%python3_sitelibdir/*.pth
%python3_sitelibdir/*.egg-info

%changelog
* Sun Apr 26 2020 Andrey Cherepanov <cas@altlinux.org> 1.0.1-alt1
- Initial build for Sisyphus
