# BEGIN SourceDeps(oneline):
BuildRequires: unzip
# END SourceDeps(oneline)
BuildRequires: /proc
BuildRequires: jpackage-compat
Name:           cobertura-maven-plugin
Version:        2.5.2
Release:        alt1_3jpp7
Summary:        Plugin providing the features of Cobertura within Maven

Group:          Development/Java
# the project is under ASL 2.0 license
# javascript files in src/site/resources/sample-maven-shared-io-report/js/
# are under GPLv2 and GPLv2+
License:        ASL 2.0 and GPLv2 and GPLv2+
URL:            http://mojo.codehaus.org/cobertura-maven-plugin/
Source0:        http://repo2.maven.org/maven2/org/codehaus/mojo/%{name}/%{version}/%{name}-%{version}-source-release.zip
Source1:        http://www.apache.org/licenses/LICENSE-2.0.txt
BuildArch:      noarch

BuildRequires:  maven-local
BuildRequires:  jpackage-utils
BuildRequires:  maven-plugin-plugin
BuildRequires:  maven-resources-plugin
BuildRequires:  maven-compiler-plugin
BuildRequires:  maven-invoker-plugin
BuildRequires:  maven-javadoc-plugin
BuildRequires:  gnu-getopt >= 0:1.0.13
BuildRequires:  cobertura
BuildRequires:  mojo-parent

Provides:       maven-plugin-cobertura = %{version}-%{release}
Obsoletes:      maven-plugin-cobertura < 2.5.2-1
Source44: import.info

%description
This plugin provides the features of Cobertura within the Maven 2 & 3
environment. The report generated by this plugin is the result of executing
the Cobertura tool against your compiled classes to help you determine
how well the unit testing efforts have been, and can then be used to identify
which parts of your Java program are lacking test coverage.

%package        javadoc
Summary:        Javadoc for %{name}
Group:          Development/Java
BuildArch: noarch

%description    javadoc
This package contains the API documentation for %{name}.

%prep
%setup -q -n %{name}-%{version}
cp %{SOURCE1} LICENSE

# we don't have this extension
%pom_xpath_remove "pom:extension[pom:artifactId[text()='wagon-webdav-jackrabbit']]"

# remove bundled .class files
find . -name *.class -delete

%build
# tests are disabled because of missing dependencies
%mvn_build -f

%install
%mvn_install

%files -f .mfiles
%doc LICENSE

%files javadoc -f .mfiles-javadoc
%doc LICENSE

%changelog
* Tue Aug 26 2014 Igor Vlasenko <viy@altlinux.ru> 2.5.2-alt1_3jpp7
- new release

