# bun build --compile appends its payload past everything the ELF headers
# describe; eu-strip rewrites the file and drops the payload, and the result
# aborts at startup. So there is no debuginfo package and rpm must not strip.
%global __strip /bin/true

# Node's names for the platform, not RPM's: the build target is derived from
# them and the dist directory is named after them.
%ifarch x86_64
%global node_arch x64
%endif
%ifarch aarch64
%global node_arch arm64
%endif

# ALT rpm does not define the AppStream metainfo directory.
%global _metainfodir %_datadir/metainfo

Name: opencode
Version: 1.18.35
Release: alt1

# bun build --compile output carries no DWARF and breaks under eu-strip (see
# %%__strip at the top), so the binary is deliberately without debuginfo: keep
# find-debuginfo off it (this also silences the brp "stripped ELF" warning).
%add_debuginfo_skiplist %_bindir/%name
# The desktop app directory embeds a prebuilt Node-API pty module; there is no
# debuginfo for it either, and find-debuginfo must not walk the directory.
%add_debuginfo_skiplist %_libexecdir/%name-desktop

Summary: AI coding agent for the terminal
License: MIT
Group: Development/Other
Url: https://%name.ai
Vcs: https://github.com/anomalyco/%name
Packager: Nazarov Denis <nenderus@altlinux.org>

# https://github.com/anomalyco/%name/archive/v%version/%name-%version.tar.gz
Source: %name-%version.tar
# The npm dependency tree, committed unpacked. Both the CLI (bun build
# --compile) and the desktop client (electron-vite) need it on disk and it
# cannot be built from a plain release tarball; see opencode_vendor.
Source1: %name-vendor-%version.tar
# Snapshot of the models.dev catalogue, which the build otherwise fetches.
Source2: models.dev-api-%version.json
# The tree-sitter grammars the highlighter would otherwise download at run
# time, and the patch that points the parser table at them.
Source3: %name-tree-sitter-%version.tar
Source4: %{name}_grammars
Source5: %{name}_vendor
# Upstream's build script fails unless bun satisfies a caret range around the
# version it pins. The range is satisfied by the distribution bun, so the patch
# is inert today; kept because both versions float and a major bump on either
# side would otherwise stop the build over upstream's convenience.
Patch0: %name-relax-bun-version.patch
# Stop the binary fetching and executing code over the network at run time.
# Each patch header says what it stops and which environment variable restores
# upstream behaviour.
Patch1: %name-no-self-update.patch
Patch2: %name-no-runtime-npm-install.patch
# Point the highlighter's parser table at the vendored grammars instead of
# GitHub URLs (generated by opencode_grammars).
Patch3: %name-local-grammars.patch
# Desktop client: resolve the window icon against the app directory instead
# of process.resourcesPath, which the system electron points into its own
# distribution when handed an app directory.
Patch4: %name-desktop-local-icons.patch
# Desktop client: never download and install upstream releases over itself.
Patch5: %name-desktop-no-updater.patch
# Desktop client: bundle the production dependencies into the main chunk
# instead of shipping a node_modules tree next to the app.
Patch6: %name-desktop-bundle-deps.patch

BuildRequires: bun
# Bun's shell resolves its own executable through /proc; without this the
# hasher build root gets a stub /proc and that fails.
BuildRequires: /proc
# The desktop build feeds the source tree into a git index so the Tailwind
# scanner sees every file (see the comment in the %%build section).
BuildRequires: git-core
# Upstream supports x86_64 and aarch64 only.
ExclusiveArch: x86_64 aarch64
Requires: %name-common = %EVR

%description
%name is an AI coding agent that runs in the terminal. It works with a
range of model providers, reads and edits files in a project, runs commands,
and keeps a session history.

This package is the command line client; the desktop client is packaged
separately as %name-desktop. It does not update itself, install npm packages
into your home directory, or download syntax highlighting grammars from
GitHub.

%package common
Summary: Shared data for the %name CLI and desktop client
Group: Development/Other
BuildArch: noarch
Requires: ripgrep
Requires: git-core

%description common
The tree-sitter grammars used for syntax highlighting, shared by the %name
terminal client and by %name-desktop, which embeds the same server code, plus
the command line tools both shell out to.

%package desktop
Summary: Desktop client for %name, the AI coding agent
Group: Development/Other
Requires: %name-common = %EVR
# The app runs on the distribution electron. Upstream pins 42.x; the prebuilt
# native module it embeds is ABI-agnostic (Node-API), so any 42+ will do.
Requires: electron >= 42

%description desktop
%name-desktop is the Electron desktop client of %name. The opencode server
is embedded into the application, so the client runs without the terminal
package installed; %name-common supplies the syntax highlighting grammars and
the command line tools the server shells out to.

The client does not update itself: updates arrive with the package.

%prep
# Source1 (the committed dependency tree: node_modules and the per-workspace
# symlink farms) and Source3 (the vendored grammars) are laid over the source.
%setup -a 1 -a 3
%patch0 -p1
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

# This bunfig only configures `bun test`/dev preloads; bun 1.4.2 crashes
# loading it, and the build does not need it.
%__rm -f packages/%name/bunfig.toml

%build
export HOME="$PWD/.home"
export BUN_INSTALL_CACHE_DIR="$PWD/.bun-cache"
export TMPDIR="$PWD/.tmp"
%__mkdir_p "$HOME" "$BUN_INSTALL_CACHE_DIR" "$TMPDIR"
# Everything the build would otherwise reach the network for.
export MODELS_DEV_API_JSON="%SOURCE2"
export OPENCODE_VERSION="%version"
export OPENCODE_CHANNEL=latest

cd packages/%name
# --single builds only the host platform; --skip-embed-web-ui leaves out the
# browser interface; --skip-install uses the committed dependency tree.
bun ./script/build.ts --single --skip-install --skip-embed-web-ui
cd ../..

#
# Desktop client.
#

# The Tailwind v4 scanner enumerates source files through the git index when
# a .git is present and falls back to a traversal that misses part of the
# renderer's utility classes otherwise (with the 1.18.34 tree the gap was
# about a quarter of the classes). A released tarball has no .git, so feed
# the scanner one.
export OPENCODE_CHANNEL=prod
git init -q
git add -A

cd packages/desktop
# prebuild.ts copies the prod icons and the AppStream metainfo into
# resources/ and builds the embedded server (../opencode/dist/node).
bun ./scripts/prebuild.ts
# Run electron-vite directly: `bun run build` would execute the prebuild
# script a second time, and the .bin wrapper shebangs want node, which this
# build root does not carry.
bun ./node_modules/electron-vite/bin/electron-vite.js build
cd ../..

%install
# CLI.
%__install -Dpm 0755 packages/%name/dist/%name-linux-%node_arch/bin/%name \
    %buildroot%_bindir/%name

# Shared data.
%__mkdir_p %buildroot%_datadir/%name
%__cp -a tree-sitter %buildroot%_datadir/%name/tree-sitter

# Desktop client: assemble the app directory electron-builder would produce,
# without electron-builder. Only out/, the runtime icons and the one
# dependency the main bundle leaves externalised are needed at run time;
# everything else is bundled into out/.
appdir=%buildroot%_libexecdir/%name-desktop
%__mkdir_p "$appdir/resources" "$appdir/node_modules/@lydell"
%__cp -a packages/desktop/out "$appdir/out"
%__cp -a packages/desktop/resources/icons "$appdir/resources/icons"
# The icons directory carries sets for every platform (android/, ios/,
# Windows store tiles); nothing on Linux reaches them.
%__rm -rf "$appdir/resources/icons/android" "$appdir/resources/icons/ios"
%__rm -f "$appdir"/resources/icons/Square*.png "$appdir/resources/icons/StoreLogo.png"
%__cp -aL "packages/desktop/node_modules/@lydell/node-pty-linux-%node_arch" \
    "$appdir/node_modules/@lydell/"
# Rollup cannot inline CommonJS requires emitted at run time from inside the
# bundled dependencies: the electron-store -> conf -> ajv chain requires ajv's
# runtime subpaths and ajv-formats, and js-yaml optionally requires esprima.
# Dereferenced copies next to the bundle keep those requires working.
# (@aws-sdk/signature-v4-crt also shows up in that list, but only inside an
# error message string; the aws sdk guards the real one with try/catch.)
for p in ajv ajv-formats esprima; do
    %__cp -aL node_modules/.bun/$p@*/node_modules/$p "$appdir/node_modules/"
done
# electron-builder would generate this from its config. The desktopName key
# is what Electron uses as the Wayland app_id (with the .desktop suffix
# stripped).
cat > "$appdir/package.json" <<EOF
{
  "name": "%name-desktop",
  "productName": "OpenCode",
  "version": "%version",
  "main": "./out/main/index.js",
  "desktopName": "%name-desktop.desktop"
}
EOF
# npm trees occasionally carry world-writable bits.
%__chmod -R go-w "$appdir"

# Launcher. ELECTRON_FORCE_IS_PACKAGED: a system electron started with an app
# directory argument treats it as an unpackaged "default app", and the app
# would then pick its dev appId and user-data paths.
%__install -Dpm 0755 /dev/stdin %buildroot%_bindir/%name-desktop <<EOF
#!/bin/sh
ELECTRON_FORCE_IS_PACKAGED=1 exec %_bindir/electron %_libexecdir/%name-desktop "\$@"
EOF

# Desktop entry. StartupWMClass=OpenCode matches the X11 WM_CLASS that
# electron derives from app.name; on Wayland the app_id comes from the
# desktopName key in the package.json above.
%__install -Dpm 0644 /dev/stdin \
    %buildroot%_datadir/applications/%name-desktop.desktop <<'EOF'
[Desktop Entry]
Type=Application
Name=OpenCode
GenericName=AI Coding Agent
Comment=Desktop client for the opencode AI coding agent
Exec=opencode-desktop %%U
Icon=opencode-desktop
Terminal=false
Categories=Development;IDE;
MimeType=x-scheme-handler/opencode;
StartupWMClass=OpenCode
EOF

# Icons for menus and app grids.
for pair in 32x32.png:32x32 64x64.png:64x64 128x128.png:128x128 '128x128@2x.png:256x256' icon.png:512x512; do
    %__install -Dpm 0644 "packages/desktop/resources/icons/${pair%%:*}" \
        "%buildroot%_datadir/icons/hicolor/${pair##*:}/apps/%name-desktop.png"
done

# AppStream metadata, generated by prebuild.ts for the prod appId.
%__install -Dpm 0644 packages/desktop/resources/ai.opencode.desktop.metainfo.xml \
    %buildroot%_metainfodir/ai.opencode.desktop.metainfo.xml

%check
%buildroot%_bindir/%name --version
test "$(%buildroot%_bindir/%name --version)" = "%version"
test -d %buildroot%_datadir/%name/tree-sitter

test -x %buildroot%_bindir/%name-desktop
test -f %buildroot%_libexecdir/%name-desktop/out/main/index.js
test -f %buildroot%_libexecdir/%name-desktop/out/preload/index.js
test -f %buildroot%_libexecdir/%name-desktop/out/renderer/index.html
test -f %buildroot%_libexecdir/%name-desktop/node_modules/@lydell/node-pty-linux-%node_arch/prebuilds/linux-%node_arch/pty.node
for p in ajv ajv-formats esprima; do
    test -f %buildroot%_libexecdir/%name-desktop/node_modules/$p/package.json
done
grep -q '"desktopName": "%name-desktop.desktop"' \
    %buildroot%_libexecdir/%name-desktop/package.json

%files
%doc LICENSE README*.md CONTEXT.md CONTRIBUTING.md SECURITY.md STATS.md
%_bindir/%name

%files common
%dir %_datadir/%name
%_datadir/%name/tree-sitter

%files desktop
%_bindir/%name-desktop
%_libexecdir/%name-desktop
%_datadir/applications/%name-desktop.desktop
%_datadir/icons/hicolor/*/apps/%name-desktop.png
%_metainfodir/ai.opencode.desktop.metainfo.xml

%changelog
* Wed Oct 07 2026 Nazarov Denis <nenderus@altlinux.org> 1.18.35-alt1
- Update to 1.18.35

* Mon Oct 05 2026 Nazarov Denis <nenderus@altlinux.org> 1.18.34-alt2
- Add opencode-desktop subpackage built from the same sources; split the
  shared tree-sitter grammars and tools into opencode-common

* Thu Oct 01 2026 Nazarov Denis <nenderus@altlinux.org> 1.18.34-alt1
- Update to 1.18.34

* Mon Sep 28 2026 Nazarov Denis <nenderus@altlinux.org> 1.18.33-alt1
- Update to 1.18.33

* Thu Sep 24 2026 Nazarov Denis <nenderus@altlinux.org> 1.18.32-alt1
- Initial build
