# bun build --compile appends its payload past everything the ELF headers
# describe; eu-strip rewrites the file and drops the payload, and the result
# aborts at startup. So there is no debuginfo package and rpm must not strip.
%global __strip /bin/true

# Node's names for the platform, not RPM's: the build target is derived from
# them and the dist directory is named after them.
%ifarch x86_64
%global node_arch x64
%endif
%ifarch aarch64
%global node_arch arm64
%endif

Name: opencode
Version: 1.18.32
Release: alt1

# bun build --compile output carries no DWARF and breaks under eu-strip (see
# %%__strip at the top), so the binary is deliberately without debuginfo: keep
# find-debuginfo off it (this also silences the brp "stripped ELF" warning).
%add_debuginfo_skiplist %_bindir/%name

Summary: AI coding agent for the terminal
License: MIT
Group: Development/Other
Url: https://%name.ai
Vcs: https://github.com/anomalyco/%name
Packager: Nazarov Denis <nenderus@altlinux.org>

# https://github.com/anomalyco/%name/archive/v%version/%name-%version.tar.gz
Source: %name-%version.tar
# The npm dependency tree, committed unpacked. bun build --compile needs it on
# disk and it cannot be built from a plain release tarball; see opencode_vendor.
Source1: %name-vendor-%version.tar
# Snapshot of the models.dev catalogue, which the build otherwise fetches.
Source2: models.dev-api-%version.json
# The tree-sitter grammars the highlighter would otherwise download at run
# time, and the patch that points the parser table at them.
Source3: %name-tree-sitter-%version.tar
Source4: %{name}_grammars
Source5: %{name}_vendor
# Upstream's build script fails unless bun satisfies a caret range around the
# version it pins. The range is satisfied by the distribution bun, so the patch
# is inert today; kept because both versions float and a major bump on either
# side would otherwise stop the build over upstream's convenience.
Patch0: %name-relax-bun-version.patch
# Stop the binary fetching and executing code over the network at run time.
# Each patch header says what it stops and which environment variable restores
# upstream behaviour.
Patch1: %name-no-self-update.patch
Patch2: %name-no-runtime-npm-install.patch
# Point the highlighter's parser table at the vendored grammars instead of
# GitHub URLs (generated by opencode_grammars).
Patch3: %name-local-grammars.patch

BuildRequires: bun
# Bun's shell resolves its own executable through /proc; without this the
# hasher build root gets a stub /proc and that fails.
BuildRequires: /proc
# Upstream supports x86_64 and aarch64 only.
ExclusiveArch: x86_64 aarch64
# opencode shells out to ripgrep, and downloads its own if it is not on PATH.
Requires: ripgrep
Requires: git-core

%description
%name is an AI coding agent that runs in the terminal. It works with a
range of model providers, reads and edits files in a project, runs commands,
and keeps a session history.

This build is the command line client only; the optional web interface is not
included, and it does not update itself, install npm packages into your home
directory, or download syntax highlighting grammars from GitHub.

%prep
# Source1 (the committed dependency tree: node_modules and the per-workspace
# symlink farms) and Source3 (the vendored grammars) are laid over the source.
%setup -a 1 -a 3
%patch0 -p1
%patch1 -p1
%patch2 -p1
%patch3 -p1

# This bunfig only configures `bun test`/dev preloads; bun 1.4.2 crashes
# loading it, and the build does not need it.
%__rm -f packages/%name/bunfig.toml

%build
export HOME="$PWD/.home"
export BUN_INSTALL_CACHE_DIR="$PWD/.bun-cache"
export TMPDIR="$PWD/.tmp"
%__mkdir_p "$HOME" "$BUN_INSTALL_CACHE_DIR" "$TMPDIR"
# Everything the build would otherwise reach the network for.
export MODELS_DEV_API_JSON="%SOURCE2"
export OPENCODE_VERSION="%version"
export OPENCODE_CHANNEL=latest

cd packages/%name
# --single builds only the host platform; --skip-embed-web-ui leaves out the
# browser interface; --skip-install uses the committed dependency tree.
bun ./script/build.ts --single --skip-install --skip-embed-web-ui

%install
%__install -Dpm 0755 packages/%name/dist/%name-linux-%node_arch/bin/%name \
    %buildroot%_bindir/%name
%__mkdir_p %buildroot%_datadir/%name
%__cp -a tree-sitter %buildroot%_datadir/%name/tree-sitter

%check
%buildroot%_bindir/%name --version
test "$(%buildroot%_bindir/%name --version)" = "%version"
test -d %buildroot%_datadir/%name/tree-sitter

%files
%doc LICENSE README*.md CONTEXT.md CONTRIBUTING.md SECURITY.md STATS.md
%_bindir/%name
%_datadir/%name/tree-sitter

%changelog
* Thu Sep 24 2026 Nazarov Denis <nenderus@altlinux.org> 1.18.32-alt1
- Initial build
