Name:           puppetdb
Version:        4.4.0
Release:        alt1
Summary:        Centralized Puppet Storage

Group:          System/Servers 
License:        Apache-2.0
URL:            https://github.com/puppetlabs/puppetdb
Source0:        %name-%version.tar

#BuildRequires(pre): rpm-build-java
BuildRequires(pre): rpm-build-ruby
BuildRequires:  ruby-tool-setup
#BuildRequires:  java-devel >= 1.6.0
#BuildRequires:  /proc
BuildRequires:  ruby-facter

Requires:  puppet >= 4

BuildArch:      noarch
#Requires:       java >= 1.6.0
#Requires:       jpackage-utils

%description
PuppetDB is the fast, scalable, and reliable data warehouse for Puppet. It
caches data generated by Puppet, and gives you advanced features at awesome
speed with a powerful API.

%prep
%setup -n %name-%version

%install
prefix=%buildroot \
DESTDIR=%buildroot \
projconfdir=%_sysconfdir/%name \
rundir=%_runtimedir/%name \
bindir=%_libexecdir/%name/bin \
uxbindir=%_bindir \
symbindir=%_sbindir \
app_prefix=%_libexecdir/%name \
app_data=%_localstatedir/%name \
app_logdir=%_logdir \
system_config_dir=%_sysconfdir/%name \
FACTER_operatingsystem=RedHat \
FACTER_osfamily=RedHat \
FACTER_operatingsystemmajrelease=7 \
rubylibdir=%ruby_sitelibdir \
bash install.sh termini
#EZ_VERBOSE=1 \

%files
%ruby_sitelibdir/*
%_libexecdir/*

%changelog
* Mon May 22 2017 Gordeev Mikhail <obirvalger@altlinux.org> 4.4.0-alt1
- Initial build in Sisyphus
