%define app_data %_localstatedir/%name
%define app_logdir %_logdir/%name
%define projconfdir %_sysconfdir/%name
%define rundir %_runtimedir/%name

Name:           puppetdb
Version:        4.4.0
Release:        alt1
Summary:        Centralized Puppet Storage

Group:          System/Servers
License:        Apache-2.0
URL:            https://github.com/puppetlabs/puppetdb
Source0:        %name-%version.tar
Source1:        README.ALT


%filter_from_requires \!^/etc/default/puppetdb$!d

BuildRequires(pre): rpm-build-java
BuildRequires(pre): rpm-build-ruby
BuildRequires:  ruby-tool-setup
BuildRequires:  java-devel >= 1.6.0
BuildRequires:  /proc
BuildRequires:  ruby-facter

Requires:  puppet
#Requires:  puppet >= 4

BuildArch:      noarch
Requires:       java >= 1.6.0
#Requires:       jpackage-utils

%description
PuppetDB is the fast, scalable, and reliable data warehouse for Puppet. It
caches data generated by Puppet, and gives you advanced features at awesome
speed with a powerful API.

%prep
%setup -n %name-%version
cp %SOURCE1 .

%install
readonly DESTDIR=%buildroot; export DESTDIR
readonly FACTER_operatingsystem=RedHat; export FACTER_operatingsystem
readonly FACTER_operatingsystemmajrelease=7; export FACTER_operatingsystemmajrelease
readonly FACTER_osfamily=RedHat; export FACTER_osfamily
readonly app_data=%app_data; export app_data
readonly app_logdir=%app_logdir; export app_logdir
readonly app_prefix=%_libexecdir/%name; export app_prefix
readonly bindir=%_libexecdir/%name/bin; export bindir
readonly confdir=%_sysconfdir; export confdir
readonly prefix=%buildroot; export prefix
readonly projconfdir=%projconfdir; export projconfdir
readonly rubylibdir=%ruby_sitelibdir; export rubylibdir
readonly rundir=%rundir; export rundir
readonly symbindir=%_sbindir; export symbindir
readonly system_config_dir=%_sysconfdir/%name; export system_config_dir
readonly tmpfilesdir=%_tmpfilesdir; export tmpfilesdir
readonly unitdir=%_unitdir; export unitdir
readonly uxbindir=%_bindir; export uxbindir
#export EZ_VERBOSE=1
bash install.sh termini
bash install.sh install
bash install.sh logrotate
bash install.sh systemd_redhat

#make install-rpm-systemd

%pre
# Add puppetdb group
getent group puppetdb > /dev/null || \
    groupadd -r puppetdb || :
# Add or update puppetdb user
if getent passwd puppetdb > /dev/null; then
    usermod --gid puppetdb --home "%app_data" \
        --comment "puppetdb daemon" puppetdb || :
else
    useradd -r --gid puppetdb --home "%app_data" --shell $(which nologin) \
        --comment "puppetdb daemon"  puppetdb || :
fi

if rpm -q puppetdb | grep ^puppetdb-2.* > /dev/null && [ $1 -eq 2 ] ; then tar -czf /tmp/puppetdb-upgrade-config-files.tgz -C /etc/puppetdb/conf.d config.ini database.ini jetty.ini ; fi

%post
chown puppetdb:puppetdb %app_logdir
chmod 700 %app_logdir
chown puppetdb:puppetdb %app_data
chmod 770 %app_data
chown puppetdb:puppetdb %projconfdir
chmod 750 %projconfdir
chown puppetdb:puppetdb %rundir
chmod 0755 %rundir

%files
%doc README.ALT
%_bindir/%name
%_libexecdir/%name
%exclude %_libexecdir/%name/scripts/install.sh
%_logdir/%name
%_logrotatedir/%name
%_sbindir/%name
%_sysconfdir/%name/*
%_sysconfdir/sysconfig/%name
%_tmpfilesdir/%name.conf
%_unitdir/%name.service
%app_data
%ruby_sitelibdir/*
%rundir

%changelog
* Mon May 22 2017 Gordeev Mikhail <obirvalger@altlinux.org> 4.4.0-alt1
- Initial build in Sisyphus
