#
#   - Catalyst::Plugin::CRUD -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Catalyst::Plugin::CRUD
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Catalyst-Plugin-CRUD
%define m_distro Catalyst-Plugin-CRUD
%define m_name Catalyst::Plugin::CRUD
%define m_author_id BAYSIDE
%define _enable_test 1

Name: perl-Catalyst-Plugin-CRUD
Version: 0.21
Release: alt2.1

Summary: CRUD (create/read/update/delete) Plugin for Catalyst

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/Catalyst-Plugin-CRUD/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org/CPAN/authors/id/B/BA/BAYSIDE/%m_distro-%version.tar.gz

# Automatically added by buildreq on Mon Sep 08 2008 (-bi)
BuildRequires: perl-Class-Trigger perl-Encode-JP perl-Jcode perl-Test-Pod perl-Test-Pod-Coverage perl-XML-Simple

%description
This module provides CRUD (create/read/update/delete) action.

 create: insert new record
 read:   retrieve record
 update: update already record
 delete: delete record
 list:   retrieve all records

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Catalyst*
%doc README Changes sample/*

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.21-alt2.1
- repair after perl 5.12 upgrade using girar-nmu

* Mon Sep 08 2008 Michael Bochkaryov <misha@altlinux.ru> 0.21-alt2
- fix directory ownership violation

* Mon Jun 30 2008 Michael Bochkaryov <misha@altlinux.ru> 0.21-alt1
- first build for ALT Linux Sisyphus

