#FIXME: https://github.com/lunarmodules/luasec/issues/110
%define target_lua_version 5.3

# Original package name LuaSec
%define oname luasec
%define oversion 1.3.2-1
%define rockspec luasec-1.3.2-1.rockspec
Name: lua%target_lua_version-module-%oname
Version: 1.3.2
Release: alt1_lr1
Summary: A binding for OpenSSL library to provide TLS/SSL communication over LuaSocket.
License: MIT
Group: Development/Other
Url: https://github.com/brunoos/luasec/wiki

%if "%target_lua_version" == "5.4"
Obsoletes: lua-module-%oname < %EVR
Provides: lua-module-%oname = %version
%endif

Source: https://github.com/lunarmodules/luasec/archive/refs/tags/v1.3.2.tar.gz#/%oname-%version.tar.gz
Source1: https://luarocks.org/manifests/lunarmodules/luasec-1.3.2-1.rockspec

BuildPreReq: rpm-macros-lua >= 1.5.2 rpm-build-lua
BuildRequires: liblua%target_lua_version-devel lua%target_lua_version-luarocks
BuildRequires: luarocks%target_lua_version(luasocket) libssl-devel

%description
This version delegates to LuaSocket the TCP connection establishment between the client and server. Then LuaSec uses this connection to start a secure TLS/SSL session.

%prep
%setup -n %oname-%version

%install
%luarocks_make %SOURCE1
%luarocks_move_docs samples

%add_findreq_skiplist %luarocks_dbdir_prefix-*/%oname/*/{doc,docs,etc,examples,samples,spec,test}/*

%files
%lua_modulesdir/*
%lua_modulesdir_noarch/*
%luarocks_dbdir_prefix-%target_lua_version/%oname
%doc CHANGELOG* LICENSE* README* docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-%target_lua_version/manifest

%changelog
* Wed Apr 01 2026 Ildar Mulyukov <ildar@altlinux.ru> 1.3.2-alt1_lr1
- autogenerated by lrimport
- build with the bundled luasocket (see https://github.com/lunarmodules/luasec/issues/110)

* Tue Aug 30 2022 Vladimir D. Seleznev <vseleznv@altlinux.org> 1.2.0-alt1
- Updated to 1.2.0.

* Mon Jul 04 2022 Vladimir D. Seleznev <vseleznv@altlinux.org> 1.0.2-alt1
- Updated to 1.0.2.
- Built from tarball.

* Fri Jun 07 2019 Ildar Mulyukov <ildar@altlinux.ru> 0.8-alt1_lr1
- autogenerated by lrimport
- restuctured according to https://www.altlinux.org/Lua_Policy

* Wed Aug 29 2018 Grigory Ustinov <grenka@altlinux.org> 0.6-alt2.1
- NMU: Rebuild with new openssl 1.1.0.

* Thu Jul 13 2017 Aleksei Nikiforov <darktemplar@altlinux.org> 0.6-alt2
- Rebuild with new luarocks and lua-5.3

* Tue Nov 01 2016 Ildar Mulyukov <ildar@altlinux.ru> 0.6-alt1_lr1
- autogenerated by lrimport

