Packager: Michael Bochkaryov <misha@altlinux.ru>
#
#   - Regexp::Parser -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Regexp::Parser
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Regexp-Parser
%define m_distro Regexp-Parser
%define m_name Regexp::Parser
%define m_author_id PINYAN
%define _enable_test 1
%add_findreq_skiplist */Perl6/Rule*

Name: perl-Regexp-Parser
Version: 0.21
Release: alt1

Summary: base class for parsing regexes

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/Regexp-Parser/

BuildArch: noarch
Source: http://www.cpan.org/authors/id/T/TO/TODDR/Regexp-Parser-0.21.tar.gz

# Automatically added by buildreq on Sat Apr 26 2008
BuildRequires: perl-NEXT perl-devel perl-unicore

%description
This module parses regular expressions (regexes).  Its default "grammar"
is Perl 5.8.4's regex set.  Grammar is quoted because the module does
not so much define a grammar as let each matched node state what it
expects to match next, but there is not currently a way of extracting a
complete grammar.  This may change in future versions.

This module is designed as a replacement (though not drop-in) for my old
YAPE::Regex modules.

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/*
#%perl_vendor_man3dir/*
%exclude %perl_vendor_archlib

%changelog
* Mon Sep 19 2011 Igor Vlasenko <viy@altlinux.ru> 0.21-alt1
- automated CPAN update

* Mon Oct 06 2008 Igor Vlasenko <viy@altlinux.ru> 0.20-alt1.1
- NMU for unknown reason:
  the person above was too neglectant to add --changelog "- NMU: <reason>" option.

* Sat Apr 26 2008 Michael Bochkaryov <misha@altlinux.ru> 0.20-alt1
- first build for ALT Linux Sisyphus

