%define _unpackaged_files_terminate_build 1
%define dist PPIx-Regexp
Name: perl-PPIx-Regexp
Version: 0.055
Release: alt1

Summary: Represent a regular expression of some sort
License: Perl
Group: Development/Perl

Url: %CPAN %dist
Source0: http://www.cpan.org/authors/id/W/WY/WYANT/%{dist}-%{version}.tar.gz

BuildRequires: perl-Task-Weaken perl-Readonly perl-PPI perl-Module-Build perl-List-MoreUtils perl-Params-Util
BuildArch: noarch

%description
This package parses regular expressions as they appear in Perl scripts,
generating a structure similar to the structure generated by PPI when it
parses a Perl script, and navigable in much the same way.

%prep
%setup -q -n %{dist}-%{version}

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/PPIx/Regexp*
%doc Changes README

%changelog
* Mon Feb 19 2018 Igor Vlasenko <viy@altlinux.ru> 0.055-alt1
- automated CPAN update

* Thu Feb 01 2018 Igor Vlasenko <viy@altlinux.ru> 0.054-alt1
- automated CPAN update

* Wed Nov 01 2017 Igor Vlasenko <viy@altlinux.ru> 0.053-alt1
- automated CPAN update

* Tue Sep 26 2017 Igor Vlasenko <viy@altlinux.ru> 0.052-alt1
- automated CPAN update

* Tue Feb 14 2017 Igor Vlasenko <viy@altlinux.ru> 0.051-alt1
- automated CPAN update

* Thu May 26 2016 Igor Vlasenko <viy@altlinux.ru> 0.050-alt1
- automated CPAN update

* Wed Apr 20 2016 Igor Vlasenko <viy@altlinux.ru> 0.049-alt1
- automated CPAN update

* Sat Mar 19 2016 Igor Vlasenko <viy@altlinux.ru> 0.048-alt1
- automated CPAN update

* Tue Dec 15 2015 Igor Vlasenko <viy@altlinux.ru> 0.044-alt1
- automated CPAN update

* Sat Nov 28 2015 Igor Vlasenko <viy@altlinux.ru> 0.043-alt1
- automated CPAN update

* Fri Oct 16 2015 Igor Vlasenko <viy@altlinux.ru> 0.042-alt1
- automated CPAN update

* Fri Dec 19 2014 Igor Vlasenko <viy@altlinux.ru> 0.037-alt1
- automated CPAN update

* Sat Mar 08 2014 Igor Vlasenko <viy@altlinux.ru> 0.036-alt1
- automated CPAN update

* Wed Jul 24 2013 Igor Vlasenko <viy@altlinux.ru> 0.034-alt1
- automated CPAN update

* Sun Sep 30 2012 Vladimir Lettiev <crux@altlinux.ru> 0.028-alt1
- 0.027 -> 0.028

* Thu May 31 2012 Vladimir Lettiev <crux@altlinux.ru> 0.027-alt1
- 0.021 -> 0.027

* Thu Sep 22 2011 Igor Vlasenko <viy@altlinux.ru> 0.021-alt1
- automated CPAN update

* Thu Mar 03 2011 Vladimir Lettiev <crux@altlinux.ru> 0.019-alt1
- New version 0.019

* Sun Feb 06 2011 Vladimir Lettiev <crux@altlinux.ru> 0.017-alt1
- New version 0.017

* Mon Jan 10 2011 Vladimir Lettiev <crux@altlinux.ru> 0.016-alt1
- New version 0.016

* Sat Nov 20 2010 Vladimir Lettiev <crux@altlinux.ru> 0.015-alt1
- New version 0.015

* Mon Oct 18 2010 Vladimir Lettiev <crux@altlinux.ru> 0.014-alt1
- New version 0.014

* Fri Oct 01 2010 Vladimir Lettiev <crux@altlinux.ru> 0.012-alt1
- New version 0.012

* Sun Sep 19 2010 Vladimir Lettiev <crux@altlinux.ru> 0.011-alt1
- New version 0.011

* Sun Aug 08 2010 Vladimir Lettiev <crux@altlinux.ru> 0.010-alt1
- New version 0.010

* Thu Jul 15 2010 Igor Vlasenko <viy@altlinux.ru> 0.008-alt1
- automated CPAN update

* Thu Jun 03 2010 Vladimir Lettiev <crux@altlinux.ru> 0.007-alt1
- New version 0.007

* Tue Apr 06 2010 Vladimir Lettiev <crux@altlinux.ru> 0.006-alt1
- initial build
