Name: perl-PPIx-Regexp
Version: 0.027
Release: alt1

Summary: Represent a regular expression of some sort
Group: Development/Perl
License: Perl

Url: %CPAN PPIx-Regexp
Source: %name-%version.tar

BuildArch: noarch
BuildRequires: perl-Task-Weaken perl-Readonly perl-PPI perl-Module-Build perl-List-MoreUtils perl-Params-Util

%description
This package parses regular expressions as they appear in Perl scripts,
generating a structure similar to the structure generated by PPI when it
parses a Perl script, and navigable in much the same way.

%prep
%setup -q

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/PPIx/Regexp*
%doc Changes README 

%changelog
* Thu May 31 2012 Vladimir Lettiev <crux@altlinux.ru> 0.027-alt1
- 0.021 -> 0.027

* Thu Sep 22 2011 Igor Vlasenko <viy@altlinux.ru> 0.021-alt1
- automated CPAN update

* Thu Mar 03 2011 Vladimir Lettiev <crux@altlinux.ru> 0.019-alt1
- New version 0.019

* Sun Feb 06 2011 Vladimir Lettiev <crux@altlinux.ru> 0.017-alt1
- New version 0.017

* Mon Jan 10 2011 Vladimir Lettiev <crux@altlinux.ru> 0.016-alt1
- New version 0.016

* Sat Nov 20 2010 Vladimir Lettiev <crux@altlinux.ru> 0.015-alt1
- New version 0.015

* Mon Oct 18 2010 Vladimir Lettiev <crux@altlinux.ru> 0.014-alt1
- New version 0.014

* Fri Oct 01 2010 Vladimir Lettiev <crux@altlinux.ru> 0.012-alt1
- New version 0.012

* Sun Sep 19 2010 Vladimir Lettiev <crux@altlinux.ru> 0.011-alt1
- New version 0.011

* Sun Aug 08 2010 Vladimir Lettiev <crux@altlinux.ru> 0.010-alt1
- New version 0.010

* Thu Jul 15 2010 Igor Vlasenko <viy@altlinux.ru> 0.008-alt1
- automated CPAN update

* Thu Jun 03 2010 Vladimir Lettiev <crux@altlinux.ru> 0.007-alt1
- New version 0.007

* Tue Apr 06 2010 Vladimir Lettiev <crux@altlinux.ru> 0.006-alt1
- initial build
