#
#   - Lingua::EN::Segmenter -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Lingua-EN-Segmenter
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Lingua-EN-Segmenter
%define m_distro Lingua-EN-Segmenter
%define m_name Lingua::EN::Segmenter
%define m_author_id unknown
%define _enable_test 1

Name: perl-Lingua-EN-Segmenter
Version: 0.1
Release: alt2.1

Summary: Subdivide texts into passages that represent subtopics

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/S/SP/SPLICE/%m_distro-%version.tar.bz2

# Automatically added by buildreq on Tue Jun 17 2008
BuildRequires: perl-Class-Exporter perl-File-Slurp perl-Lingua-Stem perl-Math-HashSum perl-Math-VecStat perl-Math-Vector-SortIndexes perl-devel

%description
Subdivide texts into passages that represent subtopics.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc CHANGES README
%perl_vendor_privlib/Lingua/

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.1-alt2.1
- repair after perl 5.12 upgrade using girar-nmu

* Sat Sep 06 2008 Vitaly Lipatov <lav@altlinux.ru> 0.1-alt2
- fix directory ownership violation

* Tue Jun 17 2008 Vitaly Lipatov <lav@altlinux.ru> 0.1-alt1
- initial build for ALT Linux Sisyphus

