#
#   - Tree::Simple::VisitorFactory -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#

%define module Tree-Simple-VisitorFactory
%define m_distro Tree-Simple-VisitorFactory
%define m_name Tree::Simple::VisitorFactory
%define m_author_id unknown
%def_enable test

Name: perl-Tree-Simple-VisitorFactory
Version: 0.10
Release: alt2.1

Summary: %m_name - A factory object for dispensing Visitor objects

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/Tree-Simple-VisitorFactory/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/S/ST/STEVAN/%m_distro-%version.tar.gz

# Automatically added by buildreq on Sat Sep 06 2008 (-bi)
BuildRequires: perl-Test-Exception perl-Test-Pod perl-Test-Pod-Coverage perl-Tree-Simple

%description
This object is really just a factory for dispensing
Tree::Simple::Visitor::* objects. It is not required to use this
package in order to use all the Visitors, it is just a somewhat
convienient way to avoid having to type thier long class names.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Tree*
%doc Changes README

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.10-alt2.1
- repair after perl 5.12 upgrade using girar-nmu

* Sat Sep 06 2008 Michael Bochkaryov <misha@altlinux.ru> 0.10-alt2
- fix directory ownership violation

* Wed Mar 21 2007 Sir Raorn <raorn@altlinux.ru> 0.10-alt1
- first build for ALT Linux Sisyphus

