#
#   - SOAP::MIME -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   (ALT Linux revision)
#   The following arguments were used:
#       SOAP-MIME --version 0.55-7
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module SOAP-MIME
%define m_distro SOAP-MIME
%define m_name SOAP::MIME
%define m_author_id unknown
%define _enable_test 1

%define oversion 0.55-7
Name: perl-SOAP-MIME
Version: 0.55.7
Release: alt1

Summary: SOAP-MIME - Perl module

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org/CPAN/authors/id/B/BY/BYRNE/SOAP/%m_distro-%oversion.tar

# Automatically added by buildreq on Mon Dec 24 2012 (-bi)
# optimized out: perl-Class-Inspector perl-Compress-Raw-Zlib perl-IO-Compress perl-URI perl-devel python-base
BuildRequires: perl-SOAP-Lite

%description
Patch to SOAP::Lite to add attachment support.
This module allows Perl clients to both compose messages with attachments,
and to parse messages with attachments.

%prep
%setup -n %m_distro-%oversion

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/SOAP/*

%changelog
* Mon Dec 24 2012 Vitaly Lipatov <lav@altlinux.ru> 0.55.7-alt1
- initial build for ALT Linux Sisyphus

