#
#   - Data-ObjectDriver -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --spec-only Data::ObjectDriver
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Data-ObjectDriver
%define m_distro Data-ObjectDriver
%define m_name Data-ObjectDriver
%define m_author_id unknown
%define _enable_test 1

Name: perl-Data-ObjectDriver
Version: 0.09
Release: alt1

Summary: Simple, transparent data interface, with caching

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Denis Baranov <baraka@altlinux.ru>

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Thu Mar 10 2011
BuildRequires: libnss-role perl-Class-Accessor perl-Class-Data-Inheritable perl-Class-Trigger perl-DBI perl-Module-Install

%description
Data::ObjectDriver is an object relational mapper, 
meaning that it maps object-oriented design concepts onto a relational database.

It's inspired by, and descended from, the MT::ObjectDriver classes 
in Six Apart's Movable Type and TypePad weblogging products. 
But it adds in caching and partitioning layers, allowing you 
to spread data across multiple physical databases, 
without your application code needing to know where the data is stored.

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install
rm -f %buildroot/%perl_vendor_privlib/Data/ObjectDriver/Driver/DBD/Oracle.pm
rm -f %buildroot/%perl_vendor_privlib/Data/ObjectDriver/Driver/DBD/SQLite.pm

%files
%perl_vendor_privlib/Data/ObjectDriver/*
%perl_vendor_privlib/Data/ObjectDriver.pm

%changelog
* Thu Sep 22 2011 Igor Vlasenko <viy@altlinux.ru> 0.09-alt1
- automated CPAN update

* Thu Mar 10 2011 Denis Baranov <baraka@altlinux.ru> 0.07-alt1
- initial build for ALT Linux Sisyphus

