#
#   - Test::Deep -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Test::Deep
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Test-Deep
%define m_distro Test-Deep
%define m_name Test::Deep
%define m_author_id unknown
%define _enable_test 1

Name: perl-Test-Deep
Version: 0.108
Release: alt1

Summary: Test-Deep - Perl module

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Mikhail Pokidko <pma@altlinux.org>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/R/RJ/RJBS/Test-Deep-0.108.tar.gz
Patch: %name.patch

# Automatically added by buildreq on Mon Dec 08 2008
BuildRequires: perl-Test-NoWarnings perl-Test-Tester

%description
None.

%prep
%setup -q -n %m_distro-%version
%patch -p1
%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%perl_vendor_privlib/Test/*

%changelog
* Mon Sep 19 2011 Igor Vlasenko <viy@altlinux.ru> 0.108-alt1
- automated CPAN update

* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 0.106-alt1
- automated CPAN update

* Mon Dec 08 2008 Mikhail Pokidko <pma@altlinux.org> 0.103-alt1
- initial build for ALT Linux Sisyphus

