# Original package name Coxpcall
%define oname coxpcall
%define oversion 1.15.0-1
%define rockspec coxpcall-1.15.0-1.rockspec
Name: lua-module-%oname
Version: 1.15.0
Release: alt1_lr1
Summary: Coroutine safe xpcall and pcall
License: MIT/X11
Group: Development/Other
Url: http://keplerproject.github.com/coxpcall
Provides: luarocks(%oname) = %version

BuildArch: noarch

# git://github.com/keplerproject/coxpcall
Source: %oname.tar
Source1: https://rocks.moonscript.org/manifests/luarocks/coxpcall-1.15.0-1.rockspec

BuildPreReq: rpm-macros-lua >= 1.1
# Automatically added by buildreq on ...
BuildRequires: liblua5-devel luarocks

%description
 Encapsulates the protected calls with a coroutine based loop, so errors can
 be dealed without the usual Lua 5.x pcall/xpcall issues with coroutines
 yielding inside the call to pcall or xpcall.
  

%prep
%setup -n %oname

%install
%luarocks_make %SOURCE1
%luarocks_move_docs doc

%files
%lua_modulesdir_noarch/*
%luarocks_dbdir/%oname
%doc README* docs_from_rockstree/*
%exclude %luarocks_dbdir/manifest

%changelog
* Wed Oct 15 2014 Ildar Mulyukov <ildar@altlinux.ru> 1.15.0-alt1_lr1
- autogenerated by lrimport

* Fri Jan 07 2011 Ildar Mulyukov <ildar@altlinux.ru> 1.13.0-alt1_lr1
- autogenerated by lrimport
