Group: Development/Java
# BEGIN SourceDeps(oneline):
BuildRequires(pre): rpm-macros-java
# END SourceDeps(oneline)
%filter_from_requires /^java-headless/d
BuildRequires: /proc
BuildRequires: jpackage-generic-compat
%global commit 2da2859d1232a9a88025e069dc43adc4048a018a
%global shortcommit %(c=%{commit}; echo ${c:0:7})

Name:           pmd-build-tools
Version:        0.9
Release:        alt1_3jpp8
Summary:        PMD Build Plugin
License:        BSD
URL:            http://pmd.sourceforge.net/
BuildArch:      noarch

Source0:        https://github.com/pmd/build-tools/archive/%{commit}/pmd-build-tools-%{shortcommit}.tar.gz
# Forwarded upstream: https://github.com/pmd/build-tools/pull/1
Source1:        LICENSE

BuildRequires:  maven-local
BuildRequires:  mvn(commons-io:commons-io)
BuildRequires:  mvn(junit:junit)
BuildRequires:  mvn(org.apache.ant:ant)
BuildRequires:  mvn(org.apache.maven:maven-compat)
BuildRequires:  mvn(org.apache.maven:maven-core)
BuildRequires:  mvn(org.apache.maven:maven-plugin-api)
BuildRequires:  mvn(org.apache.maven.plugins:maven-release-plugin)
BuildRequires:  mvn(org.apache.maven.plugins:maven-site-plugin)
BuildRequires:  mvn(org.apache.maven.plugin-testing:maven-plugin-testing-harness)
BuildRequires:  mvn(org.apache.maven.plugin-tools:maven-plugin-annotations)
BuildRequires:  mvn(org.sonatype.oss:oss-parent:pom:)
Source44: import.info

%description
This small subproject regroups most of the stuff needed to build PMD.
As some Java code has been produced to reduce the use of scripts when
generating the website, the build also requires a small jar, which is
generated by this pom.

%package javadoc
Group: Development/Java
Summary:        API documentation for %{name}
BuildArch: noarch

%description javadoc
This package provides %{summary}.

%prep
%setup -q -n build-tools-%{commit}
cp -a %{SOURCE1} .

%build
%mvn_build

%install
%mvn_install

%files -f .mfiles
%doc LICENSE

%files javadoc -f .mfiles-javadoc
%doc LICENSE

%changelog
* Tue Nov 22 2016 Igor Vlasenko <viy@altlinux.ru> 0.9-alt1_3jpp8
- new fc release

* Mon Feb 01 2016 Igor Vlasenko <viy@altlinux.ru> 0.9-alt1_2jpp8
- new version

