%define pname semver

Name: node-semver
Version: 7.3.2
Release: alt1

Summary: The semantic versioner for npm

License: ISC
Group: Development/Other
Url: https://github.com/npm/node-semver

Packager: Vitaly Lipatov <lav@altlinux.ru>

# Source-url: https://github.com/npm/node-semver/archive/v%version.tar.gz
Source: %name-%version.tar

#Source1: %name-development-%version.tar

BuildArch: noarch

BuildRequires(pre): rpm-build-intro >= 2.2.2
BuildRequires(pre): rpm-macros-nodejs >= 0.20.5

BuildRequires: rpm-build-nodejs node

# devDependencies generated by epm --restore --dry-run from node-semver/package.json
BuildRequires: node-tap >= 14.10.7

Provides: npm(%pname) = %version

AutoProv: no

%description
The semantic versioner for npm.

%prep
%setup

%build
%npm_build

%check
%npm_test

%install
%npm_install
mkdir -p %buildroot%_bindir/
ln -s %nodejs_sitelib/%pname/bin/%pname.js %buildroot%_bindir/%pname
%npm_prune

%files
%doc LICENSE README.md
%_bindir/%pname
%nodejs_sitelib/%pname/

%changelog
* Thu Oct 29 2020 Vitaly Lipatov <lav@altlinux.ru> 7.3.2-alt1
- initial build for ALT Sisyphus
