#
#   - Module-Versions-Report -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --spec-only -U Module::Versions::Report
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Module-Versions-Report
%define m_distro Module-Versions-Report
%define m_name Module-Versions-Report
%define m_author_id RUZ
%define _enable_test 1

Name: perl-Module-Versions-Report
Version: 1.06
Release: alt1.1

Summary: Module-Versions-Report - report versions of all modules in memory

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/~jesse/Module-Versions-Report-%version/

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/J/JE/JESSE/Module-Versions-Report-1.06.tar.gz


# Automatically added by buildreq on Tue Jun 07 2005
BuildRequires: perl-devel

%description
I often get email from someone reporting a bug in a module I've
written.  I email back, asking what version of the module it is,
what version of Perl on what OS, and sometimes what version of
some relevent third library (like XML::Parser).  They reply,
saying "Perl 5".  I say "I need the exact version, as reported
by "perl -v"".  They tell me.  And I say "I, uh, also asked about
the version of my module and XML::Parser [or whatever]".  They say
"Oh yeah.  It's 2.27".  "Is that my module or XML::Parser?"
"XML::Parser."  "OK, and what about my module's
version?"  "Ohyeah.  That's 3.11."  By this time, days have passed,
and what should have been a simple operation -- reporting the version
of Perl and relevent modules, has been needlessly complicated.

This module is for simplifying that task.  If you add "use
Module::Versions::Report;" to a program (especially handy if your
program is one that demonstrates a bug in some module), then when the
program has finished running, you well get a report detailing the all
modules in memory, and noting the version of each (for modules that
defined a $VERSION, at least).

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc ChangeLog README
%perl_vendor_privlib/Module/

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 1.06-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 1.06-alt1
- automated CPAN update

* Sat Sep 06 2008 Vitaly Lipatov <lav@altlinux.ru> 1.05-alt2
- fix directory ownership violation

* Mon Jun 23 2008 Vitaly Lipatov <lav@altlinux.ru> 1.05-alt1
- new version 1.05 (with rpmrb script) (fix bug #16136)

* Fri Jun 13 2008 Vitaly Lipatov <lav@altlinux.ru> 1.04-alt1
- new version 1.04 (with rpmrb script) (fix bug #15983)

* Fri Jul 06 2007 Vitaly Lipatov <lav@altlinux.ru> 1.03-alt1
- new version 1.03 (with rpmrb script) (fix bug #12227)
- add some doc

* Tue Jun 07 2005 Vitaly Lipatov <lav@altlinux.ru> 1.02-alt1
- first build for ALT Linux Sisyphus
