#   - Array::Compare -
#   This spec file originally was generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)

%define module Array-Compare
%define m_distro Array-Compare
%define m_name Array::Compare
%define m_author_id unknown
%define _enable_test 1

Name: perl-Array-Compare
Version: 2.01
Release: alt1.1

Summary: Array::Compare - perl module comparing arrays

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/Array-Compare/

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Tue Apr 27 2010 (-bi)
BuildRequires: perl-Module-Build perl-Moose perl-Test-Pod perl-Test-Pod-Coverage

%description
Array::Compare is a Perl module which allows you to compare two arrays.

It has a number of features which allow you to control the way that the
arrays are compared:

* white space in array elements can be significant or ignored.
* particular columns in the arrays can be ignored.

Additionally you can get a simple true/false return value or the number
of columns which differ or an array containing the indexes of the
differing columns.


%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Array*
%doc Changes README

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 2.01-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Apr 27 2010 Alexey Tourbin <at@altlinux.ru> 2.01-alt1
- 1.16 -> 2.01

* Fri Sep 05 2008 Michael Bochkaryov <misha@altlinux.ru> 1.16-alt2
- fix directory ownership violation

* Sat Mar 15 2008 Michael Bochkaryov <misha@altlinux.ru> 1.15-alt1
- 1.15 version;
- prerequisites fixed in Build.PL
- small spec file cleanup

* Fri Feb 01 2008 Michael Bochkaryov <misha@altlinux.ru> 1.14-alt1
- first build for ALT Linux Sisyphus

