# BEGIN SourceDeps(oneline):
BuildRequires: perl(HTTP/Cookies.pm)
# END SourceDeps(oneline)
%define _unpackaged_files_terminate_build 1
#
#   - Catalyst::Plugin::Session::State::Cookie -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#

%define module Catalyst-Plugin-Session-State-Cookie
%define m_distro Catalyst-Plugin-Session-State-Cookie
%define m_name Catalyst::Plugin::Session::State::Cookie
%define m_author_id NUFFIN
%def_enable test

Name: perl-Catalyst-Plugin-Session-State-Cookie
Version: 0.18
Release: alt2
Summary: %m_name - Maintain session IDs using cookies

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/Catalyst-Plugin-Session-State-Cookie/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source0: http://www.cpan.org/authors/id/H/HA/HAARG/%{module}-%{version}.tar.gz

# Automatically added by buildreq on Tue Apr 20 2010 (-bi)
BuildRequires: perl-Catalyst-Plugin-Session perl-Module-Install perl-Test-Pod perl-Test-Pod-Coverage

%description
In order for Catalyst::Plugin::Session to work the session ID
needs to be stored on the client, and the session data needs to
be stored on the server.

This plugin stores the session ID on the client using the cookie
mechanism.

%prep
%setup -q -n %{module}-%{version}

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Catalyst*
%doc Changes README

%changelog
* Fri Aug 25 2023 Igor Vlasenko <viy@altlinux.org> 0.18-alt2
- NMU: fixed build

* Tue Sep 01 2020 Igor Vlasenko <viy@altlinux.ru> 0.18-alt1
- automated CPAN update

* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.17-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Apr 20 2010 Alexey Tourbin <at@altlinux.ru> 0.17-alt1
- 0.09 -> 0.17

* Mon Sep 08 2008 Michael Bochkaryov <misha@altlinux.ru> 0.09-alt2
- fix directory ownership violation

* Tue Jul 01 2008 Michael Bochkaryov <misha@altlinux.ru> 0.09-alt1
- 0.09 version build

* Tue Mar 27 2007 Sir Raorn <raorn@altlinux.ru> 0.06-alt1
- first build for ALT Linux Sisyphus

