#
#   - WordPress::XMLRPC -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   (ALT Linux revision)
#   The following arguments were used:
#       '--packager=Igor Vlasenko <viy@altlinux.ru>' --no-depchk --url http://search.cpan.org/CPAN/authors/id/L/LE/LEOCHARRE/WordPress-XMLRPC-1.23.tar.gz http://search.cpan.org/CPAN/authors/id/L/LE/LEOCHARRE/WordPress-XMLRPC-1.23.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module WordPress-XMLRPC
%define m_distro WordPress-XMLRPC
%define m_name WordPress::XMLRPC
%define m_author_id unknown
%define _disable_test 1

Name: perl-WordPress-XMLRPC
Version: 1.23
Release: alt1

Summary: api to wordpress xml rpc calls

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/CPAN/authors/id/L/LE/LEOCHARRE/WordPress-XMLRPC-1.23.tar.gz

Packager: Igor Vlasenko <viy@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org/CPAN/authors/id/L/LE/LEOCHARRE/%m_distro-%version.tar.gz

# Automatically added by buildreq on Fri Nov 18 2011
BuildRequires: perl-YAML perl-devel perl(LEOCHARRE/Debug.pm) perl(SOAP/Lite.pm) perl(XMLRPC/Lite.pm) perl(LEOCHARRE/CLI2.pm) perl(Smart/Comments.pm)


%description
I wanted to interact via the command line to a wordpress blog's xmlrpc.php file.
Bascially this is interaction with xmlrpc.php as client.
This module is not meant for speed, it is meant for convenience.

This is really useful to automate new postings, uploading media, etc.

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/WordPress/*

%changelog
* Fri Nov 18 2011 Igor Vlasenko <viy@altlinux.ru> 1.23-alt1
- initial build for ALT Linux Sisyphus

