Name: gprs-easyconnect
Version: 2.5.3
Release: alt1.qa3

Summary: GPRS internet dialer
Summary (ru_RU.UTF-8): Программа для установления соединения по GPRS
License: GPL
Group: System/Configuration/Other
Url: http://easyconnect.linuxuser.hu
Source0: GPRS_Easy_Connect_253_Install.tar.gz 
Source1: gprsec.pamd
Source2: gprsec.apps
Patch0: gprsec-apn.diff
Patch1: gprsec-title.diff
BuildRequires: perl perl-Tk perl-libwww-perl libpam0-devel
BuildArch: noarch

%description
The GPRS Easy Connect is a free GUI GPRS internet connecting program
for Linux OS.

%description -l ru_RU.UTF-8
GPRS Easy Connect - свободная графическая программа для подключения к сети Интернет
через GPRS в ОС Linux.

%prep
%setup -q -n GPRS_Easy_Connect_253_Install
%patch0
%patch1

%build

%install
install -pD -m755 data/bin/gprsec $RPM_BUILD_ROOT%_sbindir/gprsec
install -pD -m755 data/bin/read2.pl $RPM_BUILD_ROOT%_bindir/read2.pl
install -pD -m644 data/share/icons/gprsec.png $RPM_BUILD_ROOT%_datadir/pixmaps/gprsec.png
install -d -m755 $RPM_BUILD_ROOT%_datadir/gprsec
install -p -m644 data/share/gprsec/{AUTHORS,history,version} $RPM_BUILD_ROOT%_datadir/gprsec
install -d -m755 $RPM_BUILD_ROOT%_datadir/gprsec/images/phones
install -p -m644 data/share/gprsec/images/phones/*.gif $RPM_BUILD_ROOT%_datadir/gprsec/images/phones
install -p -m644 data/share/gprsec/images/*.gif $RPM_BUILD_ROOT%_datadir/gprsec/images
install -p -m644 data/share/gprsec/images/*.{25,gif,png,xpm} $RPM_BUILD_ROOT%_datadir/gprsec/images
install -d -m755 $RPM_BUILD_ROOT%_datadir/gprsec/languages
#install -p -m644 data/share/gprsec/languages/{ces,deu,eng,esp,fra,ita,mag,nor,pol,rus,suo,t}* $RPM_BUILD_ROOT%_datadir/gprsec/languages
install -p -m644 data/share/gprsec/languages/{ces,deu,eng,esp,fra,ita,mag,nor,pol,suo,t}* $RPM_BUILD_ROOT%_datadir/gprsec/languages
install -d -m755 $RPM_BUILD_ROOT%_datadir/gprsec/tools
install -p -m644 data/share/gprsec/tools/* $RPM_BUILD_ROOT%_datadir/gprsec/tools
# consolehelper
install -pD -m640 %SOURCE1 $RPM_BUILD_ROOT%_sysconfdir/pam.d/gprsec
install -pD -m640 %SOURCE2 $RPM_BUILD_ROOT%_sysconfdir/security/console.apps/gprsec
mkdir -p $RPM_BUILD_ROOT%_bindir
ln -s ../lib/helper/consolehelper $RPM_BUILD_ROOT%_bindir/gprsec

# menu
mkdir -p %buildroot%_desktopdir
cat > %buildroot%_desktopdir/%{name}.desktop <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=GPRS Easy Connect
Comment=GPRS internet dialer
Icon=gprsec
Exec=gprsec
Terminal=false
Categories=Network;Dialup;
EOF

%files
%config(missingok,noreplace) %_sysconfdir/pam.d/gprsec
%config(missingok,noreplace) %_sysconfdir/security/console.apps/gprsec
%_sbindir/*
%_bindir/*
%_datadir/pixmaps/*
%_datadir/gprsec
%_desktopdir/%{name}.desktop

# TODO:
# - 3.0.x

%changelog
* Fri Apr 22 2011 Igor Vlasenko <viy@altlinux.ru> 2.5.3-alt1.qa3
- NMU: converted menu to desktop file

* Tue Jun 16 2009 Michael Shigorin <mike@altlinux.org> 2.5.3-alt1.2
- NMU: fixed Kyivstar GSM APN data (closes: #10853)
- fixed path to consolehelper on x86_64

* Thu Jan 12 2006 ALT QA Team Robot <qa-robot@altlinux.org> 2.5.3-alt1.1
- Rebuilt for new style PAM dependencies generated by rpm-build-4.0.4-alt55.

* Mon Jul 11 2005 Vyacheslav Dikonov <slava@altlinux.ru> 2.5.3-alt1
- 2.5.3, Kyivstar GSM support (by M. Shigorin)

* Mon Aug 09 2004 Vyacheslav Dikonov <slava@altlinux.ru> 2.5.1pre14-alt2
- consolehelper

* Sat Aug 07 2004 Vyacheslav Dikonov <slava@altlinux.ru> 2.5.1pre14-alt1
- ALTLinux build
