## SPEC file for Perl module Text::Table
## Used in SVK

Name: perl-Text-Table
Version: 1.135
Release: alt1

Summary: organize data in tables
Summary(ru_RU.UTF-8): организует данные в таблицы

License: The ISC license
Group: Development/Perl

%define real_name Text-Table
URL: http://search.cpan.org/dist/Text-Table/

Packager: Nikolay A. Fetisov <naf@altlinux.ru>
BuildArch: noarch

Source: %real_name-%version.tar

AutoReqProv: perl, yes

# Automatically added by buildreq on Sat Jan 21 2017
# optimized out: perl perl-CPAN-Meta perl-CPAN-Meta-Requirements perl-CPAN-Meta-YAML perl-Class-XSAccessor perl-Encode perl-File-Find-Object perl-File-Find-Object-Rule perl-JSON-PP perl-Module-Metadata perl-Number-Compare perl-Parse-CPAN-Meta perl-Perl-OSType perl-Pod-Escapes perl-Pod-Simple perl-Term-ANSIColor perl-Text-Glob perl-Tie-RefHash perl-autodie perl-devel perl-parent perl-podlators python-base python-modules python3-base
BuildRequires: perl-HTML-Parser perl-Module-Build perl-Test-TrailingSpace perl-Text-Aligner

%description
Organization  of data  in  table form is  a time-honored  and
useful method  of data representation.  While columns of data
are trivially generated by computer through formatted output,
even simple tasks  like keeping titles  aligned with the data
columns are not trivial, and the one-shot solutions one comes
up with tend to be particularly hard to maintain. Text::Table
allows you to create and maintain tables that adapt to 
alignment requirements as you use them.

%description -l ru_RU.UTF-8
Организация  данных  в табличной  форме является  полезным и 
экономящим время  способом представления данных.  В то время
как колонки данных тривиально генерируются компьютеров через
форматированный  вывод,   даже  такая  простая  задача,  как 
выравнивание заголовков с колонками  данных вызывает опреде-
лённые сложности  и быстрые  решения  оказываются достаточно
сложными для  дальнейшей  поддержки их. Данные модуль Perl - 
Text::Table  позволяет  создавать  и  поддерживать  таблицы, 
которые адаптируются  к заданным требованиям по выравниванию 
колонок данных.


%prep
%setup -q -n %real_name-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc Changes README
%exclude /.perl.req
%perl_vendor_privlib/Text/Table*

%changelog
* Mon Dec 05 2022 Nikolay A. Fetisov <naf@altlinux.org> 1.135-alt1
- New version

* Sun May 17 2020 Nikolay A. Fetisov <naf@altlinux.org> 1.134-alt1
- New version

* Wed Aug 09 2017 Nikolay A. Fetisov <naf@altlinux.org> 1.133-alt1
- New version

* Sat Jan 21 2017 Nikolay A. Fetisov <naf@altlinux.org> 1.132-alt1
- New version

* Sat Jul 30 2016 Nikolay A. Fetisov <naf@altlinux.ru> 1.131-alt1
- New version

* Sun Aug 31 2014 Nikolay A. Fetisov <naf@altlinux.ru> 1.130-alt1
- New version

* Sun Dec 01 2013 Nikolay A. Fetisov <naf@altlinux.ru> 1.128-alt1
- New version

* Sat Aug 10 2013 Nikolay A. Fetisov <naf@altlinux.ru> 1.127-alt1
- New version

* Thu Oct 18 2012 Nikolay A. Fetisov <naf@altlinux.ru> 1.126-alt1
- New version 1.126

* Thu Sep 22 2011 Igor Vlasenko <viy@altlinux.ru> 1.124-alt1
- automated CPAN update

* Tue Jun 21 2011 Nikolay A. Fetisov <naf@altlinux.ru> 1.123-alt1
- New version 1.123

* Sun Nov 28 2010 Nikolay A. Fetisov <naf@altlinux.ru> 1.116-alt1
- New version 1.116

* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 1.114-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Sun Dec 14 2008 Nikolay A. Fetisov <naf@altlinux.ru> 1.114-alt1
- New version 1.114

* Sun Apr 23 2006 Nikolay A. Fetisov <naf@altlinux.ru> 1.107-alt1
- Initial build for ALT Linux

* Tue May 24 2005 Nikolay A. Fetisov <naf@altlinux.ru> 1.107-alt0.1
- Build for new perl-5.8.7

* Sun Mar 06 2005 Nikolay A. Fetisov <naf@altlinux.ru> 1.107-alt0
- Initial build
