%define srcName cmap

Name: tetex-latex-%srcName
Version: 1.0g
Release: alt2
Summary: Make PDF files searchable and copyable
License: LPPL (LaTeX Project Public License)
Group: Publishing
Url: http://www.ctan.org/tex-archive/macros/latex/contrib/cmap
Packager: Kirill Maslinsky <kirill@altlinux.org>

BuildArch: noarch

BuildRequires(pre): rpm-build-texmf
Requires: tetex-core tetex-latex

Source0: %srcName-%version.tar

%description
The cmap package provides character map tables, which make PDF files generated by pdfLaTeX both searchable and copy-able in acrobat reader and other compliant PDF viewers.  Encodings supported are OT1, T1, T2A, T2B, T2C and T5, together with LAE (Arabic) and LFE (Farsi) and a variant OT1tt for cmtt-like fonts.

The package's main limitation currently is the inability to work with virtual fonts, because of limitations of pdfTeX. This restriction may be resolved in a future version of pdfTeX.

%prep
%setup -q -n %srcName-%version

%build

%install
%__mkdir_p %buildroot%_datadir/texmf/tex/latex/%srcName
install -pD -m644 cmap.sty *.cmap  %buildroot%_datadir/texmf/tex/latex/%srcName/

%files
%_datadir/texmf/tex/latex/%srcName/
%doc README

%changelog
* Mon Nov 16 2009 Andrey Bergman <vkni@altlinux.org> 1.0g-alt2
- Removed post and pre sections. Added dependence on rpm-build-texmf.

* Fri Jun 27 2008 Kirill Maslinsky <kirill@altlinux.org> 1.0g-alt1
- Initial build for Sisyphus

