%define pkgname RTF-Tokenizer

Name:      perl-%pkgname
Summary:   %pkgname - Tokenize RTF
Version:   1.10
Release:   alt1.qa1.1
License:   GPL or Artistic
Group:     Development/Perl
URL:       http://www.cpan.org
Source:    http://search.cpan.org/CPAN/authors/id/S/SA/SARGIE/%pkgname-%version.tar.gz

Buildarch: noarch


BuildRequires: perl-IO-stringy perl-devel perl-Text-Diff

%description
RTF::Tokenizer is an object-orientated low-level RTF reader. If 
you're looking to render RTF, or want a higher-level RTF processor, 
this is not the module for you - you want RTF::Reader.  This is the 
sixth release of  RTF::Tokenizer - it's faster, higher quality, and 
implements the RTF standard better than any previous release.

%prep
%setup -q -n %pkgname-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

# There is a file in the package with a name starting with <tt>._</tt>, 
# the file name pattern used by Mac OS X to store resource forks in non-native 
# file systems. Such files are generally useless in packages and were usually 
# accidentally included by copying complete directories from the source tarball.
find $RPM_BUILD_ROOT -name '._*' -size 1 -print0 | xargs -0 grep -lZ 'Mac OS X' -- | xargs -0 rm -f


%files
%doc README TODO
%_bindir/*
%perl_vendor_privlib/RTF*

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 1.10-alt1.qa1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Nov 10 2009 Repocop Q. A. Robot <repocop@altlinux.org> 1.10-alt1.qa1
- NMU (by repocop): the following fixes applied:
  * macos-resource-fork-file-in-package for perl-RTF-Tokenizer
  * postclean-05-filetriggers for spec file

* Tue Feb 19 2008 Slava Dubrovskiy <dubrsl@altlinux.org> 1.10-alt1
- 1.10

* Thu Jun 22 2006 Slava Dubrovskiy <dubrsl@altlinux.ru> 1.08-alt0
- Build for Sisyphus
- Update spec

* Sat Jun  3 2006 Valentyn Solomko <val@pere.org.ua>
- rebuilt after some corrections

* Wed May 31 2006 Valentyn Solomko <val@pere.org.ua>
- Spec file was autogenerated by cpan2rpm [ver: 2.028]. 
