#
#   - Test::Distribution -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --version 2.00 Test::Distribution
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Test-Distribution
%define m_distro Test-Distribution
%define m_name Test::Distribution
%define m_author_id unknown
%define _enable_test 1

Name: perl-Test-Distribution
Version: 2.00
Release: alt1.1.1

Summary: %m_name - perform tests on all modules of a distribution

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/dist/Test-Distribution/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org/CPAN/authors/id/S/SR/SRSHAH/%m_distro-%version.tar.gz

# Automatically added by buildreq on Sun Jul 20 2008 (-bi)
BuildRequires: perl-File-Find-Rule perl-Module-Build perl-Module-CoreList perl-Test-Pod perl-Test-Pod-Coverage perl-version

%description
When using this module in a test script, it goes through all the modules in
your distribution, checks their POD, checks that they compile ok and checks
that they all define a $VERSION.

This module also performs a numer of test on the distribution itself. It checks
that your files match your SIGNATURE file if you have one. It checks that your
distribution isn't missing certain 'core' description files. It checks to see
you havent' missed out listing any pre-requisites in Makefile.PL.

It defines its own testing plan, so you usually don't use it in conjunction
with other Test::* modules in the same file. It's recommended that you just
create a one-line test script as shown in the SYNOPSIS above. However, there
are options...

NOTE If you do not specify any options Test::Distribution will run all test
types except signature testing which must always be explicitly switched on.

In the future I may change the default to run no tests at all as this sounds
safer. Mail me if you disagree

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/*
%doc README Changes.pod
%exclude %perl_vendor_archlib

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 2.00-alt1.1.1
- repair after perl 5.12 upgrade using girar-nmu

* Mon Oct 06 2008 Igor Vlasenko <viy@altlinux.ru> 2.00-alt1.1
- NMU for unknown reason:
  the person above was too neglectant to add --changelog "- NMU: <reason>" option.

* Sun Jul 20 2008 Michael Bochkaryov <misha@altlinux.ru> 2.00-alt1
- first build for ALT Linux Sisyphus

