#
#   - Math-Random-Secure -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Math-Random-Secure
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Math-Random-Secure
%define m_distro Math-Random-Secure
%define m_name Math-Random-Secure
%define m_author_id unknown
%define _enable_test 1

Name: perl-Math-Random-Secure
Version: 0.06
Release: alt1

Summary: Cryptographically-secure, cross-platform replacement for rand()

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Denis Baranov <baraka@altlinux.ru>

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Mon May 02 2011 (-bi)
# optimized out: perl-Any-Moose perl-B-Hooks-EndOfScope perl-Data-OptList perl-Module-Find perl-Package-Stash perl-Params-Util perl-Sub-Exporter perl-Sub-Identify perl-Sub-Install perl-Sub-Name perl-Sub-Uplevel perl-Tree-DAG_Node perl-Variable-Magic perl-devel perl-namespace-clean
BuildRequires: perl-Crypt-Random-Source perl-List-MoreUtils perl-Math-Random-ISAAC perl-Mouse perl-Test-Warn

%description
None.

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Math/Random/Secure/*
%perl_vendor_privlib/Math/Random/Secure.pm


%changelog
* Mon May 02 2011 Denis Baranov <baraka@altlinux.ru> 0.06-alt1
- initial build for ALT Linux Sisyphus

