# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-artwork
Version: 0.88.0
Release: alt1
Summary: Artwork for Sugar look-and-feel
License: LGPLv2+
Group: Graphical desktop/Sugar
Url: http://sugarlabs.org/
Packager: Sugar Development Team <sugar@packages.altlinux.org>


Source: http://download.sugarlabs.org/sources/sucrose/glucose/sugar-artwork/sugar-artwork-0.88.0.tar.bz2

Patch: sugar-artwork-0.88.0-sugar-1899.patch

Requires: libgtk+2 >= 2.9.0
Requires: sugar-base >= 0.88.0

BuildPreReq: perl-XML-Parser  
BuildPreReq: libgtk+2-devel >= 2.9.0
BuildPreReq: icon-naming-utils  
BuildPreReq: icon-slicer  
BuildPreReq: python  
BuildPreReq: xcursorgen  

%description
Contains the themes and icons that make up the Sugar default look and feel.

%prep
%setup -v -n sugar-artwork-0.88.0
%patch -p1

%build
%define __libtoolize true
%configure
make

%install
make DESTDIR=%{buildroot} install
rm -f %{buildroot}/%{_libdir}/gtk-2.0/*/engines/*.la


%files 
%defattr(-,root,root,-)
%{_datadir}/icons/*
%{_datadir}/themes/*
%{_libdir}/gtk*/*/engines/*
%doc COPYING NEWS README

%changelog
* Tue Apr 06 2010 Aleksey Lim <alsroot@altlinux.org> 0.88.0-alt1
- Sucrose 0.88.0 release

* Tue Mar 17 2009 Aleksey Lim <alsroot@altlinux.org> 0.84.1-alt1
- update Sucrose to 0.84.0 version

* Sun Feb 15 2009 Aleksey Lim <alsroot@altlinux.org> 0.83.4-alt1
- new Sucrose 0.83.5 release

* Tue Jan 20 2009 Aleksey Lim <alsroot@altlinux.org> 0.83.3-alt1
- new Sucrose 0.83.4 release

* Tue Dec 23 2008 Aleksey Lim <alsroot@altlinux.org> 0.83.2-alt1
- new upstream release

* Fri Dec 12 2008 Aleksey Lim <alsroot@altlinux.org> 0.83.1-alt1
- Sugar 0.84 release cycle

* Sun Nov 23 2008 Aleksey Lim <alsroot@altlinux.org> 0.82.1-alt2
- change group tag to "Graphical desktop/Sugar"

* Sat Nov 08 2008 Aleksey Lim <alsroot@altlinux.org> 0.82.1-alt1
- first build for ALT Linux Sisyphus
