%ifnarch %ix86
%def_with check
%else
%def_without check
%endif
Name: ocaml-atd
Version: 4.0.0
Release: alt1
Summary: Parser for the ATD data format description language
Group: Development/ML
License: MIT
Url: https://github.com/ahrefs/atd
VCS: https://github.com/ahrefs/atd
Source0: %name-%version.tar

BuildRequires: ocaml >= 4.08
BuildRequires: dune >= 2.8
BuildRequires: ocaml-biniou-devel >= 1.0.6
BuildRequires: ocaml-cmdliner-devel >= 1.1.0
BuildRequires: ocaml-easy-format-devel
BuildRequires: ocaml-menhir >= 20180523
BuildRequires: ocaml-odoc-devel
BuildRequires: ocaml-re-devel >= 1.9.0
BuildRequires: ocaml-yojson-devel >= 1.6.0

%if_with check
BuildRequires: /usr/bin/scalac
BuildRequires: /usr/bin/javac
BuildRequires: gcc-c++
BuildRequires: ldc-devel
BuildRequires: rapidjson-devel
BuildRequires: zlib-devel
BuildRequires: ocaml-alcotest-devel
BuildRequires: python3-dev
BuildRequires: python3-module-flake8
BuildRequires: python3-module-jsonschema
BuildRequires: python3-module-mypy
BuildRequires: python3-module-pytest
%endif

%description
ATD is the OCaml library providing a parser for the ATD language and
various utilities. ATD stands for Adjustable Type Definitions in
reference to its main property of supporting annotations that allow a
good fit with a variety of data formats. This package also provides the
'atdcat' and 'atddiff' command-line utilities.

%package devel
Summary: Development files for ocaml-atd
Requires: %name = %EVR
Group: Development/ML

%description devel
Development files for ocaml-atd.

%package -n ocaml-atdcpp
Summary: C++ code generation for ATD APIs
Group: Development/ML

%description -n ocaml-atdcpp
C++ code generation for ATD APIs

%package -n ocaml-atdcpp-devel
Summary: Development files for ocaml-atdcpp
Requires: ocaml-atdcpp = %EVR
Group: Development/ML

%description -n ocaml-atdcpp-devel
Development files for ocaml-atdcpp.

%package -n ocaml-atdd
Summary: DLang code generation for ATD APIs
Group: Development/ML

%description -n ocaml-atdd
DLang code generation for ATD APIs

%package -n ocaml-atdd-devel
Summary: Development files for ocaml-atdd
Requires: ocaml-atdd = %EVR
Group: Development/ML

%description -n ocaml-atdd-devel
Development files for ocaml-atdd.

%package -n ocaml-atdgen-codec-runtime
Summary: Runtime for atdgen generated Melange converters
Group: Development/ML

%description -n ocaml-atdgen-codec-runtime
This library contains the types that are used by atdgen's Melange
backend

%package -n ocaml-atdgen-codec-runtime-devel
Summary: Development files for ocaml-atdgen-codec-runtime
Requires: ocaml-atdgen-codec-runtime = %EVR
Group: Development/ML

%description -n ocaml-atdgen-codec-runtime-devel
Development files for ocaml-atdgen-codec-runtime.

%package -n ocaml-atdgen-runtime
Summary: Runtime library for code generated by atdgen
Group: Development/ML

%description -n ocaml-atdgen-runtime
This package should be used only in conjunction with the atdgen code
generator

%package -n ocaml-atdgen-runtime-devel
Summary: Development files for ocaml-atdgen-runtime
Requires: ocaml-atdgen-runtime = %EVR
Group: Development/ML

%description -n ocaml-atdgen-runtime-devel
Development files for ocaml-atdgen-runtime.

%package -n ocaml-atdgen
Summary: Generates efficient JSON serializers, deserializers and validators
Group: Development/ML

%description -n ocaml-atdgen
Atdgen is a command-line program that takes as input type definitions in
the ATD syntax and produces OCaml code suitable for data serialization
and deserialization. Two data formats are currently supported, these are
biniou and JSON. Atdgen-biniou and Atdgen-json will refer to Atdgen used
in one context or the other. Atdgen was designed with efficiency and
durability in mind. Software authors are encouraged to use Atdgen
directly and to write tools that may reuse part of Atdgen's source
code.

%package -n ocaml-atdgen-devel
Summary: Development files for ocaml-atdgen
Requires: ocaml-atdgen = %EVR
Group: Development/ML

%description -n ocaml-atdgen-devel
Development files for ocaml-atdgen.

%package -n ocaml-atdj
Summary: Java code generation for ATD
Group: Development/ML

%description -n ocaml-atdj
Atdj is a program that generates a Java interface from type definitions.
In particular, given a set of ATD type definitions, this tool generates
a set of Java classes representing those types with built-in JSON
serializers and deserializers

%package -n ocaml-atdj-devel
Summary: Development files for ocaml-atdj
Requires: ocaml-atdj = %EVR
Group: Development/ML

%description -n ocaml-atdj-devel
Development files for ocaml-atdj.

%package -n ocaml-atdpy
Summary: Python/mypy code generation for ATD APIs
Group: Development/ML

%description -n ocaml-atdpy
Python/mypy code generation for ATD APIs

%package -n ocaml-atdpy-devel
Summary: Development files for ocaml-atdpy
Requires: ocaml-atdpy = %EVR
Group: Development/ML

%description -n ocaml-atdpy-devel
Development files for ocaml-atdpy.

%package -n ocaml-atds
Summary: ATD Code generator for Scala
Group: Development/ML

%description -n ocaml-atds
ATD Code generator for Scala

%package -n ocaml-atds-devel
Summary: Development files for ocaml-atds
Requires: ocaml-atds = %EVR
Group: Development/ML

%description -n ocaml-atds-devel
Development files for ocaml-atds.

%package -n ocaml-atdts
Summary: TypeScript code generation for ATD APIs
Group: Development/ML

%description -n ocaml-atdts
TypeScript code generation for ATD APIs

%package -n ocaml-atdts-devel
Summary: Development files for ocaml-atdts
Requires: ocaml-atdts = %EVR
Group: Development/ML

%description -n ocaml-atdts-devel
Development files for ocaml-atdts.

%prep
%setup

%build
%dune_build -p atd,atdcpp,atdd,atdgen-codec-runtime,atdgen-runtime,atdgen,atdj,atdpy,atds,atdts

%install
%dune_install_multi atd atdcpp atdd atdgen-codec-runtime atdgen-runtime atdgen atdj atdpy atds atdts

%check
%dune_check -p atd,atdcpp,atdd,atdgen-codec-runtime,atdgen-runtime,atdgen,atdj,atdpy,atdts

%files -f ocaml-files.runtime.atd

%files devel -f ocaml-files.devel.atd

%files -n ocaml-atdcpp -f ocaml-files.runtime.atdcpp

%files -n ocaml-atdcpp-devel -f ocaml-files.devel.atdcpp

%files -n ocaml-atdd -f ocaml-files.runtime.atdd

%files -n ocaml-atdd-devel -f ocaml-files.devel.atdd

%files -n ocaml-atdgen-codec-runtime -f ocaml-files.runtime.atdgen-codec-runtime

%files -n ocaml-atdgen-codec-runtime-devel -f ocaml-files.devel.atdgen-codec-runtime

%files -n ocaml-atdgen-runtime -f ocaml-files.runtime.atdgen-runtime

%files -n ocaml-atdgen-runtime-devel -f ocaml-files.devel.atdgen-runtime

%files -n ocaml-atdgen -f ocaml-files.runtime.atdgen

%files -n ocaml-atdgen-devel -f ocaml-files.devel.atdgen

%files -n ocaml-atdj -f ocaml-files.runtime.atdj

%files -n ocaml-atdj-devel -f ocaml-files.devel.atdj

%files -n ocaml-atdpy -f ocaml-files.runtime.atdpy

%files -n ocaml-atdpy-devel -f ocaml-files.devel.atdpy

%files -n ocaml-atds -f ocaml-files.runtime.atds

%files -n ocaml-atds-devel -f ocaml-files.devel.atds

%files -n ocaml-atdts -f ocaml-files.runtime.atdts

%files -n ocaml-atdts-devel -f ocaml-files.devel.atdts

%changelog
* Sun Apr 05 2026 Anton Farygin <rider@altlinux.org> 4.0.0-alt1
- 3.0.1 -> 4.0.0

* Fri Jan 02 2026 Anton Farygin <rider@altlinux.org> 3.0.1-alt1
- 2.16.0 -> 3.0.1

* Tue May 13 2025 Denis Rastyogin <gerben@altlinux.org> 2.16.0-alt1
- Initial build for ALT Sisyphus.
