# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-write-activity
Version: 69
Release: alt1.1
Summary: Word processor for Sugar
License: GPLv2+
Group: Graphical desktop/Sugar
Url: http://sugarlabs.org/
Packager: Sugar Development Team <sugar@packages.altlinux.org>
BuildArch: noarch

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Write/Write-69.tar.bz2

Requires: abiword >= 2.8
Requires: python-module-abiword  
Requires: sugar-toolkit >= 0.88.0

BuildPreReq: gettext  
BuildPreReq: sugar-toolkit >= 0.88.0

%description
The Write activity provides a word processor for the Sugar interface.

%prep
%setup -v -n Write-69


%build

rm -f MANIFEST
python setup.py build

%install
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.AbiWordActivity

%files -f org.laptop.AbiWordActivity.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc NEWS

%changelog
* Fri Oct 28 2011 Vitaly Kuznetsov <vitty@altlinux.ru> 69-alt1.1
- Rebuild with Python-2.7

* Wed Apr 07 2010 Aleksey Lim <alsroot@altlinux.org> 69-alt1
- Sucrose 0.88.0 release

* Thu Dec 03 2009 Eugeny A. Rostovtsev (REAL) <real at altlinux.org> 63-alt2.1
- Rebuilt with python 2.6

* Tue Apr 28 2009 Aleksey Lim <alsroot@altlinux.org> 63-alt2
- build against new abiword

* Thu Mar 19 2009 Aleksey Lim <alsroot@altlinux.org> 63-alt1
- new Sucrose 0.84.0 release

* Sun Feb 15 2009 Aleksey Lim <alsroot@altlinux.org> 61-alt2
- SL#356 fix

* Tue Jan 20 2009 Aleksey Lim <alsroot@altlinux.org> 61-alt1
- new Sucrose 0.83.4 release

* Sat Dec 13 2008 Aleksey Lim <alsroot@altlinux.org> 60-alt1
- Sugar 0.84 release cycle

* Sun Nov 23 2008 Aleksey Lim <alsroot@altlinux.org> 57-alt2
- change group tag to "Graphical desktop/Sugar"

* Tue Nov 18 2008 Aleksey Lim <alsroot@altlinux.org> 57-alt1
- first build for ALT Linux Sisyphus

