#
#   - MIME-Charset -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --spec-only MIME-Charset-1.008.1
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module MIME-Charset
%define m_distro MIME-Charset
%define m_name MIME-Charset
%define m_author_id unknown
%define _disable_test 1

Name: perl-MIME-Charset
Version: 1.008.1
Release: alt1

Summary: Charset Informations for MIME

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Slava Dubrovskiy <dubrsl@altlinux.org>

BuildArch: noarch
Source: %m_distro-%version.tar.gz
BuildRequires: perl-devel

%description
MIME::Charset - Charset Informations for MIME

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/MIME

%changelog
* Thu Feb 24 2011 Slava Dubrovskiy <dubrsl@altlinux.org> 1.008.1-alt1
- initial build for ALT Linux Sisyphus

