%define _unpackaged_files_terminate_build 1
%define mod_name hw_test

%ifarch %ix86 %e2k %mips riscv64
%def_disable check
%endif

Name: hw-test
Version: 2.2.0
Release: alt1

Summary: Hardware compatibility testing tool for ALT Linux
Summary(ru_RU): Инструмент тестирования оборудования для ALT Linux
Group: System/Configuration/Hardware
License: GPLv3+

BuildArch: noarch

Url: https://github.com/zerospirit79/hw-test
Source: %name-%version.tar
AutoReqProv: no
AutoReq: noshell, noshebang

BuildRequires(pre): rpm-build-python3 rpm-build-pyproject
BuildRequires: python3(setuptools)
BuildRequires: python3(wheel)
%{!?_disable_check:BuildRequires: shellcheck}
%{!?_disable_check:BuildRequires: python3-module-ruff}

# Python runtime (see also pyproject.toml)
Requires: python3 >= 3.9
Requires: python3-base
Requires: python3-module-psutil >= 5.9.0
Requires: python3-module-py-cpuinfo >= 9.0.0
Requires: python3-module-packaging >= 21.0
Requires: python3-module-pexpect >= 4.8.0

# Core system (pc-test methodology)
Requires: coreutils util-linux rpm apt apt-repo su sudo
Requires: bash update-kernel pciutils usbutils iproute2

# Hardware detection and logs
Requires: dmidecode
Requires: sos
Requires: system-report
Requires: acpica
Requires: lsscsi
Requires: lshw
Requires: inxi
Requires: hdparm
Requires: smartmontools
Requires: stress-ng
Requires: cpupower
Requires: sysfsutils

# Network
Requires: iputils
Requires: iperf3
Requires: iw
Requires: ethtool

# Optional methodology components (installed on demand when possible)
#Requires: fwupd
#Requires: glmark2
#Requires: mesa-dri-drivers
#Requires: alsa-utils
#Requires: pulseaudio-utils
#Requires: fio
#Requires: systemd-utils
#Requires: jq
#Requires: gzip
#Requires: numactl
#Requires: yad
#Requires: xdg-utils
#Requires: notify-send
#Requires: dialog
#Requires: ffmpeg
#Requires: bluez-tools
#Requires: libinput-tools
#Requires: evtest
#Requires: ipmitool
#Requires: pcsc-lite
#Requires: pcsc-tools

%description
hw-test is a hardware compatibility testing tool for ALT Linux, based on
the pc-test suite and Basealt SPO methodology. It performs automated tests
on CPU, memory, disk, network, graphics, audio, and other hardware
components with support for express testing, log collection, and resuming
after reboot.

%description -l ru_RU
hw-test — инструмент тестирования совместимости оборудования для ALT Linux
на базе pc-test и методики Basealt SPO. Выполняет автоматизированные тесты
процессора, памяти, дисков, сети, графики, аудио и других компонентов,
включая экспресс-тест, сбор журналов и продолжение после перезагрузки.

%package doc
Summary: HW Test Suite documentation
Summary(ru_RU): Документация hw-test
Group: Documentation
BuildArch: noarch
AutoReqProv: no
AutoReq: noshell, noshebang

%description doc
Documentation and screenshots for HW Test Suite, including the compatibility
testing methodology in HTML5 format.

%description -l ru_RU doc
Документация и скриншоты для hw-test, включая методику тестирования
совместимости в формате HTML5.

%prep
%setup -q
%autopatch -p1

%build
%pyproject_build
chmod 0755 usr/bin/%name \
	    usr/libexec/%name/resume.py \
	    usr/libexec/%name/resume.sh \
	    usr/libexec/%name/launcher.py \
	    usr/libexec/%name/launcher.sh
touch etc/%name-RVSETS.txt
cat >"./python3/hw_test/version.py" <<EOF
# Auto-generated by the build system, do not edit directly!
HWTEST_VERSION = "%version"
HWTEST_BUILD_DATE = "$(date '+%%Y%%m%%d')"
EOF

%install
%pyproject_install
mkdir -p -m 0755 -- "%buildroot"
mkdir -p -m 0755 -- "%buildroot%python3_sitelibdir"
cp -a python3/hw_test "%buildroot%python3_sitelibdir/"
mkdir -p -m 0755 -- "%buildroot%_libexecdir/%name"
cp -a usr/libexec/%name/l10n "%buildroot%_libexecdir/%name/"
install -m 0755 usr/libexec/%name/launcher.py "%buildroot%_libexecdir/%name/"
install -m 0755 usr/libexec/%name/launcher.sh "%buildroot%_libexecdir/%name/"
install -m 0755 usr/libexec/%name/resume.py "%buildroot%_libexecdir/%name/"
install -m 0755 usr/libexec/%name/resume.sh "%buildroot%_libexecdir/%name/"
mkdir -p -m 0755 -- "%buildroot%_bindir"
install -m 0755 usr/bin/%name "%buildroot%_bindir/%name"
mkdir -p -m 0755 -- "%buildroot%_datadir/applications"
sed "s|@hw_test_libdir@|%_libexecdir/%name|g" usr/share/applications/%name.desktop \
	> "%buildroot%_datadir/applications/%name.desktop"
sed "s|@hw_test_libdir@|%_libexecdir/%name|g" usr/share/applications/%name-autostart.desktop \
	> "%buildroot%_datadir/applications/%name-autostart.desktop"
chmod 0644 "%buildroot%_datadir/applications/%name.desktop" \
	"%buildroot%_datadir/applications/%name-autostart.desktop"
mkdir -p -m 0755 -- "%buildroot%_sysconfdir"
install -m 0644 etc/%name.conf "%buildroot%_sysconfdir/%name.conf"
install -m 0644 etc/%name-RVSETS.txt "%buildroot%_sysconfdir/%name-RVSETS.txt"
mkdir -p -m 0755 -- "%buildroot/etc/profile.d"
install -m 0644 etc/profile.d/hw-test-resume.sh "%buildroot/etc/profile.d/hw-test-resume.sh"
mkdir -p -m 0755 -- "%buildroot%_localstatedir/%name"
cp -a var/lib/%name/. "%buildroot%_localstatedir/%name/"
mkdir -p -m 0755 -- "%buildroot/usr/lib/systemd/system"
sed "s|@bindir@|%_bindir|g" usr/lib/systemd/system/%name-resume@.service \
	> "%buildroot/usr/lib/systemd/system/%name-resume@.service"
chmod 0644 "%buildroot/usr/lib/systemd/system/%name-resume@.service"

%post
rm -rf %_libexecdir/%name/hw_test 2>/dev/null ||:
if [ -d %_libexecdir/%name ] && [ %_libexecdir != /usr/libexec ] && [ ! -e /usr/libexec/%name ]; then
	mkdir -p /usr/libexec 2>/dev/null || true
	ln -snf %_libexecdir/%name /usr/libexec/%name 2>/dev/null || true
fi
if [ -f %_datadir/applications/%name-autostart.desktop ]; then
	for homedir in /home/*; do
		[ -d "$homedir" ] || continue
		user="$(basename "$homedir")"
		getent passwd "$user" >/dev/null 2>&1 || continue
		lastdir="$homedir/HW-TEST"
		[ -L "$lastdir" ] || continue
		[ -s "$lastdir/STATE/STEP" ] || continue
		mkdir -p "$homedir/.config/autostart"
		chown "$user:$user" "$homedir/.config/autostart" 2>/dev/null || true
		if [ -d "$homedir/.config" ] && [ "$(stat -c '%%U' "$homedir/.config")" = root ]; then
			chown "$user:$user" "$homedir/.config" 2>/dev/null || true
		fi
		cp -f %_datadir/applications/%name-autostart.desktop \
			"$homedir/.config/autostart/%name.desktop"
		chown "$user:$user" "$homedir/.config/autostart/%name.desktop"
		chmod 0644 "$homedir/.config/autostart/%name.desktop"
	done
fi
a="^(# Allow \\w+ to execute) %_bindir/%name without a password$"
b="\\1 %name and dmesg"
sed -i -E "s|$a|$b|g" /etc/sudoers
a="^(\\w+ ALL=\\(ALL:ALL\\) NOPASSWD: %_bindir/%name)$"
b="\\1,$(which dmesg)"
sed -i -E "s|$a|$b|g" /etc/sudoers

%check
%pyproject_run_pytest

%files
%_sysconfdir/%name.conf
%config(noreplace) %ghost %_sysconfdir/%name-RVSETS.txt
/etc/profile.d/hw-test-resume.sh
%_bindir/%name
%python3_sitelibdir/%mod_name
%_libexecdir/%name
%_datadir/applications/%name.desktop
%_datadir/applications/%name-autostart.desktop
%_localstatedir/%name
/usr/lib/systemd/system/%name-resume@.service
%python3_sitelibdir/%mod_name/
%python3_sitelibdir/%{pyproject_distinfo %mod_name}/

%files doc
%doc img html CHANGELOG.md LICENSE README.md

%changelog
* Fri Jun 06 2026 Pavel Shilov <zerospirit@altlinux.org> 2.2.0-alt1
- Initial build for Sisyphus
