# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: libhippo-canvas
Version: 0.3.0
Release: alt4.20081111.1
Summary: A canvas widget
License: GPL
Group: System/Libraries
Url: http://developer.mugshot.org/wiki/Hippo_Canvas
Packager: Sugar Development Team <sugar@packages.altlinux.org>

# git clone git://git.gnome.org/hippo-canvas libhippo-canvas-0.3.0 && cd libhippo-canvas-0.3.0 && git reset --hard 74a66f0aef549df7b64927fed03537f402cb229d
Source: libhippo-canvas-0.3.0-20081111.tar.bz2

BuildPreReq: libcairo-devel  
BuildPreReq: glib2-devel >= 2.6
BuildPreReq: libgtk+2-devel >= 2.6
BuildPreReq: gtk-doc >= 1.6
BuildPreReq: libcroco-devel >= 0.6
BuildPreReq: librsvg-devel >= 2.16
BuildPreReq: libpango-devel >= 1.14
BuildPreReq: pkg-config  
BuildPreReq: python-module-pycairo-devel  
BuildPreReq: python-module-pygobject-devel >= 2.15
BuildPreReq: python-module-pygtk-devel  
BuildPreReq: python-devel  

%description
Hippo Canvas is a canvas library based on GTK+2.0, Cairo and Pango.
It is used by the Mugshot client and by the Sugar UI.

%package devel
Summary: Development files for %name
Group: Development/GNOME and GTK+
Requires: %name = %version-%release
Requires: libcairo-devel  
Requires: libgtk+2-devel >= 2.6
Requires: libpango-devel >= 1.14
Requires: pkg-config  

%description devel
Hippo Canvas is a canvas library based on GTK+2.0, Cairo and Pango.
It is used by the Mugshot client and by the Sugar UI.

%package -n python-module-hippo-canvas
Summary: Python bindings for %name
Group: Development/Python
Requires: %name = %version-%release
Requires: python-module-pycairo  
Requires: python-module-pygobject >= 2.15
Requires: python-module-pygtk  
Requires: python  

%description -n python-module-hippo-canvas
Hippo Canvas is a canvas library based on GTK+2.0, Cairo and Pango.
It is used by the Mugshot client and by the Sugar UI.

%prep
%setup -v -n libhippo-canvas-0.3.0

%build
NOCONFIGURE=1 sh autogen.sh
%define __libtoolize true
%configure --enable-python --disable-static --disable-gtk-doc am_cv_python_pythondir=%{python_sitelibdir} am_cv_python_pyexecdir=%{python_sitelibdir}
make

%install
make DESTDIR=%{buildroot} install

%files 
%defattr(-,root,root,-)
%{_libdir}/*.so.*

%files devel
%{_includedir}/*
%{_libdir}/libhippocanvas*.so
%{_libdir}/pkgconfig/*.pc

%files -n python-module-hippo-canvas
%{python_sitelibdir}/*

%changelog
* Wed Oct 26 2011 Vitaly Kuznetsov <vitty@altlinux.ru> 0.3.0-alt4.20081111.1
- Rebuild with Python-2.7

* Tue Apr 06 2010 Aleksey Lim <alsroot@altlinux.org> 0.3.0-alt4.20081111
- rebuild

* Tue Nov 24 2009 Eugeny A. Rostovtsev (REAL) <real at altlinux.org> 0.3.0-alt3.20081111.1
- Rebuilt with python 2.6

* Mon Nov 23 2009 Aleksey Lim <alsroot@altlinux.org> 0.3.0-alt3.20081111
- rebuild

* Sat Dec 13 2008 Aleksey Lim <alsroot@altlinux.org> 0.3.0-alt2.20081111
- revert Group tag

* Sat Dec 13 2008 Aleksey Lim <alsroot@altlinux.org> 0.3.0-alt1.20081111
- Sugar 0.84 release cycle

* Sun Nov 16 2008 Aleksey Lim <alsroot@altlinux.org> 0.3.0-alt1.20080808
- first build for ALT Linux Sisyphus

