#
#   - Net::Syslogd -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   (ALT Linux revision)
#   The following arguments were used:
#       Net::Syslogd
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Net-Syslogd
%define m_distro Net-Syslogd
%define m_name Net::Syslogd
%define m_author_id unknown
%define _enable_test 1

Name: perl-Net-Syslogd
Version: 0.09
Release: alt1

Summary: Perl implementation of Syslog Listener

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Eugene Prokopiev <enp@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/V/VI/VINSWORLD/Net-Syslogd-%{version}.tar.gz

# Automatically added by buildreq on Tue Feb 28 2012
BuildRequires: perl-devel

%description
Net::Syslogd is a class implementing a simple Syslog listener in Perl.
Net::Syslogd will accept messages on the default Syslog port (UDP 514)
and attempt to decode them according to RFC 3164.

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Net/*

%changelog
* Wed Oct 17 2012 Igor Vlasenko <viy@altlinux.ru> 0.09-alt1
- automated CPAN update

* Tue Feb 28 2012 Eugene Prokopiev <enp@altlinux.ru> 0.04-alt1
- initial build for ALT Linux Sisyphus

