#
#   - Lingua::EN::Words2Nums -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   (ALT Linux revision)
#   The following arguments were used:
#       '--packager=Igor Vlasenko <viy@altlinux.ru>' --url http://search.cpan.org/CPAN/authors/id/J/JO/JOEY/Lingua-EN-Words2Nums-0.18.tar.gz Lingua-EN-Words2Nums-0.18.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Lingua-EN-Words2Nums
%define m_distro Lingua-EN-Words2Nums
%define m_name Lingua::EN::Words2Nums
%define m_author_id unknown
%define _enable_test 1

Name: perl-Lingua-EN-Words2Nums
Version: 0.18
Release: alt1

Summary: convert English text to numbers

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/CPAN/authors/id/J/JO/JOEY/Lingua-EN-Words2Nums-0.18.tar.gz

Packager: Igor Vlasenko <viy@altlinux.ru>

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Wed Sep 26 2012
BuildRequires: perl-devel

%description
This module converts English text into numbers. It supports both ordinal and
cardinal numbers, negative numbers, and very large numbers.

The main subroutine, which is exported by default, is words2nums(). This
subroutine, when fed a string, will attempt to convert it into a number.
If it succeeds, the number will be returned. If it fails, it returns undef.

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Lingua/*

%changelog
* Wed Sep 26 2012 Igor Vlasenko <viy@altlinux.ru> 0.18-alt1
- initial build for ALT Linux Sisyphus

