#
#   - Test::WWW::Mechanize -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --spec-only Test::WWW::Mechanize
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Test-WWW-Mechanize
%define m_distro Test-WWW-Mechanize
%define m_name Test::WWW::Mechanize
%define m_author_id unknown
%define _disable_test 1

Name: perl-Test-WWW-Mechanize
Version: 1.34
Release: alt1

Summary: Test-WWW-Mechanize - Testing-specific WWW::Mechanize subclass

License: Artistic
Group: Development/Perl
Url: %CPAN %m_distro

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/P/PE/PETDANCE/Test-WWW-Mechanize-1.34.tar.gz

# Automatically added by buildreq on Tue Jul 01 2008
BuildRequires: libnss-mdns perl-Carp-Assert-More perl-HTML-Lint perl-HTTP-Server-Simple perl-Test-LongString perl-Test-Pod perl-Test-Pod-Coverage perl-WWW-Mechanize

%description
Test::WWW::Mechanize is a subclass of WWW::Mechanize that incorporates
features for web application testing.  For example:

    $mech->get_ok( $page );
    $mech->title_is( "Invoice Status", "Make sure we're on the invoice page" );
    $mech->content_contains( "Andy Lester", "My name somewhere" );
    $mech->content_like( qr/(cpan|perl)\.org/, "Link to perl.org or CPAN" );

This is equivalent to:

    $mech->get( $page );
    ok( $mech->success );
    is( $mech->title, "Invoice Status", "Make sure we're on the invoice page" );
    ok( index( $mech->content, "Andy Lester" ) >= 0, "My name somewhere" );
    like( $mech->content, qr/(cpan|perl)\.org/, "Link to perl.org or CPAN" );

but has nicer diagnostics if they fail.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%perl_vendor_privlib/Test/*

%changelog
* Mon Sep 19 2011 Igor Vlasenko <viy@altlinux.ru> 1.34-alt1
- automated CPAN update

* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 1.30-alt1
- automated CPAN update

* Tue Dec 02 2008 Vitaly Lipatov <lav@altlinux.ru> 1.22-alt1
- new version 1.22 (with rpmrb script)
- remove man page, disable test

* Sat Sep 06 2008 Vitaly Lipatov <lav@altlinux.ru> 1.20-alt3
- fix directory ownership violation

* Tue Jul 01 2008 Vitaly Lipatov <lav@altlinux.ru> 1.20-alt2
- update buildreqs

* Tue Jul 01 2008 Vitaly Lipatov <lav@altlinux.ru> 1.20-alt1
- new version 1.20 (fix #16219)

* Sat Nov 11 2006 Vitaly Lipatov <lav@altlinux.ru> 1.10-alt0.1
- new version 1.10 (with rpmrb script)
- fix buildreq, source url, url

* Fri Sep 02 2005 Vitaly Lipatov <lav@altlinux.ru> 1.06-alt1
- first build for ALT Linux Sisyphus
