#
#   - Log::Dispatch::Config -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --debug Log::Dispatch::Config
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Log-Dispatch-Config
%define m_distro Log-Dispatch-Config
%define m_name Log::Dispatch::Config
%define m_author_id MIYAGAWA
%define _enable_test 1

Name: perl-Log-Dispatch-Config
Version: 1.04
Release: alt1

Summary: Log::Dispatch::Config - Log4j for Perl

License: Artistic and GPL
Group: Development/Perl
Url: http://search.cpan.org/dist/Log-Dispatch-Config/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Log-Dispatch-Config-1.04.tar.gz

# Automatically added by buildreq on Tue Jul 15 2008
BuildRequires: perl-AppConfig perl-IO-stringy perl-Log-Dispatch perl-devel

%description
Log::Dispatch::Config is a subclass of Log::Dispatch and provides a
way to configure Log::Dispatch object with configulation file
(default, in AppConfig format). I mean, this is log4j for Perl, not
with all API compatibility though.

%prep
%setup -q -n %m_distro-%version

%build
rm t/03_reload.t
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/*
%doc Changes README
%exclude %perl_vendor_archlib

%changelog
* Mon Sep 19 2011 Igor Vlasenko <viy@altlinux.ru> 1.04-alt1
- automated CPAN update

* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 1.03-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 1.03-alt1
- automated CPAN update

* Mon Oct 06 2008 Igor Vlasenko <viy@altlinux.ru> 1.02-alt1.1
- NMU for unknown reason:
  the person above was too neglectant to add --changelog "- NMU: <reason>" option.

* Tue Jul 15 2008 Michael Bochkaryov <misha@altlinux.ru> 1.02-alt1
- first build for ALT Linux Sisyphus

