%define oname pyramid_hsts

%def_with python3

Name: python-module-%oname
Version: 1.2.2
Release: alt1.git20141127
Summary: HTTP Strict Transport Security for a Pyramid application
License: Public domain
Group: Development/Python
Url: https://pypi.python.org/pypi/pyramid_hsts/
Packager: Eugeny A. Rostovtsev (REAL) <real at altlinux.org>

# https://github.com/thruflo/pyramid_hsts.git
Source: %name-%version.tar
BuildArch: noarch

BuildPreReq: python-devel python-module-setuptools-tests
BuildPreReq: python-module-pyramid python-module-coverage
BuildPreReq: python-module-nose python-module-mock
BuildPreReq: python-module-PasteDeploy python-module-zope.deprecation
BuildPreReq: python-module-repoze.lru python-module-zope.component
%if_with python3
BuildRequires(pre): rpm-build-python3
BuildPreReq: python3-devel python3-module-setuptools-tests
BuildPreReq: python3-module-pyramid python3-module-coverage
BuildPreReq: python3-module-nose python3-module-mock
BuildPreReq: python3-module-PasteDeploy python3-module-zope.deprecation
BuildPreReq: python3-module-repoze.lru python3-module-zope.component
%endif

%py_provides %oname

%description
Enforce HTTP Strict Transport Security for a Pyramid web application.

Features:

* adds a Strict-Transport-Security header to every response
* redirects requests with an insecure protocol to the corresponding
  secure protocol, i.e.: from http://... to https://...
* ensures urls generated by request.*_url methods (e.g.:
  request.route_url) use a secure protocol

%package -n python3-module-%oname
Summary: HTTP Strict Transport Security for a Pyramid application
Group: Development/Python3
%py3_provides %oname

%description -n python3-module-%oname
Enforce HTTP Strict Transport Security for a Pyramid web application.

Features:

* adds a Strict-Transport-Security header to every response
* redirects requests with an insecure protocol to the corresponding
  secure protocol, i.e.: from http://... to https://...
* ensures urls generated by request.*_url methods (e.g.:
  request.route_url) use a secure protocol

%prep
%setup

%if_with python3
cp -fR . ../python3
%endif

%build
%python_build_debug

%if_with python3
pushd ../python3
%python3_build_debug
popd
%endif

%install
%python_install

%if_with python3
pushd ../python3
%python3_install
popd
%endif

%check
python setup.py test
%if_with python3
pushd ../python3
python3 setup.py test
popd
%endif

%files
%doc *.md UNLICENSE
%python_sitelibdir/*

%if_with python3
%files -n python3-module-%oname
%doc *.md UNLICENSE
%python3_sitelibdir/*
%endif

%changelog
* Fri Nov 28 2014 Eugeny A. Rostovtsev (REAL) <real at altlinux.org> 1.2.2-alt1.git20141127
- Version 1.2.2

* Fri Oct 31 2014 Eugeny A. Rostovtsev (REAL) <real at altlinux.org> 1.1.4-alt1.git20140224
- Initial build for Sisyphus

