%define _unpackaged_files_terminate_build 1
#
#   - List::AllUtils -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       --version=0.02 List::AllUtils
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module List-AllUtils
%define m_distro List-AllUtils
%define m_name List::AllUtils
%define m_author_id unknown
%define _enable_test 1

Name: perl-List-AllUtils
Version: 0.14
Release: alt1

Summary: List-AllUtils - Perl module

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Kirill Maslinsky <kirill@altlinux.org>

BuildArch: noarch
Source0: http://www.cpan.org/authors/id/D/DR/DROLSKY/%{module}-%{version}.tar.gz

# Automatically added by buildreq on Mon Sep 14 2009
BuildRequires: perl-List-MoreUtils perl-Module-Build perl(Test/Warnings.pm) perl(List/SomeUtils.pm) perl(List/UtilsBy.pm)

%description
None.

%prep
%setup -q -n %{module}-%{version}


%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc CONTRIBUTING.md LICENSE README.md Changes
%perl_vendor_privlib/List/*

%changelog
* Tue Feb 14 2017 Igor Vlasenko <viy@altlinux.ru> 0.14-alt1
- automated CPAN update

* Thu Nov 17 2016 Igor Vlasenko <viy@altlinux.ru> 0.12-alt1
- automated CPAN update

* Thu May 26 2016 Igor Vlasenko <viy@altlinux.ru> 0.10-alt1
- automated CPAN update

* Tue Dec 16 2014 Igor Vlasenko <viy@altlinux.ru> 0.09-alt1
- automated CPAN update

* Tue Jun 17 2014 Igor Vlasenko <viy@altlinux.ru> 0.03-alt1
- automated CPAN update

* Mon Sep 14 2009 Kirill Maslinsky <kirill@altlinux.org> 0.02-alt1
- initial build for ALT Linux Sisyphus

