%define _unpackaged_files_terminate_build 1
# needed xvfb-run
%def_disable test

Name: perl-Gtk3-ImageView
Version: 10
Release: alt1

Summary: Image viewer widget for GTK 3

License: GPL+ or Artistic
Group: Development/Perl
Url: https://metacpan.org/release/Gtk3-ImageView

Packager: Vitaly Lipatov <lav@altlinux.ru>

Source0: http://www.cpan.org/authors/id/A/AS/ASOKOLOV/Gtk3-ImageView-%{version}.tar.gz

BuildArch: noarch

BuildRequires(pre): rpm-build-perl
BuildRequires: perl-devel

#BuildRequires: perl(ExtUtils::MakeMaker) >= 6.76
# Run-time:
#BuildRequires: perl(base)
BuildRequires: perl(Cairo.pm)
BuildRequires: perl(Carp.pm)
BuildRequires: perl(Glib.pm) >= 1.21
BuildRequires: perl(Glib/Object/Subclass.pm)
BuildRequires: perl(Gtk3.pm)
BuildRequires: perl(List/Util.pm)
BuildRequires: perl(POSIX.pm)
BuildRequires: perl(Readonly.pm)
BuildRequires: perl(Scalar/Util.pm)

# Tests:
#BuildRequires: perl(Carp::Always)
#BuildRequires: perl(English)
#BuildRequires: perl(File::Spec)
#BuildRequires: perl(File::Temp)
#BuildRequires: perl(Image::Magick)
#BuildRequires: perl(MIME::Base64)
BuildRequires: perl(Test/Differences.pm)
#BuildRequires: perl(Test::MockObject)
#BuildRequires: perl(Test::More)
#BuildRequires: perl(Try::Tiny)
#BuildRequires: xorg-x11-server-Xvfb

# Optional tests:
# git-core not used
# Test::Perl::Critic not used
#Requires: perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))
Requires: perl(if.pm)
Requires: perl(Glib.pm) >= 1.21

# Remove under-specified dependencies
#global __requires_exclude %{?__requires_exclude:%__requires_exclude|}^perl\\(Glib\\)$

%description
The Gtk3::ImageView widget allows the user to zoom, pan and select the
specified image and provides hooks to allow additional tools, e.g. painter,
to be created and used.

%prep
%setup -q -n Gtk3-ImageView-%{version}
# Bareword "Gtk3::Gdk::Display::get_default" not allowed while "strict subs"
sed -i -e "3iuse Gtk3;" lib/Gtk3/ImageView/Tool.pm

%build
%perl_vendor_build

%install
%perl_vendor_install

%check
#unset TEST_AUTHOR
#xvfb-run -d make test

%files
%doc README.md Changes README
%perl_vendor_privlib/*
#_man3dir/*

%changelog
* Tue Oct 05 2021 Igor Vlasenko <viy@altlinux.org> 10-alt1
- automated CPAN update

* Tue May 18 2021 Igor Vlasenko <viy@altlinux.org> 9-alt1
- automated CPAN update

* Thu Dec 03 2020 Vitaly Lipatov <lav@altlinux.ru> 6-alt1
- initial build for ALT Sisyphus

* Wed Nov 18 2020 Petr Pisar <ppisar@redhat.com> - 6-1
- Version 6 bump

* Mon Nov 02 2020 Petr Pisar <ppisar@redhat.com> 4-1
- Specfile autogenerated by cpanspec 1.78.
