#
#   - Net::SSH -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Net::SSH
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Net-SSH
%define m_distro Net-SSH
%define m_name Net::SSH
%define m_author_id unknown
%define _enable_test 1

Name: perl-Net-SSH
Version: 0.09
Release: alt1.1

Summary: Perl extension for secure shell

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Mikhail Pokidko <pma@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/I/IV/IVAN/Net-SSH-0.09.tar.gz

# Automatically added by buildreq on Wed Nov 15 2006
BuildRequires: perl-devel

%description
Simple wrappers around ssh commands.

For an all-perl implementation that does not require the system ssh command,
see Net::SSH::Perl instead.

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/*
%exclude %perl_vendor_archlib

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.09-alt1.1
- repair after perl 5.12 upgrade using girar-nmu

* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 0.09-alt1
- automated CPAN update

* Fri Sep 05 2008 Mikhail Pokidko <pma@altlinux.org> 0.08-alt2
- sisyphus_check fixes

* Wed Nov 15 2006 Mikhail Pokidko <pma@altlinux.ru> 0.08-alt1
- first build for ALT Linux Sisyphus

