%define _unpackaged_files_terminate_build 1
#
#   - IPC::Shareable -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#

%define module IPC-Shareable
%define m_distro IPC-Shareable
%define m_name IPC::Shareable
%define m_author_id unknown
# FIXME: tests dies with kernel.shm_destroy_unused = 1
%def_disable test

Name: perl-IPC-Shareable
Version: 1.12
Release: alt1

Summary: %m_name - share Perl variables between processes

License: GPL
Group: Development/Perl
Url: http://search.cpan.org/dist/IPC-Shareable/

BuildArch: noarch
Source0: http://www.cpan.org/authors/id/S/ST/STEVEB/%{module}-%{version}.tar.gz

# Automatically added by buildreq on Mon Sep 08 2008 (-bi)
BuildRequires: perl-Log-Agent perl-Storable perl-devel perl(JSON.pm) perl(String/CRC32.pm)
BuildRequires: perl-IPC-SysV

%description
IPC::Shareable allows you to tie a variable to shared memory making it
easy to share the contents of that variable with other Perl processes.
Scalars, arrays, and hashes can be tied.  The variable being tied may
contain arbitrarily complex data structures - including references to
arrays, hashes of hashes, etc.

%prep
%setup -q -n %{module}-%{version}

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc Changes README CREDITS DISCLAIMER docs examples
%perl_vendor_privlib/IPC*
%doc CREDITS DISCLAIMER README

%changelog
* Fri Mar 25 2022 Igor Vlasenko <viy@altlinux.org> 1.12-alt1
- automated CPAN update

* Fri Sep 17 2021 Igor Vlasenko <viy@altlinux.org> 1.06-alt1
- automated CPAN update

* Sun Jul 18 2021 Igor Vlasenko <viy@altlinux.org> 1.05-alt1
- automated CPAN update

* Thu Jul 01 2021 Igor Vlasenko <viy@altlinux.org> 1.04-alt1
- automated CPAN update

* Thu Jun 10 2021 Igor Vlasenko <viy@altlinux.org> 1.00-alt1
- automated CPAN update

* Wed Oct 17 2012 Igor Vlasenko <viy@altlinux.ru> 0.61-alt1
- automated CPAN update

* Sat Nov 06 2010 Vladimir Lettiev <crux@altlinux.ru> 0.60-alt2.1
- rebuilt with perl 5.12

* Mon Sep 08 2008 Michael Bochkaryov <misha@altlinux.ru> 0.60-alt2
- fix directory ownership violation
- spec file cleanup

* Thu Mar 22 2007 Sir Raorn <raorn@altlinux.ru> 0.60-alt1
- first build for ALT Linux Sisyphus

