#
#   - IPC::Shareable -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#

%define module IPC-Shareable
%define m_distro IPC-Shareable
%define m_name IPC::Shareable
%define m_author_id unknown
# FIXME: tests dies with kernel.shm_destroy_unused = 1
%def_disable test

Name: perl-IPC-Shareable
Version: 0.60
Release: alt2.1

Summary: %m_name - share Perl variables between processes

License: GPL
Group: Development/Perl
Url: http://search.cpan.org/dist/IPC-Shareable/

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/B/BS/BSUGARS/%m_distro-%version.tar.gz

# Automatically added by buildreq on Mon Sep 08 2008 (-bi)
BuildRequires: perl-Log-Agent perl-Storable perl-devel
BuildRequires: perl-IPC-SysV

%description
IPC::Shareable allows you to tie a variable to shared memory making it
easy to share the contents of that variable with other Perl processes.
Scalars, arrays, and hashes can be tied.  The variable being tied may
contain arbitrarily complex data structures - including references to
arrays, hashes of hashes, etc.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/IPC*
%doc CHANGES COPYING CREDITS DISCLAIMER README TO_DO

%changelog
* Sat Nov 06 2010 Vladimir Lettiev <crux@altlinux.ru> 0.60-alt2.1
- rebuilt with perl 5.12

* Mon Sep 08 2008 Michael Bochkaryov <misha@altlinux.ru> 0.60-alt2
- fix directory ownership violation
- spec file cleanup

* Thu Mar 22 2007 Sir Raorn <raorn@altlinux.ru> 0.60-alt1
- first build for ALT Linux Sisyphus

