%define _unpackaged_files_terminate_build 1
%define shortname edition

Name: alterator-interface-%{shortname}
Version: 0.3.0
Release: alt1

Summary: Alterator interface for edition
License: GPLv2+
Group: System/Configuration/Other
URL: https://altlinux.space/alterator/alterator-interface-edition

BuildArch: noarch
Source: %name-%version.tar

BuildRequires(pre): rpm-macros-alterator
BuildRequires: python3-devel

%description
%summary.

%package -n alterator-backend-%{shortname}
Summary: Alterator backend for edition
Group: System/Configuration/Other

Requires: alterator-backend-%{shortname}-utils = %EVR
Requires: alterator-interface-%{shortname}
Requires: alterator-module-executor >= 0.1.19

%description -n alterator-backend-%{shortname}
%summary.

%package -n alterator-backend-%{shortname}-utils
Summary: Scripts for alterator-backend-%{shortname}
Group: System/Configuration/Other

Requires: alterator-entry >= 0.2.0
Requires: distro-licenses
Requires: dconf

%description -n alterator-backend-%{shortname}-utils
%summary.

%prep
%setup

%install
%makeinstall_std
install -v -p -m 755 -D backend/%{shortname}.d/alterator-backend-edition.filetrigger %buildroot%_rpmlibdir/10-alterator-backend-edition.filetrigger

%files
%dir %_datadir/dbus-1
%dir %_datadir/dbus-1/interfaces
%dir %_datadir/polkit-1
%dir %_datadir/polkit-1/actions
%dir %_datadir/glib-2.0
%dir %_datadir/glib-2.0/schemas
%_datadir/dbus-1/interfaces/*.xml
%_datadir/polkit-1/actions/*.policy
%_datadir/glib-2.0/schemas/org.altlinux.alterator.edition.gschema.xml

%files -n alterator-backend-%{shortname}
%dir %_alterator_datadir/backends
%_alterator_datadir/backends/current_edition.backend
%dir %_alterator_libdir/backends/%{shortname}.d
%_alterator_libdir/backends/%{shortname}.d/generate-editions-backends
%_rpmlibdir/10-alterator-backend-edition.filetrigger

%files -n alterator-backend-%{shortname}-utils
%_alterator_libdir/backends/%{shortname}
%_alterator_libdir/backends/%{shortname}.py

%post -n alterator-backend-%{shortname}
%_alterator_libdir/backends/%{shortname}.d/generate-editions-backends

%preun -n alterator-backend-%{shortname}
if [ $1 = 0 ]; then
    find %_sysconfdir/alterator/backends -name "autogenerated-edition-*.backend" -type f -delete
fi

%changelog
* Sun Aug 10 2025 Kirill Sharov <sheriffkorov@altlinux.org> 0.3.0-alt1
- Move base logic for editions to alterator-backend-edition-utils subpackage with
  lightweight dependencies.
- Add more fallbacks to legacy paths.
- Read os-release before dconf for getting of edition is first of all.

* Fri Jul 25 2025 Kirill Sharov <sheriffkorov@altlinux.org> 0.2.0-alt1
- Add ReleaseNotes & FinalNotes methods for getting notes of edition
  with fallback to legacy path.

* Mon Jul 07 2025 Kirill Sharov <sheriffkorov@altlinux.org> 0.1.5-alt4
- Actualize URL of repository.

* Sat Mar 29 2025 Evgeny Sinelnikov <sin@altlinux.org> 0.1.5-alt3
- Avoid to try-restart alterator-manager.service due new release supported
  dynamic restart based on inotify.

* Fri Mar 14 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.5-alt2
- Add dconf to requires.

* Fri Mar 14 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.5-alt1
- Fix painfully slow filetrigger.

* Thu Mar 13 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.4-alt1
- Move dconf edition key to /org/altlinux/product/edition/current.
- Use dconf compile instead of dconf update.

* Thu Mar 13 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.3-alt1
- In filetrigger remove backends for removed .edition files

* Sat Mar 08 2025 Evgeny Sinelnikov <sin@altlinux.org> 0.1.2-alt1
- feat: add fallback to legacy license directory for current edition.

* Tue Feb 25 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.1-alt3
- Add missing distro-licenses dependency to backend.
- Add env variables to backends for alterator-manager.

* Thu Feb 20 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.1-alt2
- Fix extra edition_ in generated backend names.
- Declare used LC_ALL environment variable in backend (thx Andrey Alekseev).

* Tue Feb 04 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.1-alt1
- Return optional from get_edition_file.
- Refactor argparse to use functions.

* Fri Jan 10 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.0-alt1
- Initial build.
