#
#   - Probe::Perl -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       -debug -version 0.01 Probe::Perl
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Probe-Perl
%define m_distro Probe-Perl
%define m_name Probe::Perl
%define m_author_id unknown
%define _enable_test 1

Name: perl-Probe-Perl
Version: 0.01
Release: alt1

Summary: Information about the currently running perl

License: Artistic
Group: Development/Perl
Url: %CPAN %m_distro

Packager: Michael Bochkaryov <misha@altlinux.ru>

BuildArch: noarch
Source: %m_distro-%version.tar.gz

# Automatically added by buildreq on Sun Oct 18 2009 (-bi)
BuildRequires: perl-Module-Build

%description
This module provides methods for obtaining information about the
currently running perl interpreter. It originally began life as
code in the Module::Build project, but has been externalized here
for general use.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%perl_vendor_privlib/Probe/*

%changelog
* Sun Oct 18 2009 Michael Bochkaryov <misha@altlinux.ru> 0.01-alt1
- initial build for ALT Linux Sisyphus

