#
#   - String::Tokenizer -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       String::Tokenizer
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module String-Tokenizer
%define m_distro String-Tokenizer
%define m_name String::Tokenizer
%define m_author_id unknown
%define _enable_test 1

Name: perl-String-Tokenizer
Version: 0.05
Release: alt2.1

Summary: A simple string tokenizer

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org//CPAN/authors/id/S/ST/STEVAN/%m_distro-%version.tar.gz

# Automatically added by buildreq on Sat Nov 11 2006
BuildRequires: perl-Test-Pod perl-Test-Pod-Coverage

%description
A simple string tokenizer which takes a string and splits it on
whitespace. It also optionally takes a string of characters to use as
delimiters, and returns them with the token set as well. This allows
for splitting the string in many different ways.

This is a very basic tokenizer, so more complex needs should be either
addressed with a custom written tokenizer or post-processing of the output
generated by this module. Basically, this will not fill everyones needs,
but it spans a gap between simple "split / /, $string" and the other
options that involve much larger and complex modules.

Also note that this is not a lexical analyser. Many people confuse
tokenization with lexical analysis. A tokenizer mearly splits its
input into specific chunks, a lexical analyzer classifies those
chunks. Sometimes these two steps are combined, but not here.

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc Changes README
%perl_vendor_privlib/String/

%changelog
* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 0.05-alt2.1
- repair after perl 5.12 upgrade using girar-nmu

* Sat Sep 06 2008 Vitaly Lipatov <lav@altlinux.ru> 0.05-alt2
- fix directory ownership violation

* Sat Nov 11 2006 Vitaly Lipatov <lav@altlinux.ru> 0.05-alt1
- first build for ALT Linux Sisyphus

