%define hsc_name ghc
%define hsc_version %ghc_version
%define hsc_namever %hsc_name
%define h_pkg_name html
%define f_pkg_name html
%define pkg_libdir %_libdir/%hsc_name-%hsc_version/lib/%h_pkg_name-%version

Name: %hsc_namever-%f_pkg_name
Version: 1.0.1.2
Release: alt3
License: BSD
Packager: Alex V. Myltsev <avm@altlinux.ru>
Group: Development/Haskell
Source: %f_pkg_name-%version.tar.gz
Summary: HTML combinator library
BuildRequires(pre): rpm-build-haskell


%description
This package contains a combinator library for constructing
HTML documents.

%prep
%setup -n %h_pkg_name-%version

%build
%hs_configure2
%hs_build

%install
%hs_install
%hs_gen_filelist

cd %buildroot%_datadir/doc/%name-%version
rm -rf doc LICENSE examples

%files -f %name-files.nonprof
%hs_pkgconfdir/%f_pkg_name-%version.conf
%doc dist/doc/html
#%%doc LICENSE examples

%changelog
* Wed Nov 23 2011 Vitaly Kuznetsov <vitty@altlinux.ru> 1.0.1.2-alt3
- rebuild

* Sat Aug 13 2011 Denis Smirnov <mithraen@altlinux.ru> 1.0.1.2-alt2.1.1
- rebuild with shared objects support

* Tue Dec 07 2010 Denis Smirnov <mithraen@altlinux.ru> 1.0.1.2-alt2.1
- rebuild with ghc 7.0/var/lib/altlinux/sisyphus/files/SRPMS/ghc-ansi-terminal-0.5.3-alt1.src.rpm

* Thu Sep 09 2010 Denis Smirnov <mithraen@altlinux.ru> 1.0.1.2-alt2
- ghc 6.12.3

* Thu Sep 09 2010 Denis Smirnov <mithraen@altlinux.ru> 1.0.1.2-alt1.1.1
- rebuild with new haskell

* Wed Mar 17 2010 Denis Smirnov <mithraen@altlinux.ru> 1.0.1.2-alt1.1
- rebuild with new haskell

* Fri Nov 14 2008 Alexander Myltsev <avm@altlinux.ru> 1.0.1.2-alt1
- Add category entry to the cabal file.

* Mon Jan 14 2008 Alex V. Myltsev <avm@altlinux.ru> 1.0.1.1-alt2
- Use package.conf.d.

* Wed Jan 09 2008 Alex V. Myltsev <avm@altlinux.ru> 1.0.1.1-alt1
- spec file autogenerated by cabal-rpm
