%define _unpackaged_files_terminate_build 1
%define module_name Nmap-Parser

Name: perl-%module_name
Version: 1.37
Release: alt1

Summary: Parse nmap scan data with perl
License: MIT
Group: Development/Perl

URL: %CPAN %module_name
# See also: http://code.google.com/p/nmap-parser/
Source0: http://www.cpan.org/authors/id/A/AP/APERSAUD/%{module_name}-%{version}.tar.gz

# Automatically added by buildreq on Sat Aug 13 2011
BuildRequires: nmap perl-XML-Twig perl-devel

BuildArch: noarch

%description
This module implements interface to the information contained in a nmap scan.
It is implemented by parsing the xml scan data that is generated by nmap.
This will enable anyone who utilizes nmap to quickly create fast and robust
security scripts that utilize the powerful port scanning abilities of nmap.

%prep
%setup -q -n %{module_name}-%{version}

%build
rm -f ._*
%perl_vendor_build

%install
%perl_vendor_install

%files
%doc tools/* Changes.md README.md
%perl_vendor_privlib/Nmap/

%changelog
* Wed Jan 30 2019 Igor Vlasenko <viy@altlinux.ru> 1.37-alt1
- automated CPAN update

* Wed Aug 02 2017 Igor Vlasenko <viy@altlinux.ru> 1.36-alt1
- automated CPAN update

* Sun Dec 18 2016 Igor Vlasenko <viy@altlinux.ru> 1.33-alt1
- automated CPAN update

* Wed Jul 24 2013 Igor Vlasenko <viy@altlinux.ru> 1.31-alt1
- automated CPAN update

* Sat Aug 13 2011 Victor Forsiuk <force@altlinux.org> 1.21-alt1
- 1.21

* Mon Nov 22 2010 Igor Vlasenko <viy@altlinux.ru> 1.19-alt2.1
- repair after perl 5.12 upgrade using girar-nmu

* Mon Feb 01 2010 Victor Forsyuk <force@altlinux.org> 1.19-alt2
- Fix repocop warning macos-resource-fork-file-in-package.

* Tue Dec 30 2008 Victor Forsyuk <force@altlinux.org> 1.19-alt1
- 1.19

* Fri Aug 01 2008 Victor Forsyuk <force@altlinux.org> 1.16-alt1
- 1.16

* Tue Mar 04 2008 Victor Forsyuk <force@altlinux.org> 1.13-alt1
- 1.13

* Sat Jun 16 2007 Victor Forsyuk <force@altlinux.org> 1.11-alt1
- Initial build.
