#
#   - Net::Pcap::Reassemble -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Net::Pcap::Reassemble
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Net-Pcap-Reassemble
%define m_distro Net-Pcap-Reassemble
%define m_name Net::Pcap::Reassemble
%define m_author_id unknown
%define _enable_test 1

Name: perl-Net-Pcap-Reassemble
Version: 0.05
Release: alt1

Summary: IP fragment reassembly for Net::Pcap

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Denis Smirnov <mithraen@altlinux.ru>

BuildArch: noarch
Source: http://www.cpan.org/authors/id/J/JR/JRAFTERY/Net-Pcap-Reassemble-0.05.tar.gz

# Automatically added by buildreq on Sat Nov 07 2009
BuildRequires: perl-Net-Pcap perl-devel

%description
This module performs reassembly of fragmented datagrams in libpcap
packet capture data returned by the Net::Pcap "loop()" function.
This module supports reassembly of IPv4 and IPv6 fragments.

%prep
%setup -q -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%perl_vendor_privlib/Net/*

%changelog
* Tue Jul 13 2010 Igor Vlasenko <viy@altlinux.ru> 0.05-alt1
- automated CPAN update

* Sat Nov 07 2009 Denis Smirnov <mithraen@altlinux.ru> 0.04-alt1
- initial build for ALT Linux Sisyphus

