%define _unpackaged_files_terminate_build 1
%define shortname component

Name: alterator-backend-%{shortname}
Version: 0.3.1
Release: alt1

Summary: Backends generations for components backends
License: GPLv2+
Group: System/Configuration/Other
URL: https://altlinux.space/alterator/alterator-backend-component

BuildArch: noarch

Source0: %name-%version.tar

Requires: alterator-interface-%{shortname} = %EVR
Requires: alterator-module-executor >= 0.1.29
Requires: alterator-entry >= 0.2.0
Requires: alterator-backend-systeminfo >= 0.4.1

Provides: alterator-backend-component_categories = %EVR
Provides: alterator-backend-batch-components = 0.3.1-alt2
Provides: alterator-backend-batch-component_categories = 0.3-alt3

Obsoletes: alterator-backend-component_categories < 0.1.5-alt3
Obsoletes: alterator-backend-batch-components < 0.3.1-alt2
Obsoletes: alterator-backend-batch-component_categories < 0.3-alt3

BuildRequires(pre): rpm-macros-alterator
BuildRequires: python3-devel

%description
%summary.

%package -n alterator-interface-%{shortname}
Summary: Components interface for alterator browser
Group: System/Configuration/Other

Provides: alterator-interface-component_categories = 0.1.0-alt2

Obsoletes: alterator-interface-component_categories < 0.1.0-alt2

%description -n alterator-interface-%{shortname}
%summary.

%prep
%setup

%install
%makeinstall_std
install -v -p -m 755 -D alterator-backend-component.filetrigger %buildroot%_rpmlibdir/10-%{name}.filetrigger

%files
%_alterator_libdir/backends
%_alterator_datadir/backends
%_rpmlibdir/10-%{name}.filetrigger

%files -n alterator-interface-component
%_datadir/polkit-1/actions
%_datadir/dbus-1/interfaces

%post
%_alterator_libdir/backends/component.d/generate-components-backends

%preun
if [ $1 = 0 ]; then
    find %_sysconfdir/alterator/backends -name "autogenerated-component-*.backend" -type f -delete
fi

%changelog
* Fri Nov 28 2025 Kirill Sharov <sheriffkorov@altlinux.org> 0.3.1-alt1
- Add 'exit_status = true' for new version of executor.

* Mon Sep 01 2025 Kirill Sharov <sheriffkorov@altlinux.org> 0.3.0-alt1
- Use 'as' instead 'ay' for batch interfaces.
- Insert quotes for string values in Alterator entries.

* Thu Aug 14 2025 Kirill Sharov <sheriffkorov@altlinux.org> 0.2.0-alt1
- Merge all scripts of components, component categories and batch to one.
- Unify CLI arg format: use name of component/category instead file path.
- Add --path option for getting file path instead content.
- Add list command for getting list of entities.
- Add LICENSE.
- Rename source package to alterator-backend-component.


* Mon Aug 11 2025 Kirill Sharov <sheriffkorov@altlinux.org> 0.1.10-alt1
- Fix path of systeminfo according new version.

* Mon Jul 07 2025 Kirill Sharov <sheriffkorov@altlinux.org> 0.1.9-alt2
- Actualize URL of repository.

* Mon Mar 31 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.9-alt1
- Filter using DEs, language and kflavour from system.

* Sat Mar 29 2025 Evgeny Sinelnikov <sin@altlinux.org> 0.1.8-alt4
- Avoid to try-restart alterator-manager.service due new release supported
  dynamic restart based on inotify.

* Mon Feb 24 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.8-alt3
- Add LC_ALL as env variable for alterator-manager to fix Description
  translations.

* Tue Feb 18 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.8-alt2
- Remove extra output in basic_check_component_installed

* Tue Feb 04 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.8-alt1
- basic_check_component_installed now works even without
  edition present
- Update path to current_edition_helper.py script

* Fri Jan 31 2025 Michael Chernigin <chernigin@altlinux.org> 0.1.7-alt1
- Rewrite scripts in python.
- Take into account current edition.
- Add filetrigger to generate backends.

* Tue Dec 24 2024 Michael Chernigin <chernigin@altlinux.org> 0.1.6-alt1
- Return installed packages in status method.

* Thu Dec 19 2024 Michael Chernigin <chernigin@altlinux.org> 0.1.5-alt1
- Add support for python3.9.

* Mon Dec 09 2024 Michael Chernigin <chernigin@altlinux.org> 0.1.4-alt1
- Switch to Alterator Entry in toml.
- Change getDescription to return array of bytes instead of strings.

* Tue Oct 22 2024 Michael Chernigin <chernigin@altlinux.org> 0.1.3-alt1
- Change prefix from ru.basealt to org.altlinux.

* Mon Sep 23 2024 Michael Chernigin <chernigin@altlinux.org> 0.1.2-alt1
- Fix install status of virtual packages.

* Thu Jun 27 2024 Michael Chernigin <chernigin@altlinux.org> 0.1.1-alt1
- Improve performance of basic check for component installed.

* Thu Jun 27 2024 Michael Chernigin <chernigin@altlinux.org> 0.1.0-alt1
- Initial build.
