%define _unpackaged_files_terminate_build 1
%define sover 1

%def_with check

Name: libstorage-ng
Version: 4.5.355
Release: alt1

Summary: Library for storage management
License: GPL-2.0-only
Group: System/Libraries
URL: https://github.com/openSUSE/libstorage-ng
VCS: https://github.com/openSUSE/libstorage-ng.git

Source: %name-%version.tar
Patch: %name-%version-%release.patch

BuildRequires(pre): rpm-macros-python3
BuildRequires(pre): rpm-macros-ruby
BuildRequires: rpm-build-python3
BuildRequires: rpm-build-ruby
BuildRequires: gcc-c++
BuildRequires: boost-devel
BuildRequires: libxml2-devel
BuildRequires: libjson-c-devel
BuildRequires: swig
BuildRequires: python3-dev
BuildRequires: ruby
BuildRequires: libruby-devel
BuildRequires: doxygen
BuildRequires: graphviz
%if_with check
BuildRequires: /proc
BuildRequires: strace
BuildRequires: glibc-locales
BuildRequires: gem-test-unit
%endif

%description
libstorage-ng is a C++ library for storage management. It handles disks,
partition tables, LVM, MD RAID, bcache, encryption (LUKS, BitLocker)
and many file systems, keeping all devices and their relations in a graph.

%package -n %name%sover
Summary: Library for storage management
Group: System/Libraries
Requires: %name-common
Requires: parted
Requires: lsscsi
Requires: dmsetup
Requires: util-linux
Requires: udev

%description -n %name%sover
libstorage-ng is a C++ library for storage management. It handles disks,
partition tables, LVM, MD RAID, bcache, encryption (LUKS, BitLocker)
and many file systems, keeping all devices and their relations in a graph.

%package common
Summary: Data files and translations for libstorage-ng
Group: System/Libraries
BuildArch: noarch

%description common
This package contains data files and translations for libstorage-ng.

%package devel
Summary: Development files for libstorage-ng
Group: Development/C++
Requires: %name%sover = %EVR
# used by the public headers
Requires: libxml2-devel
Requires: boost-devel-headers

%description devel
This package contains header files for developing with libstorage-ng.

%package doc
Summary: API documentation for libstorage-ng
Group: Documentation
BuildArch: noarch

%description doc
This package contains the libstorage-ng API documentation generated by doxygen.

%package -n python3-module-%name
Summary: Python 3 bindings for libstorage-ng
Group: Development/Python3
Requires: %name%sover = %EVR

%description -n python3-module-%name
This package contains Python 3 bindings (module "storage") for libstorage-ng.

%package -n ruby-%name
Summary: Ruby bindings for libstorage-ng
Group: Development/Ruby
Requires: %name%sover = %EVR
Requires: ruby

%description -n ruby-%name
This package contains Ruby bindings (module "storage") for libstorage-ng.

%package utils
Summary: Utilities for libstorage-ng
Group: Development/Other

%description utils
This package contains helper utilities for libstorage-ng.

%package integration-tests
Summary: Integration tests for libstorage-ng
Group: Development/Other
BuildArch: noarch
Requires: python3-module-%name = %EVR

%description integration-tests
This package contains integration tests for libstorage-ng. They must be run
as root and modify real block devices.

%prep
%setup
%autopatch -p1
# upstream generates it from git tags
echo %version > VERSION

%build
# as upstream builds it: disables boost assertions (BOOST_ASSERT)
%add_optflags -DNDEBUG
# ruby arch headers are not under rubyhdrdir on ALT
export CPPFLAGS="-I$(ruby -rrbconfig -e 'print RbConfig::CONFIG["rubyarchhdrdir"]')"
%autoreconf
%configure \
	--docdir=%_docdir/%name \
	--disable-static \
	--disable-silent-rules
%make_build

%install
%makeinstall_std
find %buildroot -name '*.la' -delete
# packaged in the library as doc files
rm %buildroot%_docdir/%name/AUTHORS %buildroot%_docdir/%name/LICENSE
%find_lang %name

%check
# xml.test is linked without -lxml2 upstream
%make_build check VERBOSE=1 \
	'xml_test_LDADD=$(LDADD) $(XML_LIBS)' \
	LIBSTORAGE_CONFDIR=%buildroot%_datadir/libstorage \
	LIBSTORAGE_LOCALEDIR=%buildroot%_datadir/locale

%files -n %name%sover
%doc AUTHORS LICENSE
%_libdir/%name.so.%sover
%_libdir/%name.so.%sover.*

%files common -f %name.lang
%dir %_datadir/libstorage
%_datadir/libstorage/udev-filters.json

%files devel
%_libdir/%name.so
%_includedir/storage

%files doc
%_docdir/%name

%files -n python3-module-%name
%python3_sitelibdir_noarch/storage.py
%python3_sitelibdir_noarch/__pycache__/storage.*
%python3_sitelibdir/_storage.so

%files -n ruby-%name
%ruby_vendorarchdir/storage.so

%files utils
%dir %_libexecdir/%name
%_libexecdir/%name/utils

%files integration-tests
%python3_sitelibdir_noarch/storageitu.py
%python3_sitelibdir_noarch/__pycache__/storageitu.*
%dir %_libexecdir/%name
%_libexecdir/%name/integration-tests

%changelog
* Sat Sep 26 2026 Dmitry Udalov <udalov@altlinux.org> 4.5.355-alt1
- Initial build for Sisyphus.
