%define target_lua_version 5.4

# Original package name tree-sitter-teal
%define oname tree-sitter-teal
%define oversion 0.0.33-1
%define rockspec tree-sitter-teal-0.0.33-1.rockspec
Name: lua%target_lua_version-module-%oname
Version: 0.0.33
Release: alt1_lr1
Summary: tree-sitter parser for teal
License: MIT
Group: Development/Other
Url: https://github.com/euclidianAce/tree-sitter-teal

Source: https://github.com/euclidianAce/tree-sitter-teal/archive/3db655924b2ff1c54fdf6371b5425ea6b5dccefe.zip#/%oname-3db655924b2ff1c54fdf6371b5425ea6b5dccefe.zip
Source1: https://luarocks.org/manifests/neorocks/tree-sitter-teal-0.0.33-1.rockspec

BuildPreReq: rpm-macros-lua >= 1.5.2 rpm-build-lua
BuildRequires: liblua%target_lua_version-devel lua%target_lua_version-luarocks
BuildRequires: luarocks%target_lua_version(luarocks-build-treesitter-parser) >= 5.0.0

%description
see homepage

%prep
%setup -n %oname-3db655924b2ff1c54fdf6371b5425ea6b5dccefe

%install
%luarocks_make %SOURCE1
%luarocks_move_docs doc
# FIXME: move to rpm-macros-lua
echo Fixing Lua interpreter path
find %buildroot -type f -name '*.lua' \
  -exec grep 'env lua$' {} \; \
  -exec subst '1 s/env lua$/env lua%target_lua_version/' '{}' ';' \
  -print

%check
%lua_path_add_buildroot
make test

%add_findreq_skiplist %luarocks_dbdir_prefix-*/%oname/*/{doc,docs,etc,examples,samples,spec,test}/*

%files
%lua_modulesdir/*
%luarocks_dbdir_prefix-%target_lua_version/%oname
%doc LICENSE* README*
%exclude %luarocks_dbdir_prefix-%target_lua_version/manifest
%exclude %luarocks_dbdir_prefix-%target_lua_version/%oname/*/parser

%changelog
* Tue Apr 29 2025 Ildar Mulyukov <ildar@altlinux.ru> 0.0.33-alt1_lr1
- autogenerated by lrimport
