#
#   - Dist-CheckConflicts -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   (ALT Linux revision)
#   The following arguments were used:
#       '--packager=Igor Vlasenko <viy@altlinux.ru>' --url http://search.cpan.org/CPAN/authors/id/D/DO/DOY/Dist-CheckConflicts-0.02.tar.gz http://search.cpan.org/CPAN/authors/id/D/DO/DOY/Dist-CheckConflicts-0.02.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Dist-CheckConflicts
%define m_distro Dist-CheckConflicts
%define m_name Dist-CheckConflicts
%define m_author_id unknown
%define _enable_test 1

Name: perl-Dist-CheckConflicts
Version: 0.02
Release: alt1

Summary: declare version conflicts for your dist

License: Artistic
Group: Development/Perl
Url: http://search.cpan.org/CPAN/authors/id/D/DO/DOY/Dist-CheckConflicts-0.02.tar.gz

Packager: Igor Vlasenko <viy@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org/CPAN/authors/id/D/DO/DOY/%m_distro-%version.tar.gz

BuildRequires: perl(Test/Fatal.pm) perl(List/MoreUtils.pm) perl(Sub/Exporter.pm)

%description
Dist::CheckConflicts declare version conflicts for your dist.

%prep
%setup -n %m_distro-%version
%build
%perl_vendor_build

%install
%perl_vendor_install

%files
%perl_vendor_privlib/Dist/*

%changelog
* Sun Sep 25 2011 Igor Vlasenko <viy@altlinux.ru> 0.02-alt1
- initial build for ALT Linux Sisyphus

