#
#   - Graph-ReadWrite -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   (ALT Linux revision)
#   The following arguments were used:
#       Graph::ReadWrite
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define module Graph-ReadWrite
%define m_distro Graph-ReadWrite
%define m_name Graph-ReadWrite
%define m_author_id unknown
%define _enable_test 1

Name: perl-Graph-ReadWrite
Version: 2.00
Release: alt2

Summary: Graph::Reader::Dot - class for reading a Graph instance from Dot format

License: Artistic
Group: Development/Perl
Url: http://www.cpan.org

Packager: Vitaly Lipatov <lav@altlinux.ru>

BuildArch: noarch
Source: http://search.cpan.org/CPAN/authors/id/N/NE/NEILB/%m_distro-%version.tar.bz2

# Automatically added by buildreq on Mon Jun 23 2008
BuildRequires: perl-Graph perl-XML-Parser perl-XML-Writer perl-devel

%description
Graph::Reader::Dot is a class for reading in a directed graph in the
file format used by the dot tool (part of the AT+T graphviz package).

%prep
%setup -q -n %m_distro-%version

%build
%perl_vendor_build

%install
%perl_vendor_install
rm -rf %buildroot%perl_vendor_man3dir/

%files
%perl_vendor_privlib/Graph/

%changelog
* Sat Sep 06 2008 Vitaly Lipatov <lav@altlinux.ru> 2.00-alt2
- fix directory ownership violation
- disable man packaging

* Mon Jun 23 2008 Vitaly Lipatov <lav@altlinux.ru> 2.00-alt1
- initial build for ALT Linux Sisyphus

