%define target_lua_version 5.4

# Original package name lua-protobuf
%define oname lua-protobuf
%define oversion 0.5.2-1
%define rockspec lua-protobuf-0.5.2-1.rockspec
Name: lua%target_lua_version-module-%oname
Version: 0.5.2
Release: alt1_lr1
Summary: protobuf data support for Lua
License: MIT
Group: Development/Other
Url: https://github.com/starwing/lua-protobuf

Source: https://github.com/starwing/lua-protobuf/archive/refs/tags/0.5.2.tar.gz#/lua-protobuf-%version.tar.gz
Source1: https://luarocks.org/manifests/xavier-wang/lua-protobuf-0.5.2-1.rockspec

BuildPreReq: rpm-macros-lua >= 1.5.2 rpm-build-lua
# Automatically added by buildreq on ...
BuildRequires: liblua%target_lua_version-devel lua%target_lua_version-luarocks

%description
This project offers a simple C library for basic protobuf wire format encode/decode.

%prep
%setup -n %oname-%version

%install
%luarocks_make %SOURCE1
%luarocks_move_docs doc
echo Fixing Lua interpreter path
find %buildroot -type f -name '*.lua' \
  -exec grep 'env lua$' {} \; \
  -exec subst '1 s/env lua$/env lua%target_lua_version/' '{}' ';' \
  -print

%check
%lua_path_add_buildroot
# needs luaunit
#%%lua test.lua

%add_findreq_skiplist %luarocks_dbdir_prefix-*/%oname/*/{doc,docs,etc,examples,samples,spec,test}/*

%files
%lua_modulesdir/*
%lua_modulesdir_noarch/*
%luarocks_dbdir_prefix-%target_lua_version/%oname
%doc docs_from_rockstree/*
%exclude %luarocks_dbdir_prefix-%target_lua_version/manifest

%changelog
* Wed Mar 12 2025 Ildar Mulyukov <ildar@altlinux.ru> 0.5.2-alt1_lr1
- autogenerated by lrimport
